---
# ansible-playbook --vault-id nrcyer@prompt /etc/ansible_bioit/playbook/bioit/bioit-bigsdb.yml --tags "bioperl" -e "target=bioit-nrcyer-dev species=yersinia branch=dev_ASG mongo_dtap=dev" --vault-password-file "/etc/ansible_bioit/vault/bioit_vault_pass"
# use --tags if needed
- hosts: "{{ target }}"
  gather_facts: True
  become: yes

  pre_task:
    - name: Ensure binary directory exists for database access config file
      file:
        path: "/etc/bioit"
        state: directory
      become: yes

  roles:
    - { name: bioit.locale, become: yes }
    - { name: bioit.postgresql }
    - { name: bioit.filedb }
    - { name: bioit.tools }
    - { name: bioit.bigsdb }
...
