---
# Disclaimer: this role only works for exactly three replica set members provided by --limit to the playbook, if ever using more then to be defined in task "Initialise replicaset"
- name: check if dtap in list
  vars:
    dtaplist:
      - dt
      - ap
  fail:
    msg: "unsupported dtap requested, choose from {{ dtaplist }}"
  when: dtap not in dtaplist

- name: Copy mongodb gpg key
  get_url:
    url: "{{ linux_repo }}/gpg_keys/mongodb-archive-keyring.gpg"
    dest: /usr/share/keyrings/mongodb-archive-keyring.gpg
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install mongodb source list
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] {{ linux_repo}}/mongodb {{ ansible_distribution_release }}/mongodb-org/6.0 multiverse'
    filename: mongodb
    state: present

- name: install mongodb package
  apt:
    name: mongodb-org

# I hope that if these directories exist, that their ownership is still modified
- name: create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: mongodb
    group: mongodb
  loop:
    - /var/lib/mongodb
    - "{{ keyfilebasepath }}"

- name: Copy mongodb keyfile from vault
  ansible.builtin.copy:
    content: "{{ secret_mongodb_keystring }}"
    dest: "{{ keyfilepath }}"
    owner: mongodb
    group: mongodb
    mode: '0600'

- name: Copy mongod config file
  ansible.builtin.template:
    src: /etc/ansible/roles/bioit.mongodb/templates/mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'

- name: Start Mongod service
  ansible.builtin.systemd:
    state: started
    name: mongod
    enabled: yes

- name: ansible debug; trial to get a list of hostnames for the replicaset members
  ansible.builtin.debug:
    msg: "this ({{ play_hosts[host_index] }}) is the hostname"
  loop: "{{ range(0, play_hosts|length) | list }}"
  loop_control:
    loop_var: host_index
  when: inventory_hostname == play_hosts[0]

- name: Install pymongo globally
  ansible.builtin.pip:
    name: pymongo

# ansible-galaxy collection install community.mongodb
- name: Initialise replicaset
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ vars['mongodb_admin_password_'+dtap] }}"
    replica_set: "{{ replica_set_name }}"
    members:
      - "{{ play_hosts[0] }}:{{ port }}"
      - "{{ play_hosts[1] }}:{{ port }}"
      - "{{ play_hosts[2] }}:{{ port }}"
  when: inventory_hostname == play_hosts[0]
  register: repl

- name: Ensure replicaset has reached a converged state
  community.mongodb.mongodb_status:
    replica_set: "{{ replica_set_name }}"
    poll: 10
    interval: 10
  when: repl.changed == True

- name: create mongodump backup dir
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  when: inventory_hostname == play_hosts[0]

- name: Add cron.d entry for daily mongodump for backup purposes
  cron:
    name: "cron.d job to create daily backup of mongo databases"
    minute: '00'
    hour: '5'
    weekday: '*'
    user: root
    job: "mongodump -o {{ backup_dir }} --host '{{ replica_set_name }}/localhost:{{ port }}' -u 'admin' -p '{{ vars['mongodb_admin_password_'+dtap] }}' --authenticationDatabase 'admin' --gzip ; tar -zvcf {{ backup_dir }}/mongodump.tar.gz {{ backup_dir }}/*/ --remove-files"
    cron_file: "mongodump_daily"
  when: inventory_hostname == play_hosts[0]

# ansible-galaxy collection install community.mongodb
- name: Create MongoDB root user siteRootAdmin
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ port }}"
    database: "admin"
    name: "{{ mongodb_admin_user }}"
    password: "{{ vars['mongodb_admin_password_'+dtap] }}"
    roles: "root"
  when: inventory_hostname == play_hosts[0]
...