#!/bin/sh
#Remove temp BIGSdb files from secure tmp folder older than 1 week.
find /temp_bigs/working_tmp/ -name '*BIGSdb_*' -type f -mmin +30240 -exec rm -f {} \; 2>/dev/null

#Remove .jnlp files from web tree older than 1 day
find /temp_bigs/results_tmp -name '*.jnlp' -type f -mmin +1440 -exec rm -f {} \; 2>/dev/null

#Remove other tmp files from web tree older than 1 week
find /temp_bigs/results_tmp -type f -mmin +30240 -exec rm -f {} \; 2>/dev/null