import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal, Optional

PYTHONPATH = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(PYTHONPATH))

from bioit_mongodb_scripts.config import COREQC_CONFIG
from bioit_mongodb_scripts.model.json_model import JsonReportDict
from bioit_mongodb_scripts.util.mongo_initialisation import MongoInitialisation
from bioit_mongodb_scripts.util.python_utility_functions import get_mongodb_config_data, load_config


class CheckCoreQCMetrics:
    """
    This class contains the function that checks the core quality metrics.
    """
    def __init__(self, technical_id: str, json_report: JsonReportDict, species: str, reportdirectorypath: Path,
                 sample_coreqc_metrics: dict[str, Any], mongo_config_data: dict[str, Any] = None) -> None:
        """
        Initialises this class.
        :param technical_id: sample id/ isolates id
        :param json_report: json dict containing all results which are found under the 'results' key
        :param species: commonly used bioit species name: either genus or specific like stec
        :param reportdirectorypath: absolute path to where the directory containing all files required for html are 
            stored (only required for new_isolate)
        :param sample_coreqc_metrics: The core qc metrics for this specific sample, generated by get_coreqc_metrics.py
        :param mongo_config_data: Use provided mongo_config_data, else get mongo_config_data from file
        :return: None
        """
        self._technical_id = technical_id
        self._json_report = json_report
        self._species = species
        self._reportdirectorypath = reportdirectorypath
        self._sample_coreqc_metrics = sample_coreqc_metrics
        self._mongo_config_data = mongo_config_data if mongo_config_data else get_mongodb_config_data()
        
        # Add class variables
        self._coreqc_config = load_config(COREQC_CONFIG)
        self._rejection_reasons = {}
        self._good_sample_quality = True

    def check_coreqc_metrics(self) -> bool:
        """
        This function checks the core quality metrics. If any failure threshold is surpassed, then the isolate is added
        to the isolates_rejected_coreqc collection and the script is stopped.
        If no failure threshold is surpassed, but any warning threshold is, then the function returns False.
        If no failure or warning thresholds are exceeded, then the function returns True.
        The core quality metrics used here, and found in the corresponding COREQC_CONFIG originate from the
        D8.1_HERA_BE_WGS_Updated_quality_guidelines_report_29NOV2024 document that can be found in the HERA folder.
        :return: Whether the input document is of good quality according to the core quality metrics (good quality =
        does not surpass any warning threshold)
        """
        for metric, metric_info in self._sample_coreqc_metrics.items():
            self._evaluate_core_qc_metric(metric_info, metric)

        if len(self._rejection_reasons) > 0:
            self._insert_into_rejected_isolates_collection(self._sample_coreqc_metrics)

        return self._good_sample_quality

    def _evaluate_core_qc_metric(self, metric_info: dict[str, Any], core_qc_metric: str) -> None:
        """
        Evaluates a core qc metric.
        :param metric_info: the current metric's info
        :param core_qc_metric: the current core qc metric's name in the config.
        :return: None
        """
        qc_value = self.__get_qcvalue_for_metric(metric_info)
        self.__process_thresholds(metric_info, qc_value, core_qc_metric)
        
    def __get_qcvalue_for_metric(self, metric_info: dict[str, Any]) -> float:
        """
        Gets the quality control value as a float from the json_report. Replaces part of fields where necessary and
        strips any non-float characters where necessary. Also takes the average if necessary.
        :param metric_info: the current metric's info
        :return: qc_value as float
        """
        if metric_info.get('field'):
            field = metric_info['field']
            if metric_info.get('field_to_replace'):
                for key2, value in metric_info['field_to_replace'].items():
                    field = field.replace(key2, self._json_report[value])
            if not metric_info.get('value_format_to_strip'):
                qc_value = float(self._json_report[metric_info['category']][field])
            else:
                qc_value = float(
                    self._json_report[metric_info['category']][field].rstrip(metric_info['value_format_to_strip']))
        else:  # metric_info.get('fields'):
            qc_value = sum(
                float(self._json_report[metric_info['category']][field]) for field in metric_info['fields']) / len(
                metric_info['fields'])
        return qc_value

    def __process_thresholds(self, metric_info: dict[str, Any], qc_value: float, core_qc_metric: str) -> None:
        """
        Evaluates a given qc_value against the failure and warning thresholds for the current core quality metric.
        If the failure threshold is exceeded, then a reason is added to the rejection_reasons.
        If the warning threshold is exceeded, then the good_sample_quality is set to false.
        :param metric_info: the current metric's info
        :param qc_value: the current metric's value in the json_report that needs to be evaluated against the thresholds.
        :param core_qc_metric: the current core qc metric's name in the config.
        :return: None
        """
        if self.___evaluate_threshold(metric_info, qc_value, 'threshold_fail'):
            qc_value_formatted, threshold_formatted = self.___format_values(metric_info, qc_value, 'threshold_fail')
            self._rejection_reasons[core_qc_metric] = {
                'value': qc_value,
                'reason': f"{metric_info['parameter_name']} (={qc_value_formatted}) "
                          f"{metric_info['threshold_direction']} than allowed limit (={threshold_formatted})."
            }
        elif self.___evaluate_threshold(metric_info, qc_value, 'threshold_warn'):
            self._good_sample_quality = False

    @staticmethod
    def ___evaluate_threshold(metric_info: dict[str, Any], qc_value: float,
                              threshold: Literal['threshold_fail', 'threshold_warn']) -> bool:
        """
        Evaluates whether the QC value exceeds the given threshold based on threshold direction.
        :param metric_info: the current metric's info
        :param qc_value: the current metric's value in the json_report that needs to be evaluated against the thresholds.
        :param threshold: the current threshold; threshold_fail or threshold_warn
        :return: Bool, True if threshold exceeded, False if not
        """
        if metric_info['threshold_direction'] == 'higher':
            return float(qc_value) > metric_info[threshold]
        else:  # 'lower'
            return float(qc_value) < metric_info[threshold]

    @staticmethod
    def ___format_values(metric_info: dict[str, Any], qc_value: float,
                         threshold: Literal['threshold_fail', 'threshold_warn']) -> (str, str):
        """
        Formats QC value and threshold with unit if applicable.
        :param metric_info: the current metric's info
        :param qc_value: the current metric's value in the json_report that needs to be evaluated against the thresholds.
        :param threshold: the current threshold; threshold_fail or threshold_warn
        :return: the formatted qc_value & threshold value
        """
        if metric_info.get('value_format_to_strip'):
            unit = metric_info['value_format_to_strip']
            return f"{qc_value}{unit}", f"{metric_info[threshold]}{unit}"
        else:
            return qc_value, metric_info[threshold]

    def _insert_into_rejected_isolates_collection(self, sample_coreqc_metrics: dict[str, dict[str, Any]]) -> None:
        """"
        Inserts an isolate into the rejected isolates collection and includes the reasons for rejection and all quality
        sections.
        :param sample_coreqc_metrics: The current pathogen/sample's coreqc metrics.
        :return: None
        """
        # Open collections
        self._mongoinit = MongoInitialisation(self._species, mongo_config_data=self._mongo_config_data,
                                              selected_connection_string='CONNECTION_STRING_AZURE')
        isolates_rejected_coreqc_collection = self._mongoinit.initialise_isolates_rejected_coreqc_collection()

        # Logic to handle previously rejected versions of the same sample
        previous_rejected_sample_version: Optional[dict[str, Any]] = isolates_rejected_coreqc_collection.find_one(
            {'_id': self._technical_id})
        if previous_rejected_sample_version:
            previous_rejected_sample_version['isolates_id'] = self._technical_id
            previous_rejected_sample_version.pop('_id')
            isolates_rejected_coreqc_collection.insert_one(previous_rejected_sample_version)
            isolates_rejected_coreqc_collection.delete_one({'_id': self._technical_id})

        # Prepare the document that is to be inserted into the isolates_rejected_coreqc collection
        document_to_be_inserted = {
            "_id": self._technical_id,
            "report_directory": str(self._reportdirectorypath),
            "rejection_reasons": self._rejection_reasons,
            "creation_date": datetime.now(timezone.utc),
            "insertion_type": 'automatic'}
        # Quality control metrics are spread in 3 sections: quast, quality_checks and preprocess. We decided to
        # keep track of all quality sections for potential post hoc analyses.
        quality_sections = set(metric_info['category'] for metric_info in sample_coreqc_metrics.values())
        for quality_section in quality_sections:
            document_to_be_inserted[quality_section] = self._json_report[quality_section]

        isolates_rejected_coreqc_collection.insert_one(document_to_be_inserted)
        logging.info(f"Sample {self._technical_id} failed one or more core QC checks. It was added to the "
                     f"isolates_rejected_coreqc collection.")
        # exit gracefully
        sys.exit()
