-- migrate:up
ALTER TABLE isolates ADD COLUMN sample_id text;

ALTER TABLE isolates
    ADD COLUMN isolation_date date,
    ADD COLUMN year_of_isolation smallint,
    ADD COLUMN month_of_isolation smallint,
    ADD COLUMN day_of_isolation smallint,
    ADD COLUMN human_sample bool,
    ADD COLUMN specimen text,
    ADD COLUMN patient_id text,
    ADD COLUMN patient_birth_date date,
    ADD COLUMN patient_age smallint,
    ADD COLUMN patient_age_group text,
    ADD COLUMN patient_sex text,
    ADD COLUMN patient_zip text,
    ADD COLUMN province text,
    ADD COLUMN region text,
    ADD COLUMN latitude double precision,
    ADD COLUMN longitude double precision,
    ADD COLUMN hospitalisation text,
    ADD COLUMN recently_stayed_abroad text,
    ADD COLUMN country_1 text,
    ADD COLUMN country_2 text,
    ADD COLUMN serogroup_pheno text,
    ADD COLUMN mic_azm text,
    ADD COLUMN mic_azm_1 text,
    ADD COLUMN mic_cox text,
    ADD COLUMN mic_cox_1 text,
    ADD COLUMN mic_chl text,
    ADD COLUMN mic_chl_1 text,
    ADD COLUMN mic_cip text,
    ADD COLUMN mic_cip_1 text,
    ADD COLUMN mic_pen text,
    ADD COLUMN mic_pen_1 text,
    ADD COLUMN mic_rif text,
    ADD COLUMN mic_rif_1 text,
    ADD COLUMN clinical_info text,
    ADD COLUMN evolution text,
    ADD COLUMN case_type text;

-- migrate:down

ALTER TABLE isolates DROP COLUMN sample_id;

ALTER TABLE isolates
    DROP COLUMN isolation_date,
    DROP COLUMN year_of_isolation,
    DROP COLUMN month_of_isolation,
    DROP COLUMN day_of_isolation,
    DROP COLUMN human_sample,
    DROP COLUMN specimen,
    DROP COLUMN patient_id,
    DROP COLUMN patient_birth_date,
    DROP COLUMN patient_age,
    DROP COLUMN patient_age_group,
    DROP COLUMN patient_sex,
    DROP COLUMN patient_zip,
    DROP COLUMN province,
    DROP COLUMN region,
    DROP COLUMN latitude,
    DROP COLUMN longitude,
    DROP COLUMN hospitalisation,
    DROP COLUMN recently_stayed_abroad,
    DROP COLUMN country_1,
    DROP COLUMN country_2,
    DROP COLUMN serogroup_pheno,
    DROP COLUMN mic_azm,
    DROP COLUMN mic_azm_1,
    DROP COLUMN mic_cox,
    DROP COLUMN mic_cox_1,
    DROP COLUMN mic_chl,
    DROP COLUMN mic_chl_1,
    DROP COLUMN mic_cip,
    DROP COLUMN mic_cip_1,
    DROP COLUMN mic_pen,
    DROP COLUMN mic_pen_1,
    DROP COLUMN mic_rif,
    DROP COLUMN mic_rif_1,
    DROP COLUMN clinical_info,
    DROP COLUMN evolution,
    DROP COLUMN case_type;