
-- migrate:up
ALTER TABLE isolates
        ADD COLUMN template text,
        ADD COLUMN client_name text,
        ADD COLUMN client_zip text,
        ADD COLUMN sample_client_reference text,
        ADD COLUMN origine text,
        ADD COLUMN perinatal_info text,
        ADD COLUMN related_disease text,
        ADD COLUMN mode_of_transmission text,
        ADD COLUMN identification text,
        ADD COLUMN serotype text,
        ADD COLUMN antibiotic_therapy text,
        ADD COLUMN antibiotic text,
        ADD COLUMN outcome text,
        ADD COLUMN link text,
        ADD COLUMN serovar_final text,
        ADD COLUMN aggl_serogroup text,
        ADD COLUMN mlva_profile text,
        ADD COLUMN mic_amo double precision,
        ADD COLUMN mic_amo_1 text,
        ADD COLUMN mic_amp double precision,
        ADD COLUMN mic_amp_1 text,
        ADD COLUMN mic_caz double precision,
        ADD COLUMN mic_caz_1 text,
        ADD COLUMN mic_col double precision,
        ADD COLUMN mic_col_1 text,
        ADD COLUMN mic_etp double precision,
        ADD COLUMN mic_etp_1 text,
        ADD COLUMN mic_gmn double precision,
        ADD COLUMN mic_gmn_1 text,
        ADD COLUMN mic_mem double precision,
        ADD COLUMN mic_mem_1 text,
        ADD COLUMN mic_smx_1 text,
        ADD COLUMN mic_tgc double precision,
        ADD COLUMN mic_tmp double precision,
        ADD COLUMN mic_ery double precision,
        ADD COLUMN mic_ery_1 text,
        ADD COLUMN mic_str double precision,
        ADD COLUMN mic_str_1 text,
        ADD COLUMN mic_tet double precision,
        ADD COLUMN mic_tet_1 text,
        ADD COLUMN mic_tmpsmx double precision,
        ADD COLUMN mic_tmpsmx_1 text,
        ADD COLUMN mic_van double precision,
        ADD COLUMN mic_van_1 text,
        ADD COLUMN mic_resistances text,
        ADD COLUMN indication_for_sequencing text,
        ADD COLUMN keep_for_clustering text,
        ADD COLUMN comment text,
        ADD COLUMN label text,
        ADD COLUMN country_reporting_alert text;

ALTER TABLE isolates
        ALTER COLUMN human_sample TYPE text,
        ALTER COLUMN mic_cox TYPE double precision,
        ALTER COLUMN mic_chl TYPE double precision,
        ALTER COLUMN mic_cip TYPE double precision,
        ALTER COLUMN mic_pen TYPE double precision,
        ALTER COLUMN mic_rif TYPE double precision;

ALTER TABLE isolates
        DROP COLUMN mic_azm_1;

-- migrate:down

ALTER TABLE isolates
        DROP COLUMN template,
        DROP COLUMN client_name,
        DROP COLUMN client_zip,
        DROP COLUMN sample_client_reference,
        DROP COLUMN origine,
        DROP COLUMN perinatal_info,
        DROP COLUMN related_disease,
        DROP COLUMN mode_of_transmission,
        DROP COLUMN identification,
        DROP COLUMN serotype,
        DROP COLUMN antibiotic_therapy,
        DROP COLUMN antibiotic,
        DROP COLUMN outcome,
        DROP COLUMN link,
        DROP COLUMN serovar_final,
        DROP COLUMN aggl_serogroup,
        DROP COLUMN mlva_profile,
        DROP COLUMN mic_amo,
        DROP COLUMN mic_amo_1,
        DROP COLUMN mic_amp,
        DROP COLUMN mic_amp_1,
        DROP COLUMN mic_caz,
        DROP COLUMN mic_caz_1,
        DROP COLUMN mic_col,
        DROP COLUMN mic_col_1,
        DROP COLUMN mic_etp,
        DROP COLUMN mic_etp_1,
        DROP COLUMN mic_gmn,
        DROP COLUMN mic_gmn_1,
        DROP COLUMN mic_mem,
        DROP COLUMN mic_mem_1,
        DROP COLUMN mic_smx_1,
        DROP COLUMN mic_tgc,
        DROP COLUMN mic_tmp,
        DROP COLUMN mic_ery,
        DROP COLUMN mic_ery_1,
        DROP COLUMN mic_str,
        DROP COLUMN mic_str_1,
        DROP COLUMN mic_tet,
        DROP COLUMN mic_tet_1,
        DROP COLUMN mic_tmpsmx,
        DROP COLUMN mic_tmpsmx_1,
        DROP COLUMN mic_van,
        DROP COLUMN mic_van_1,
        DROP COLUMN mic_resistances,
        DROP COLUMN indication_for_sequencing,
        DROP COLUMN keep_for_clustering,
        DROP COLUMN comment,
        DROP COLUMN label,
        DROP COLUMN country_reporting_alert;

ALTER TABLE isolates
        ALTER COLUMN human_sample TYPE bool,
        ALTER COLUMN mic_cox TYPE text,
        ALTER COLUMN mic_chl TYPE text,
        ALTER COLUMN mic_cip TYPE text,
        ALTER COLUMN mic_pen TYPE text,
        ALTER COLUMN mic_rif TYPE text;


ALTER TABLE isolates
        ADD COLUMN mic_azm_1 text;

