-- migrate:up
ALTER TABLE isolates
    DROP COLUMN latitude,
    DROP COLUMN longitude,
    ADD COLUMN symptom_asymptomatic text,
    ADD COLUMN symptom_gastroenteritis text,
    ADD COLUMN symptom_sepsis text,
    ADD COLUMN symptom_urinary_tract_infection text,
    ADD COLUMN symptom_unknown text,
    DROP COLUMN clinical_info,
    ADD COLUMN mic_azm_I text,
    ADD COLUMN mic_smx real,
    ADD COLUMN mic_tgc_I text,
    ADD COLUMN mic_tmp_I text,
    ALTER COLUMN mic_azm TYPE real USING mic_azm::real,
    RENAME COLUMN mic_cox_1 TO mic_cox_I,
    RENAME COLUMN mic_chl_1 TO mic_chl_I,
    RENAME COLUMN mic_cip_1 TO mic_cip_I,
    RENAME COLUMN mic_pen_1 TO mic_pen_I,
    RENAME COLUMN mic_rif_1 TO mic_rif_I,
    RENAME COLUMN mic_amo_1 TO mic_amo_I,
    RENAME COLUMN mic_amp_1 TO mic_amp_I,
    RENAME COLUMN mic_caz_1 TO mic_caz_I,
    RENAME COLUMN mic_col_1 TO mic_col_I,
    RENAME COLUMN mic_etp_1 TO mic_etp_I,
    RENAME COLUMN mic_gmn_1 TO mic_gmn_I,
    RENAME COLUMN mic_mem_1 TO mic_mem_I,
    RENAME COLUMN mic_smx_1 TO mic_smx_I,
    RENAME COLUMN mic_ery_1 TO mic_ery_I,
    RENAME COLUMN mic_str_1 TO mic_str_I,
    RENAME COLUMN mic_tet_1 TO mic_tet_I,
    RENAME COLUMN mic_tmpsmx_1 TO mic_tmpsmx_I,
    RENAME COLUMN mic_van_1 TO mic_van_I;

-- migrate:down

ALTER TABLE isolates
    ADD COLUMN latitude double precision,
    ADD COLUMN longitude double precision,
    DROP COLUMN symptom_asymptomatic,
    DROP COLUMN symptom_gastroenteritis,
    DROP COLUMN symptom_sepsis,
    DROP COLUMN symptom_urinary_tract_infection,
    DROP COLUMN symptom_unknown,
    ADD COLUMN clinical_info text,
    DROP COLUMN mic_azm_I,
    DROP COLUMN mic_smx,
    DROP COLUMN mic_tgc_I,
    DROP COLUMN mic_tmp_I,
    ALTER COLUMN mic_azm TYPE text USING mic_azm::text,
    RENAME COLUMN mic_cox_I TO mic_cox_1,
    RENAME COLUMN mic_chl_I	TO mic_chl_1,
    RENAME COLUMN mic_cip_I TO mic_cip_1,
    RENAME COLUMN mic_pen_I TO mic_pen_1,
    RENAME COLUMN mic_rif_I TO mic_rif_1,
    RENAME COLUMN mic_amo_I TO mic_amo_1,
    RENAME COLUMN mic_amp_I TO mic_amp_1,
    RENAME COLUMN mic_caz_I TO mic_caz_1,
    RENAME COLUMN mic_col_I TO mic_col_1,
    RENAME COLUMN mic_etp_I TO mic_etp_1,
    RENAME COLUMN mic_gmn_I TO mic_gmn_1,
    RENAME COLUMN mic_mem_I TO mic_mem_1,
    RENAME COLUMN mic_smx_I TO mic_smx_1,
    RENAME COLUMN mic_ery_I TO mic_ery_1,
    RENAME COLUMN mic_str_I TO mic_str_1,
    RENAME COLUMN mic_tet_I TO mic_tet_1,
    RENAME COLUMN mic_tmpsmx_I TO mic_tmpsmx_1,
    RENAME COLUMN mic_van_I TO mic_van_1;