-- migrate:up
ALTER TABLE isolates
    ADD COLUMN client_region text,
    ADD COLUMN client_code text,
    ADD COLUMN reception_date date,
    ADD COLUMN Flu_type text,
    ADD COLUMN FluA_subtypePCR text,
    ADD COLUMN FluB_lineagePCR text,
    ADD COLUMN sampling_week smallint,
    ADD COLUMN sampling_date date,
    ADD COLUMN sampling_year smallint,
    ADD COLUMN sampling_month smallint,
    ADD COLUMN sampling_day smallint,
    ADD COLUMN admission_date date,
    ADD COLUMN admission_year smallint,
    ADD COLUMN admission_month smallint,
    ADD COLUMN admission_day smallint,
    ADD COLUMN symptoms_start_date date,
    ADD COLUMN antiviral_treatment text,
    ADD COLUMN antiviral_treatment_type text,
    ADD COLUMN antiviral_treatment_date date,
    ADD COLUMN antiviral_treatment_year smallint,
    ADD COLUMN antiviral_treatment_month smallint,
    ADD COLUMN antiviral_treatment_day smallint,
    ADD COLUMN seasonal_vaccination text,
    ADD COLUMN vaccination_date date,
    ADD COLUMN vaccination_year smallint,
    ADD COLUMN vaccination_month smallint,
    ADD COLUMN vaccination_day smallint,
    ADD COLUMN R_Oseltamivir text,
    ADD COLUMN EC50_OS float,
    ADD COLUMN R_Zanamivir text,
    ADD COLUMN EC50_ZA float,
    ADD COLUMN GISAID_NGS text,
    ADD COLUMN official_name text;

-- migrate:down
ALTER TABLE isolates
    DROP COLUMN client_region,
    DROP COLUMN client_code,
    DROP COLUMN reception_date,
    DROP COLUMN Flu_type,
    DROP COLUMN FluA_subtypePCR,
    DROP COLUMN FluB_lineagePCR,
    DROP COLUMN sampling_week,
    DROP COLUMN sampling_date,
    DROP COLUMN sampling_year,
    DROP COLUMN sampling_month,
    DROP COLUMN sampling_day,
    DROP COLUMN admission_date,
    DROP COLUMN admission_year,
    DROP COLUMN admission_month,
    DROP COLUMN admission_day,
    DROP COLUMN symptoms_start_date,
    DROP COLUMN antiviral_treatment,
    DROP COLUMN antiviral_treatment_type,
    DROP COLUMN antiviral_treatment_date,
    DROP COLUMN antiviral_treatment_year,
    DROP COLUMN antiviral_treatment_month,
    DROP COLUMN antiviral_treatment_day,
    DROP COLUMN seasonal_vaccination,
    DROP COLUMN vaccination_date,
    DROP COLUMN vaccination_year,
    DROP COLUMN vaccination_month,
    DROP COLUMN vaccination_day,
    DROP COLUMN R_Oseltamivir,
    DROP COLUMN EC50_OS,
    DROP COLUMN R_Zanamivir,
    DROP COLUMN EC50_ZA,
    DROP COLUMN GISAID_NGS,
    DROP COLUMN official_name ;