-- migrate:up
ALTER TABLE isolates
    -- Remove shared fields but not shared among all
    DROP COLUMN case_type,
    DROP COLUMN outcome,
    -- Remove salmonella specific and add in salmonella specific migration
    DROP COLUMN link_human_to_human_transmission,
    DROP COLUMN link_isolated_case,
    DROP COLUMN link_foodborne_transmission,
    DROP COLUMN link_not_applicable,
    DROP COLUMN link_other,
    DROP COLUMN link_unknown,
    DROP COLUMN serovar_final,
    DROP COLUMN serovar_luminex,
    DROP COLUMN serovar_agglutination,
    DROP COLUMN serovar_agglutination_formula,
    DROP COLUMN malditof_identification,
    DROP COLUMN symptom_asymptomatic,
    DROP COLUMN symptom_gastroenteritis,
    DROP COLUMN symptom_sepsis,
    DROP COLUMN symptom_urinary_tract_infection,
    DROP COLUMN symptom_unknown,
    DROP COLUMN antibiotic_therapy,
    DROP COLUMN antibiotic,
    DROP COLUMN mlva_profile,
    -- Remove listeria specific and add in listeria specific migration
    DROP COLUMN perinatal_info,
    DROP COLUMN related_disease,
    DROP COLUMN mode_of_transmission,
    DROP COLUMN identification,
    DROP COLUMN serotype,
    DROP COLUMN serogroup_pheno,
    -- Remove neisseria specific and add in neisseria specific migration
    DROP COLUMN evolution,
    -- Remove influenza specific and add in influenza specific migration
    DROP COLUMN client_region,
    DROP COLUMN client_code,
    DROP COLUMN reception_date,
    DROP COLUMN Flu_type,
    DROP COLUMN FluA_subtypePCR,
    DROP COLUMN FluB_lineagePCR,
    DROP COLUMN sampling_week,
    DROP COLUMN sampling_date,
    DROP COLUMN sampling_year,
    DROP COLUMN sampling_month,
    DROP COLUMN sampling_day,
    DROP COLUMN admission_date,
    DROP COLUMN admission_year,
    DROP COLUMN admission_month,
    DROP COLUMN admission_day,
    DROP COLUMN symptoms_start_date,
    DROP COLUMN antiviral_treatment,
    DROP COLUMN antiviral_treatment_type,
    DROP COLUMN antiviral_treatment_date,
    DROP COLUMN antiviral_treatment_year,
    DROP COLUMN antiviral_treatment_month,
    DROP COLUMN antiviral_treatment_day,
    DROP COLUMN seasonal_vaccination,
    DROP COLUMN vaccination_date,
    DROP COLUMN vaccination_year,
    DROP COLUMN vaccination_month,
    DROP COLUMN vaccination_day,
    DROP COLUMN R_Oseltamivir,
    DROP COLUMN EC50_OS,
    DROP COLUMN R_Zanamivir,
    DROP COLUMN EC50_ZA,
    DROP COLUMN GISAID_NGS,
    DROP COLUMN official_name,
    -- Remove MICs
    DROP COLUMN mic_amo,
    DROP COLUMN mic_amo_I,
    DROP COLUMN mic_amp,
    DROP COLUMN mic_amp_I,
    DROP COLUMN mic_azm,
    DROP COLUMN mic_azm_I,
    DROP COLUMN mic_caz,
    DROP COLUMN mic_caz_I,
    DROP COLUMN mic_chl,
    DROP COLUMN mic_chl_I,
    DROP COLUMN mic_cip,
    DROP COLUMN mic_cip_I,
    DROP COLUMN mic_col,
    DROP COLUMN mic_col_I,
    DROP COLUMN mic_cox,
    DROP COLUMN mic_cox_I,
    DROP COLUMN mic_ery,
    DROP COLUMN mic_ery_I,
    DROP COLUMN mic_etp,
    DROP COLUMN mic_etp_I,
    DROP COLUMN mic_gmn,
    DROP COLUMN mic_gmn_I,
    DROP COLUMN mic_mem,
    DROP COLUMN mic_mem_I,
    DROP COLUMN mic_pen,
    DROP COLUMN mic_pen_I,
    DROP COLUMN mic_rif,
    DROP COLUMN mic_rif_I,
    DROP COLUMN mic_smx,
    DROP COLUMN mic_smx_I,
    DROP COLUMN mic_str,
    DROP COLUMN mic_str_I,
    DROP COLUMN mic_tet,
    DROP COLUMN mic_tet_I,
    DROP COLUMN mic_tgc,
    DROP COLUMN mic_tgc_I,
    DROP COLUMN mic_tmp,
    DROP COLUMN mic_tmp_I,
    DROP COLUMN mic_tmpsmx,
    DROP COLUMN mic_tmpsmx_I,
    DROP COLUMN mic_van,
    DROP COLUMN mic_van_I,
    DROP COLUMN mic_resistances;

-- migrate:down
ALTER TABLE isolates
    ADD COLUMN case_type text,
    ADD COLUMN outcome text,
    ADD COLUMN link_human_to_human_transmission text,
    ADD COLUMN link_isolated_case text,
    ADD COLUMN link_foodborne_transmission text,
    ADD COLUMN link_not_applicable text,
    ADD COLUMN link_other text,
    ADD COLUMN link_unknown text,
    ADD COLUMN serovar_final text,
    ADD COLUMN serovar_luminex text,
    ADD COLUMN serovar_agglutination text,
    ADD COLUMN serovar_agglutination_formula text,
    ADD COLUMN malditof_identification text,
    ADD COLUMN symptom_asymptomatic text,
    ADD COLUMN symptom_gastroenteritis text,
    ADD COLUMN symptom_sepsis text,
    ADD COLUMN symptom_urinary_tract_infection text,
    ADD COLUMN symptom_unknown text,
    ADD COLUMN mlva_profile text,
    ADD COLUMN antibiotic_therapy text,
    ADD COLUMN antibiotic text,
    ADD COLUMN perinatal_info text,
    ADD COLUMN related_disease text,
    ADD COLUMN mode_of_transmission text,
    ADD COLUMN identification text,
    ADD COLUMN serotype text,
    ADD COLUMN serogroup_pheno text,
    ADD COLUMN evolution text,
    ADD COLUMN client_region text,
    ADD COLUMN client_code text,
    ADD COLUMN reception_date date,
    ADD COLUMN Flu_type text,
    ADD COLUMN FluA_subtypePCR text,
    ADD COLUMN FluB_lineagePCR text,
    ADD COLUMN sampling_week smallint,
    ADD COLUMN sampling_date date,
    ADD COLUMN sampling_year smallint,
    ADD COLUMN sampling_month smallint,
    ADD COLUMN sampling_day smallint,
    ADD COLUMN admission_date date,
    ADD COLUMN admission_year smallint,
    ADD COLUMN admission_month smallint,
    ADD COLUMN admission_day smallint,
    ADD COLUMN symptoms_start_date date,
    ADD COLUMN antiviral_treatment text,
    ADD COLUMN antiviral_treatment_type text,
    ADD COLUMN antiviral_treatment_date date,
    ADD COLUMN antiviral_treatment_year smallint,
    ADD COLUMN antiviral_treatment_month smallint,
    ADD COLUMN antiviral_treatment_day smallint,
    ADD COLUMN seasonal_vaccination text,
    ADD COLUMN vaccination_date date,
    ADD COLUMN vaccination_year smallint,
    ADD COLUMN vaccination_month smallint,
    ADD COLUMN vaccination_day smallint,
    ADD COLUMN R_Oseltamivir text,
    ADD COLUMN EC50_OS float,
    ADD COLUMN R_Zanamivir text,
    ADD COLUMN EC50_ZA float,
    ADD COLUMN GISAID_NGS text,
    ADD COLUMN official_name text,
    ADD COLUMN mic_amo real,
    ADD COLUMN mic_amo_I text,
    ADD COLUMN mic_amp real,
    ADD COLUMN mic_amp_I text,
    ADD COLUMN mic_azm real,
    ADD COLUMN mic_azm_I text,
    ADD COLUMN mic_caz real,
    ADD COLUMN mic_caz_I text,
    ADD COLUMN mic_chl real,
    ADD COLUMN mic_chl_I text,
    ADD COLUMN mic_cip real,
    ADD COLUMN mic_cip_I text,
    ADD COLUMN mic_col real,
    ADD COLUMN mic_col_I text,
    ADD COLUMN mic_cox real,
    ADD COLUMN mic_cox_I text,
    ADD COLUMN mic_ery real,
    ADD COLUMN mic_ery_I text,
    ADD COLUMN mic_etp real,
    ADD COLUMN mic_etp_I text,
    ADD COLUMN mic_gmn real,
    ADD COLUMN mic_gmn_I text,
    ADD COLUMN mic_mem real,
    ADD COLUMN mic_mem_I text,
    ADD COLUMN mic_pen real,
    ADD COLUMN mic_pen_I text,
    ADD COLUMN mic_rif real,
    ADD COLUMN mic_rif_I text,
    ADD COLUMN mic_smx real,
    ADD COLUMN mic_smx_I text,
    ADD COLUMN mic_str real,
    ADD COLUMN mic_str_I text,
    ADD COLUMN mic_tet real,
    ADD COLUMN mic_tet_I text,
    ADD COLUMN mic_tgc real,
    ADD COLUMN mic_tgc_I text,
    ADD COLUMN mic_tmp real,
    ADD COLUMN mic_tmp_I text,
    ADD COLUMN mic_tmpsmx real,
    ADD COLUMN mic_tmpsmx_I text,
    ADD COLUMN mic_van real,
    ADD COLUMN mic_van_I text,
    ADD COLUMN mic_resistances text;