-- migrate:up
UPDATE eav_fields SET category='Mykrobe' WHERE category='Genotyphi';
update schemes SET name='Mykrobe' WHERE name='Genotyphi';
DELETE FROM scheme_members WHERE locus='GENOTYPHI_ESBLS';
DELETE FROM loci WHERE id='GENOTYPHI_ESBLS';
DELETE FROM scheme_members WHERE locus='GENOTYPHI_AMINOGLYCOSIDES';
DELETE FROM loci WHERE id='GENOTYPHI_AMINOGLYCOSIDES';
DELETE FROM scheme_members WHERE locus='GENOTYPHI_BETA-LACTAMASES';
DELETE FROM loci WHERE id='GENOTYPHI_BETA-LACTAMASES';
DELETE FROM scheme_members WHERE locus='GENOTYPHI_MACROLIDES';
DELETE FROM loci WHERE id='GENOTYPHI_MACROLIDES';
DELETE FROM scheme_members WHERE locus='GENOTYPHI_PHENICOLS';
DELETE FROM loci WHERE id='GENOTYPHI_PHENICOLS';
DELETE FROM scheme_members WHERE locus='GENOTYPHI_QUINOLONES';
DELETE FROM loci WHERE id='GENOTYPHI_QUINOLONES';
UPDATE loci SET id='MYKROBE_INCFIAHI1' WHERE id='GENOTYPHI_INCFIAHI1';
UPDATE loci SET id='MYKROBE_INCHI1A' WHERE id='GENOTYPHI_INCHI1A';
UPDATE loci SET id='MYKROBE_INCHI1BR27' WHERE id='GENOTYPHI_INCHI1BR27';
UPDATE loci SET id='MYKROBE_INCY' WHERE id='GENOTYPHI_INCY';
UPDATE loci SET id='MYKROBE_AZITHROMYCIN' WHERE id='GENOTYPHI_AZITHROMYCIN';
UPDATE loci SET id='MYKROBE_PST' WHERE id='GENOTYPHI_PST';
UPDATE loci SET id='MYKROBE_SULFONAMIDES' WHERE id='GENOTYPHI_SULFONAMIDES';
UPDATE loci SET id='MYKROBE_TETRACYCLINE' WHERE id='GENOTYPHI_TETRACYCLINES';
UPDATE loci SET id='MYKROBE_TRIMETHOPRIM' WHERE id='GENOTYPHI_TRIMETHOPRIMS';
UPDATE loci SET id='MYKROBE_Z66' WHERE id='GENOTYPHI_Z66';
DELETE FROM eav_fields WHERE field='ESBLs_susceptibility';
DELETE FROM eav_fields WHERE field='aminoglycosides_susceptibility';
DELETE FROM eav_fields WHERE field='beta-lactamases_susceptibility';
DELETE FROM eav_fields WHERE field='macrolides_susceptibility';
DELETE FROM eav_fields WHERE field='phenicols_susceptibility';
DELETE FROM eav_fields WHERE field='quinolones_susceptibility';
UPDATE eav_fields SET field='tetracycline_susceptibility' WHERE field='tetracyclines_susceptibility';
UPDATE eav_fields SET field='trimethoprim_susceptibility' WHERE field='trimethoprims_susceptibility';

-- migrate:down
UPDATE eav_fields SET category='Genotyphi' WHERE category='Mykrobe';
update schemes SET name='Genotyphi' WHERE name='Mykrobe';
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_ESBLS','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_ESBLS', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_ESBLS&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_AMINOGLYCOSIDES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_AMINOGLYCOSIDES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_AMINOGLYCOSIDES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_BETA-LACTAMASES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_BETA-LACTAMASES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_BETA-LACTAMASES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_MACROLIDES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_MACROLIDES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_MACROLIDES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_PHENICOLS','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_PHENICOLS', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_PHENICOLS&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_QUINOLONES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_QUINOLONES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_QUINOLONES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES(10, 'GENOTYPHI_ESBLS', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES(10, 'GENOTYPHI_AMINOGLYCOSIDES', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES(10, 'GENOTYPHI_BETA-LACTAMASES', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES(10, 'GENOTYPHI_MACROLIDES', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES(10, 'GENOTYPHI_PHENICOLS', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES(10, 'GENOTYPHI_QUINOLONES', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
UPDATE loci SET id='GENOTYPHI_INCFIAHI1' WHERE id='MYKROBE_INCFIAHI1';
UPDATE loci SET id='GENOTYPHI_INCHI1A' WHERE id='MYKROBE_INCHI1A';
UPDATE loci SET id='GENOTYPHI_INCHI1BR27' WHERE id='MYKROBE_INCHI1BR27';
UPDATE loci SET id='GENOTYPHI_INCY' WHERE id='MYKROBE_INCY';
UPDATE loci SET id='GENOTYPHI_AZITHROMYCIN' WHERE id='MYKROBE_AZITHROMYCIN';
UPDATE loci SET id='GENOTYPHI_PST' WHERE id='MYKROBE_PST';
UPDATE loci SET id='GENOTYPHI_SULFONAMIDES' WHERE id='MYKROBE_SULFONAMIDES';
UPDATE loci SET id='GENOTYPHI_TETRACYCLINES' WHERE id='MYKROBE_TETRACYCLINE';
UPDATE loci SET id='GENOTYPHI_TRIMETHOPRIMS' WHERE id='MYKROBE_TRIMETHOPRIM';
UPDATE loci SET id='GENOTYPHI_Z66' WHERE id='MYKROBE_Z66';
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('ESBLs_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1) ON CONFLICT DO NOTHING;
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('aminoglycosides_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1) ON CONFLICT DO NOTHING;
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('beta-lactamases_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1) ON CONFLICT DO NOTHING;
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('macrolides_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1) ON CONFLICT DO NOTHING;
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('phenicols_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1) ON CONFLICT DO NOTHING;
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('quinolones_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1) ON CONFLICT DO NOTHING;
UPDATE eav_fields SET field='tetracyclines_susceptibility' WHERE field='tetracycline_susceptibility';
UPDATE eav_fields SET field='trimethoprims_susceptibility' WHERE field='trimethoprim_susceptibility';