-- migrate:up
ALTER TABLE isolates
    ADD COLUMN author_group text,
    ADD COLUMN author text,
    ADD COLUMN coauthor text,
    ADD COLUMN patient_id_system text,
    ADD COLUMN patient_death_indicator text,
    ADD COLUMN patient_first_names text,
    ADD COLUMN patient_initials text,
    ADD COLUMN patient_last_names text,
    ADD COLUMN original_sample_id_status text,
    ADD COLUMN original_sample_id text,
    ADD COLUMN requester_hp_identification_nb_system text,
    ADD COLUMN requester_hp_identification_nb text,
    ADD COLUMN requester_hp_speciality text,
    ADD COLUMN requester_ho_identification_nb_system text,
    ADD COLUMN requester_ho_identification_nb text,
    ADD COLUMN performer_hp_identification_nb_system text,
    ADD COLUMN performer_hp_identification_nb text,
    ADD COLUMN performer_ho_identification_nb_system text,
    ADD COLUMN performer_ho_identification_nb text,
    ADD COLUMN specimen_material text,
    ADD COLUMN specimen_microorganism text,
    ADD COLUMN specimen_collection_datetime timestamp,
    ADD COLUMN specimen_received_datetime timestamp,
    ADD COLUMN requester_HP_contact_information text,
    ADD COLUMN hosp_fl text,
    ADD COLUMN syndrome text,
    ADD COLUMN department text,
    ADD COLUMN evolution text,
    ADD COLUMN amp_rsi text,
    ADD COLUMN amp_mic text,
    ADD COLUMN van_rsi text,
    ADD COLUMN van_mic text,
    ADD COLUMN tpl_rsi text,
    ADD COLUMN tpl_mic text,
    ADD COLUMN lin_rsi text,
    ADD COLUMN lin_mic text,
    ADD COLUMN tig_rsi text,
    ADD COLUMN tig_mic text,
    ADD COLUMN genh_rsi text,
    ADD COLUMN genh_mic text,
    ADD COLUMN str_rsi text,
    ADD COLUMN str_mic text,
    ADD COLUMN dap_rsi text,
    ADD COLUMN dap_mic text,
    ADD COLUMN era_rsi text,
    ADD COLUMN era_mic text;

-- migrate:down
ALTER TABLE isolates
    DROP COLUMN author_group,
    DROP COLUMN author,
    DROP COLUMN coauthor,
    DROP COLUMN patient_id_system,
    DROP COLUMN patient_death_indicator,
    DROP COLUMN patient_first_names,
    DROP COLUMN patient_initials,
    DROP COLUMN patient_last_names,
    DROP COLUMN original_sample_id_status,
    DROP COLUMN original_sample_id,
    DROP COLUMN requester_hp_identification_nb_system,
    DROP COLUMN requester_hp_identification_nb,
    DROP COLUMN requester_hp_speciality,
    DROP COLUMN requester_ho_identification_nb_system,
    DROP COLUMN requester_ho_identification_nb,
    DROP COLUMN performer_hp_identification_nb_system,
    DROP COLUMN performer_hp_identification_nb,
    DROP COLUMN performer_ho_identification_nb_system,
    DROP COLUMN performer_ho_identification_nb,
    DROP COLUMN specimen_material,
    DROP COLUMN specimen_microorganism,
    DROP COLUMN specimen_collection_datetime,
    DROP COLUMN specimen_received_datetime,
    DROP COLUMN requester_HP_contact_information,
    DROP COLUMN hosp_fl,
    DROP COLUMN syndrome,
    DROP COLUMN department,
    DROP COLUMN evolution,
    DROP COLUMN amp_rsi,
    DROP COLUMN amp_mic,
    DROP COLUMN van_rsi,
    DROP COLUMN van_mic,
    DROP COLUMN tpl_rsi,
    DROP COLUMN tpl_mic,
    DROP COLUMN lin_rsi,
    DROP COLUMN lin_mic,
    DROP COLUMN tig_rsi,
    DROP COLUMN tig_mic,
    DROP COLUMN genh_rsi,
    DROP COLUMN genh_mic,
    DROP COLUMN str_rsi,
    DROP COLUMN str_mic,
    DROP COLUMN dap_rsi,
    DROP COLUMN dap_mic,
    DROP COLUMN era_rsi,
    DROP COLUMN era_mic;