-- migrate:up
ALTER TABLE isolates
    ADD COLUMN epi_link text,
    ADD COLUMN serovar_final text,
    ADD COLUMN serovar_luminex text,
    ADD COLUMN serovar_agglutination text,
    ADD COLUMN serovar_agglutination_formula text,
    ADD COLUMN malditof_identification text,
    ADD COLUMN symptom_asymptomatic text,
    ADD COLUMN symptom_gastroenteritis text,
    ADD COLUMN symptom_sepsis text,
    ADD COLUMN symptom_urinary_tract_infection text,
    ADD COLUMN symptom_unknown text,
    ADD COLUMN antibiotic_therapy text,
    ADD COLUMN antibiotic text,
    ADD COLUMN mlva_profile text,
    ADD COLUMN mic_amp real,
    ADD COLUMN mic_amp_I text,
    ADD COLUMN mic_azm real,
    ADD COLUMN mic_azm_I text,
    ADD COLUMN mic_cox real,
    ADD COLUMN mic_cox_I text,
    ADD COLUMN mic_caz real,
    ADD COLUMN mic_caz_I text,
    ADD COLUMN mic_chl real,
    ADD COLUMN mic_chl_I text,
    ADD COLUMN mic_cip real,
    ADD COLUMN mic_cip_I text,
    ADD COLUMN mic_col real,
    ADD COLUMN mic_col_I text,
    ADD COLUMN mic_etp real,
    ADD COLUMN mic_etp_I text,
    ADD COLUMN mic_gmn real,
    ADD COLUMN mic_gmn_I text,
    ADD COLUMN mic_mem real,
    ADD COLUMN mic_mem_I text,
    ADD COLUMN mic_smx real,
    ADD COLUMN mic_smx_I text,
    ADD COLUMN mic_tet real,
    ADD COLUMN mic_tet_I text,
    ADD COLUMN mic_tgc real,
    ADD COLUMN mic_tgc_I text,
    ADD COLUMN mic_tmp real,
    ADD COLUMN mic_tmp_I text;

-- migrate:down
ALTER TABLE isolates
    DROP COLUMN epi_link,
    DROP COLUMN serovar_final,
    DROP COLUMN serovar_luminex,
    DROP COLUMN serovar_agglutination,
    DROP COLUMN serovar_agglutination_formula,
    DROP COLUMN malditof_identification,
    DROP COLUMN symptom_asymptomatic,
    DROP COLUMN symptom_gastroenteritis,
    DROP COLUMN symptom_sepsis,
    DROP COLUMN symptom_urinary_tract_infection,
    DROP COLUMN symptom_unknown,
    DROP COLUMN antibiotic_therapy,
    DROP COLUMN antibiotic,
    DROP COLUMN mlva_profile,
    DROP COLUMN mic_amp,
    DROP COLUMN mic_amp_I,
    DROP COLUMN mic_azm,
    DROP COLUMN mic_azm_I,
    DROP COLUMN mic_cox,
    DROP COLUMN mic_cox_I,
    DROP COLUMN mic_caz,
    DROP COLUMN mic_caz_I,
    DROP COLUMN mic_chl,
    DROP COLUMN mic_chl_I,
    DROP COLUMN mic_cip,
    DROP COLUMN mic_cip_I,
    DROP COLUMN mic_col,
    DROP COLUMN mic_col_I,
    DROP COLUMN mic_etp,
    DROP COLUMN mic_etp_I,
    DROP COLUMN mic_gmn,
    DROP COLUMN mic_gmn_I,
    DROP COLUMN mic_mem,
    DROP COLUMN mic_mem_I,
    DROP COLUMN mic_smx,
    DROP COLUMN mic_smx_I,
    DROP COLUMN mic_tet,
    DROP COLUMN mic_tet_I,
    DROP COLUMN mic_tgc,
    DROP COLUMN mic_tgc_I,
    DROP COLUMN mic_tmp,
    DROP COLUMN mic_tmp_I;