---
- name: check if dtap in list
  vars:
    dtaplist:
      - devtest
      - accprod
  fail:
    msg: "unsupported dtap requested, choose from {{ dtaplist }}"
  when: dtap not in dtaplist

- name: Assert if branch given
  fail:
    msg: "'branch' argument required in -e when running playbook"
  when: branch is not defined

- name: Install system packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python3.10-dev
      - python3.10-venv
      - virtualenv
      - uwsgi
      - uwsgi-plugin-python3
      - libpcre3-dev # needed for uwsgi?
      - supervisor
      - git

# configure Nginx
- name: Include bioit.galaxy.nginx/tasks/base.yml
  include_role:
    name: bioit.galaxy.nginx
    tasks_from: base

- name: Generate nginx conf for nrc integration from template
  template:
    src: templates/nrcint_nginx.conf.j2
    dest: /etc/nginx/sites-available/nrcint

- name: Soft link the nrc integration entry
  file:
    src: /etc/nginx/sites-available/nrcint
    dest: /etc/nginx/sites-enabled/nrcint
    state: link

#- name: Include bioit.cerbot/tasks/main.yml
#  include_role:
#    name: bioit.certbot
#    tasks_from: main

- name: check nginx configuration
  command: sudo nginx -t

- name: Get updated files from git repository
  git:
    repo: "https://{{bioit_git_ro_user}}:{{ secret_bioit_git_ro_password }}@{{bioit_git_server}}/bigsdb/bigsdb.git"
    dest: "{{ bioit_bigs_home }}"
    version: "{{ branch }}"
    force: true

- name: Change git cloned repo owner and group
  file:
    path: "{{ bioit_bigs_home }}"
    owner: "{{ uwsgi_user_name }}"
    group: "{{ uwsgi_group }}"
    recurse: yes

- name: Create config directory
  file:
    path: "{{ bioit_bigs_home  }}/bioit_nrc_integration/python/config"
    state: directory
    owner: "{{ uwsgi_user_name }}"
    group: "{{ uwsgi_group }}"
    mode: '775'

- name: Include bioit.galaxy.supervisor/tasks/extra.yml
  include_role:
    name: bioit.galaxy.supervisor
    tasks_from: extra

- name: Generate supervisor conf.d for qclabs from template
  template:
    src: templates/nrcint_supervisord.conf.j2
    dest: /etc/supervisor/conf.d/nrcint.conf

- name: Generate uwsgi config from template
  template:
    src: templates/nrcint.ini.j2
    dest: /etc/uwsgi/apps-available/nrcint.ini

- name: Soft link the uwsgi qclabs entry
  file:
    src: /etc/uwsgi/apps-available/nrcint.ini
    dest: /etc/uwsgi/apps-enabled/nrcint.ini
    state: link

- name: adapt Mongo host and admin passphrase for dev/test
  set_fact:
    mongo_host: "{{ vars['mongo_host_'+ dtap] }}"
    mongodb_admin_password: "{{ vars['mongodb_admin_password_'+ dtap] }}"

- name: replace the local mongodb connection string in the bioit_mongodb_scripts config file
  lineinfile:
    path: "{{ bioit_bigs_home }}/bioit_mongodb_scripts/config/config.yml"
    regexp: 'CONNECTION_STRING_LOCAL: to_be_replaced_by_ansible'
    line: "CONNECTION_STRING_LOCAL: mongodb://admin:{{ mongodb_admin_password }}@{{ mongo_host.split(',')[0] }}:27017,{{ mongo_host.split(',')[1] }}:27017,{{ mongo_host.split(',')[2] }}:27017/?replicaSet=bioit-HERA&authSource=admin"

- name: Create Python virtual environment
  pip:
    requirements: "{{ bioit_bigs_home }}/bioit_nrc_integration/python/requirements.txt"
    virtualenv: "{{ nrcint_venv }}"
    virtualenv_python: python3.10

- name: restart nrcint supervisord
  supervisorctl:
    name: nrcint
    state: restarted
...