--insert schemes
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(1, 'MLST', 'MLST scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 1, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 1) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(2, 'cgMLST', 'cgMLST scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 2, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 2) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(3, 'PCR serogroup', 'PCR Serogroup scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 4, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 3) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(4, 'Species confirmation', 'Species confirmation scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 5, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 4) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(5, 'Virulence', 'Virulence scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 6, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 5) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(6, 'Antibiotic resistance', 'Antibiotic resistance scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 7, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 6) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(7, 'rMLST', 'rMLST scheme downloaded from PubMLST', 't', 3, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 7) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(8, 'ResFinder4', 'ResFinder4 database', 't', 8, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 8) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(9, 'VFDB_core', 'VirulenceFactor core database', 't', 9, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 9) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(10, 'VirulenceFinder', 'VirulenceFinder database', 't', 10, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 10) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(11, 'PlasmidFinder_grampositive', 'PlasmidFinder gram-positive bacteria', 't', 11, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 11) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(12, 'ResFinder4 mutations', 'ResFinder4 - PointFinder database', 't', 12, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 12) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(13, 'AMRFinder', 'AMRFinder', 't', 13, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_listeria_seqdef', 13) ON CONFLICT DO NOTHING;

--insert scheme_fields
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES(1, 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES(1, 'CC', 'text', 'Clonal Complex', 2, 'f', 'f', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES(1, 'lineage', 'text', 'Lineage', 3, 'f', 'f', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES(2, 'cgST', 'integer', 'Sequence Type (cgMLST)', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES(3, 'profile_id', 'integer', 'Profile id', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES(3, 'serogroup', 'text', 'Serogroup', 2, 'f', 'f', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES((SELECT id FROM schemes WHERE name='rMLST'), 'rST', 'integer', 'Sequence Type for rMLST', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;

--rMLST identification
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'genus', 'rMLST', 'Genus according to rMLST', '$.rmlst_genus', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'species', 'rMLST', 'Species according to rMLST', '$.rmlst_species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'subspecies', 'rMLST', 'Subspecies according to rMLST', '$.rmlst_subspecies', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'lineage', 'rMLST', 'Lineage according to rMLST', '$.rmlst_lineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'sublineage', 'rMLST', 'Sublineage according to rMLST', '$.rmlst_sublineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--AMRFinder
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AMRFinder', 'AMR', 'AMRFinder', 'Subclass of hit of the AMRFinder assay', '$.amr_genes_hits[*].Subclass', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AMRFinder', 'resistance gene', 'AMRFinder', 'Element symbol of hit of the AMRFinder assay', '$.amr_genes_hits[*].Element_symbol', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--ResFinder4
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('ResFinder4', 'AMR', 'ResFinder4', 'Phenotype of hit of the ResFinder4 assay', '$.resfinder4_genes_hits[*].Phenotype', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('ResFinder4', 'resistance gene', 'ResFinder4', 'Resistance gene of hit of the ResFinder4 assay', '$.resfinder4_genes_hits[*].Resistance_gene', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--PlasmidFinder_grampositive
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('PlasmidFinder_grampositive', 'locus', 'PlasmidFinder - Gram positive', 'Locus detected by the PlasmidFinder assay', '$.loci[*].Locus', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--MOB_suite
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('MOB_suite', 'id', 'MOB-suite', 'Id detected by the MOB-suite assay', '$.mob_suite_overview[*].id', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--insert classification_schemes for clustering
INSERT INTO classification_schemes(id, scheme_id, name, description, inclusion_threshold, use_relative_threshold, seqdef_cscheme_id, display_order, status, curator, datestamp) VALUES(1, (SELECT id FROM schemes WHERE name = 'cgMLST'), 'cgMLST_4_diffs_clustering', 'cgMLST profiles clustering at the threshold of 4 allelic differences', 4, false, 1, 1, 'experimental', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING ;
INSERT INTO classification_schemes(id, scheme_id, name, description, inclusion_threshold, use_relative_threshold, seqdef_cscheme_id, display_order, status, curator, datestamp) VALUES(2, (SELECT id FROM schemes WHERE name = 'cgMLST'), 'cgMLST_7_diffs_clustering', 'cgMLST profiles clustering at the threshold of 7 allelic differences', 7, false, 2, 2, 'experimental', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING ;
