INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(1, 'MLST', 'MLST scheme downloaded and updated weekly from pubMLST.', 't', 1, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_mycobacterium_seqdef', 1) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(2, 'cgMLST', 'cgMLST scheme downloaded and updated weekly from pubMLST.', 't', 2, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_mycobacterium_seqdef', 2) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(3, 'Spoligotyping', 'Spoligotyping scheme containing 43 loci with 1 allele (spacer) each, if it is found then it receives the value of 1, else the value of 0.', 't', 4, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_mycobacterium_seqdef', 3) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(4, 'csb_RD', 'csb & regions of difference (RD1, RD9).', 't', 5, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_mycobacterium_seqdef', 4) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(5, 'rMLST', 'rMLST scheme downloaded from PubMLST', 't', 3, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_mycobacterium_seqdef', 5) ON CONFLICT DO NOTHING;

INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES((SELECT id FROM schemes WHERE name='MLST'), 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES((SELECT id FROM schemes WHERE name='cgMLST'), 'cgST', 'integer', 'Sequence Type for cgMLST', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES((SELECT id FROM schemes WHERE name='rMLST'), 'rST', 'integer', 'Sequence Type for rMLST', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;

--spoligotyping
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer01','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer01', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer02','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer02', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer03','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer03', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer3&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer04','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer04', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer4&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer05','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer05', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer5&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer06','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer06', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer6&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer07','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer07', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer7&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer08','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer08', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer8&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer09','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer09', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer9&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer10','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer10', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer10&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer11','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer11', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer11&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer12','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer12', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer12&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer13','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer13', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer13&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer14','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer14', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer14&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer15','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer15', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer15&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer16','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer16', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer16&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer17','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer17', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer17&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer18','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer18', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer18&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer19','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer19', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer19&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer20','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer20', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer20&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer21','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer21', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer21&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer22','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer22', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer22&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer23','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer23', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer23&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer24','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer24', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer24&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer25','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer25', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer25&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer26','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer26', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer26&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer27','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer27', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer27&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer28','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer28', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer28&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer29','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer29', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer29&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer30','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer30', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer30&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer31','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer31', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer31&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer32','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer32', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer32&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer33','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer33', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer33&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer34','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer34', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer34&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer35','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer35', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer35&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer36','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer36', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer36&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer37','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer37', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer37&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer38','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer38', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer38&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer39','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer39', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer39&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer40','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer40', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer40&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer41','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer41', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer41&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer42','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer42', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer42&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('Spacer43','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','Spacer43', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=Spacer43&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer01', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer02', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer03', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer04', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer05', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer06', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer07', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer08', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer09', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer10', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer11', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer12', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer13', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer14', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer15', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer16', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer17', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer18', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer19', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer20', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer21', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer22', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer23', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer24', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer25', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer26', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer27', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer28', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer29', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer30', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer31', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer32', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer33', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer34', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer35', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer36', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer37', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer38', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer39', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer40', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer41', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer42', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Spoligotyping'), 'Spacer43', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--csb_RD
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field) VALUES((SELECT id FROM schemes WHERE name='csb_RD'), 'csb_RD_species', 'text', '', 4, 'f', 'f', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('csb','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','csb', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=csb&allele_id=[?]', 'allele only', 't', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('RD1','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','RD1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=RD1&allele_id=[?]', 'allele only', 't', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('RD9','DNA','text', 'f', 'f', 'bigsdb_mycobacterium_seqdef','RD9', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_mycobacterium_seqdef&page=alleleInfo&locus=RD9&allele_id=[?]', 'allele only', 't', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--csb_RD
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='csb_RD'), 'csb', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='csb_RD'), 'RD1', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='csb_RD'), 'RD9', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--51SNP
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('51SNP', 'genetic group', '51SNP', 'Genetic group from the 51SNP assay', '$.genetic_group', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('51SNP', 'gyrB group', '51SNP', 'gyrB species differentiation from the 51SNP assay', '$.gyrB_group', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('51SNP', 'gyrB species', '51SNP', 'gyrB species differentiation from the 51SNP assay', '$.gyrB_species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('51SNP', 'SCG', '51SNP', 'SNP Cluster Group from the 51SNP assay', '$.scg', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('51SNP', 'ST', '51SNP', 'ST associated with the SNP Cluster Group from the 51SNP assay', '$.st', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--snplineage
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('SNP_lineage', 'detected lineage', 'SNP lineage', 'Detected lineage from the SNP lineage assay', '$.detected_lineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--snpit
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('snpit', 'species', 'snpit', 'Species detected by the snpit assay', '$.snpit_species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('snpit', 'lineage', 'snpit', 'Lineage detected by the snpit assay', '$.snpit_lineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('snpit', 'sublineage', 'snpit', 'Sublineage detected by the snpit assay', '$.snpit_sublineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--hsp65
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('hsp65', 'species', 'hsp65', 'Species detected by the hsp65 assay', '$.loci[*].Species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--NCBI 16S
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('NCBI_16S', 'species', 'NCBI 16S', 'Species detected by the NCBI 16S assay', '$.loci[*].Species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--AMR detection
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'AMR type', 'AMR detection', 'XDR, PRE_XDR, MDR, MONO, NONE, OTHER', '$.amr_type', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'First line resistant', 'AMR detection', 'First line resistant or not (true/false)', '$.amr_first_line_resistant', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Second line group a resistant', 'AMR detection', 'Second line group a resistant or not (true/false)', '$.amr_second_line_group_a_resistant', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Second line group b resistant', 'AMR detection', 'Second line group b resistant or not (true/false)', '$.amr_second_line_group_b_resistant', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Isoniazid', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_INH', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Rifampicin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_RIF', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Levofloxacin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_LEV', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Moxifloxacin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_MXF', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Amikacin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_AMI', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Capreomycin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_CAP', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Kanamycin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_KAN', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Streptomycin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_STM', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Ethionamide', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_ETH', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Pyrazinamide', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_PZA', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Bedaquiline', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_BDQ', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Clofazimine', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_CFZ', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Delamanid', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_DLM', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Ethambutol', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_EMB', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Linezolid', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_LZD', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype D-cycloserine', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_DCS', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Multidrug efflux', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_EFF', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Para-aminosalicylic acid', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_PAS', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Pretomanid', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_PRT', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('AMR_detection', 'Phenotype Rifabutin', 'AMR detection', 'R, R (int.), S, S (int.)', '$.amr_pheno_RBT', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--rMLST identification
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('rMLST', 'genus', 'rMLST', 'Genus according to rMLST', '$.rmlst_genus', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('rMLST', 'species', 'rMLST', 'Species according to rMLST', '$.rmlst_species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('rMLST', 'subspecies', 'rMLST', 'Subspecies according to rMLST', '$.rmlst_subspecies', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('rMLST', 'lineage', 'rMLST', 'Lineage according to rMLST', '$.rmlst_lineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES ('rMLST', 'sublineage', 'rMLST', 'Sublineage according to rMLST', '$.rmlst_sublineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--clustering
INSERT INTO classification_schemes(id, scheme_id, name, description, inclusion_threshold, use_relative_threshold, seqdef_cscheme_id, display_order, status, curator, datestamp) VALUES(1, (SELECT id FROM schemes WHERE name = 'cgMLST'), 'cgMLST_5_diffs_clustering', 'cgMLST profiles clustering at the threshold of 5 allelic differences', 5, false, 1, 1, 'experimental', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING ;
INSERT INTO classification_schemes(id, scheme_id, name, description, inclusion_threshold, use_relative_threshold, seqdef_cscheme_id, display_order, status, curator, datestamp) VALUES(2, (SELECT id FROM schemes WHERE name = 'cgMLST'), 'cgMLST_12_diffs_clustering', 'cgMLST profiles clustering at the threshold of 12 allelic differences', 12, false, 2, 2, 'experimental', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING ;

