INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(1, 'MLST', 'MLST scheme downloaded and updated weekly from Enterobase.', 't', 1, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 1) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(2, 'cgMLST', 'cgMLST scheme downloaded and updated weekly from Enterobase.', 't', 2, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 2) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(3, 'ResFinder4', 'ResFinder4 - ResFinder4 database', 't', 4, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 3) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(4, 'VFDB_core', 'VirulenceFactor core database', 't', 6, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 4) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(5, 'spifinder_fastq', 'SPIFinder carried out on fastq with kma', 't', 8, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 5) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(6, 'spifinder_fasta', 'SPIFinder carried out on fasta with blast', 't', 9, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 6) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(7, 'sistr', 'SISTR ', 't', 10, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 7) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(8, 'seqsero2_allele', 'SeqSero2 allele ', 't', 11, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 8) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(9, 'seqsero2_kmer', 'SeqSero2 kmer ', 't',12, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 9) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(10, 'seqsero2_kmerread', 'SeqSero2 kmerread ', 't', 13, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 10) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(11, 'ResFinder4 mutations', 'ResFinder4 - PointFinder database', 't', 5, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 11) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(12, 'rMLST', 'rMLST scheme downloaded from PubMLST', 't', 3, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 12) ON CONFLICT DO NOTHING;
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(13, 'AMRFinder', 'AMRFinder', 't', 14, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 13) ON CONFLICT DO NOTHING;

---sequence typing fields
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field)
            VALUES(1, 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field)
            VALUES(2, 'cgST', 'integer', 'Sequence Type for cgMLST', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field)
            VALUES((SELECT id FROM schemes WHERE name='rMLST'), 'rST', 'integer', 'Sequence Type for rMLST', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't') ON CONFLICT DO NOTHING;

--spifinder_fastq
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-3','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-3', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-3&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-4','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-4', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-4&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-5','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-5', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-5&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_HPI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_HPI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_HPI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SESS-LEE','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SESS-LEE', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SESS-LEE&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SGI1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SGI1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SGI1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SGI2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SGI2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SGI2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-10','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-10', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-10&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-11','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-11', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-11&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-12','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-12', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-12&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-13','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-13', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-13&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-14','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-14', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-14&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-6','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-6', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-6&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-7','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-7', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-7&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-8','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-8', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-8&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-9','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-9', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-9&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_C63PI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_C63PI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_C63PI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_CS54_ISLAND','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_CS54_ISLAND', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_CS54_ISLAND&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_NOT_NAMED','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_NOT_NAMED', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_NOT_NAMED&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-1', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-2', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-3', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-4', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-5', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_HPI', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SESS-LEE', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SGI1', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SGI2', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-10', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-11', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-12', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-13', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-14', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-6', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-7', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-8', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-9', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_C63PI', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_CS54_ISLAND', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_NOT_NAMED', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--spifinder_fasta
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-3','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-3', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-3&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-4','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-4', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-4&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-5','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-5', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-5&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_HPI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_HPI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_HPI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SESS-LEE','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SESS-LEE', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SESS-LEE&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SGI1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SGI1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SGI1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SGI2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SGI2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SGI2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-10','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-10', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-10&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-11','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-11', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-11&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-12','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-12', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-12&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-13','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-13', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-13&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-14','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-14', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-14&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-6','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-6', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-6&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-7','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-7', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-7&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-8','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-8', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-8&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-9','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-9', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-9&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_C63PI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_C63PI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_C63PI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_CS54_ISLAND','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_CS54_ISLAND', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_CS54_ISLAND&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_NOT_NAMED','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_NOT_NAMED', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_NOT_NAMED&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-1', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-2', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-3', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-4', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-5', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_HPI', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SESS-LEE', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SGI1', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SGI2', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-10', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-11', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-12', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-13', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-14', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-6', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-7', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-8', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-9', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_C63PI', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_CS54_ISLAND', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_NOT_NAMED', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--serotyping
--sistr
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SISTR_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SISTR_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SISTR_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SISTR_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SISTR_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SISTR_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SISTR_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SISTR_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SISTR_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='sistr'), 'SISTR_O_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='sistr'), 'SISTR_H1_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='sistr'), 'SISTR_H2_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('SISTR', 'serotype', 'SISTR', 'Serotype detected by the SISTR assay', '$.sistr_serotype_consensus', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--seqsero2 allele
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_ALLELE_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_ALLELE_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_ALLELE_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_ALLELE_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_ALLELE_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_ALLELE_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_ALLELE_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_ALLELE_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_ALLELE_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_allele'), 'SEQSERO2_ALLELE_O_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_allele'), 'SEQSERO2_ALLELE_H1_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_allele'), 'SEQSERO2_ALLELE_H2_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('SeqSero2', 'serotype raw read allele', 'SeqSero2', 'Serotype detected by the SeqSero2 assay in raw read allele mode', '$.seqsero2_allele_Predicted_serotype', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--seqsero2 kmer
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMER_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMER_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMER_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMER_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMER_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMER_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMER_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMER_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMER_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmer'), 'SEQSERO2_KMER_O_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmer'), 'SEQSERO2_KMER_H1_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmer'), 'SEQSERO2_KMER_H2_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('SeqSero2', 'serotype assembly kmer', 'SeqSero2', 'Serotype detected by the SeqSero2 assay in assembly kmer mode', '$.seqsero2_kmer_Predicted_serotype', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--seqsero2 kmerread
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMERREAD_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMERREAD_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMERREAD_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMERREAD_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMERREAD_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMERREAD_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMERREAD_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMERREAD_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMERREAD_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmerread'), 'SEQSERO2_KMERREAD_O_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmerread'), 'SEQSERO2_KMERREAD_H1_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmerread'), 'SEQSERO2_KMERREAD_H2_ANTIGEN', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('SeqSero2', 'serotype raw read kmer', 'SeqSero2', 'Serotype detected by the SeqSero2 assay in raw read kmer mode', '$.seqsero2_kmerread_Predicted_serotype', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--AMRFinder
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AMRFinder', 'AMR', 'AMRFinder', 'Subclass of hit of the AMRFinder assay', '$.amr_genes_hits[*].Subclass', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AMRFinder', 'resistance gene', 'AMRFinder', 'Element symbol of hit of the AMRFinder assay', '$.amr_genes_hits[*].Element_symbol', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--ResFinder4
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('ResFinder4', 'AMR', 'ResFinder4', 'Phenotype of hit of the ResFinder4 assay', '$.resfinder4_genes_hits[*].Phenotype', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('ResFinder4', 'resistance gene', 'ResFinder4', 'Resistance gene of hit of the ResFinder4 assay', '$.resfinder4_genes_hits[*].Resistance_gene', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--rMLST identification
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'genus', 'rMLST', 'Genus according to rMLST', '$.rmlst_genus', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'species', 'rMLST', 'Species according to rMLST', '$.rmlst_species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'subspecies', 'rMLST', 'Subspecies according to rMLST', '$.rmlst_subspecies', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'lineage', 'rMLST', 'Lineage according to rMLST', '$.rmlst_lineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('rMLST', 'sublineage', 'rMLST', 'Sublineage according to rMLST', '$.rmlst_sublineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--MOB_suite
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('MOB_suite', 'id', 'MOB-suite', 'Id detected by the MOB-suite assay', '$.mob_suite_overview[*].id', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--AbritAMR
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Ampicillin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Ampicillin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Cefotaxime (ESBL) interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Cefotaxime_ESBL_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Cefotaxime (AmpC) interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Cefotaxime_AmpC_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Tetracycline interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Tetracycline_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Gentamicin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Gentamicin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Kanamycin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Kanamycin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Streptomycin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Streptomycin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Sulfathiazole interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Sulfathiazole_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Trimethoprim interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Trimethoprim_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Trim-Sulpha interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Trim_Sulpha_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Chloramphenicol interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Chloramphenicol_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Ciprofloxacin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Ciprofloxacin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Meropenem interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Meropenem_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Azithromycin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Azithromycin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Aminoglycosides (RMT) interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Aminoglycosides_RMT_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Colistin interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Colistin_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Other interpretation', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Other_Interpretation', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Ampicillin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Ampicillin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Cefotaxime (ESBL) ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Cefotaxime_ESBL_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Cefotaxime (AmpC) ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Cefotaxime_AmpC_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Tetracycline ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Tetracycline_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Gentamicin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Gentamicin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Kanamycin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Kanamycin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Streptomycin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Streptomycin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Sulfathiazole ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Sulfathiazole_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Trimethoprim ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Trimethoprim_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Trim-Sulpha ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Trim_Sulpha_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Chloramphenicol ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Chloramphenicol_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Ciprofloxacin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Ciprofloxacin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Meropenem ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Meropenem_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Azithromycin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Azithromycin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Aminoglycosides (RMT) ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Aminoglycosides_RMT_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Colistin ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Colistin_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('AbritAMR', 'Other ResMech detected', 'AbritAMR', 'Resistant, Susceptible or -', '$.abritamr_Other_ResMech', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

--Mykrobe
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('Mykrobe', 'phylogenetic group', 'Mykrobe', 'Phylogenetic group detected by the Mykrobe assay', '$.mykrobe_phylo_group', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('Mykrobe', 'species', 'Mykrobe', 'Species detected by the Mykrobe assay', '$.mykrobe_species', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;
INSERT INTO analysis_fields(analysis_name, field_name, analysis_display_name, field_description, json_path, data_type, curator, datestamp) VALUES('Mykrobe', 'lineage', 'Mykrobe', 'Lineage detected by the Mykrobe assay', '$.mykrobe_lineage', 'text', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING;

-- hierarchical clustering
INSERT INTO classification_schemes(id, scheme_id, name, description, inclusion_threshold, use_relative_threshold, seqdef_cscheme_id, display_order, status, curator, datestamp) VALUES(1, (SELECT id FROM schemes WHERE name = 'cgMLST'), 'cgMLST_5_diffs_clustering', 'cgMLST profiles clustering at the threshold of 5 allelic differences', 5, false, 1, 1, 'experimental', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING ;
INSERT INTO classification_schemes(id, scheme_id, name, description, inclusion_threshold, use_relative_threshold, seqdef_cscheme_id, display_order, status, curator, datestamp) VALUES(2, (SELECT id FROM schemes WHERE name = 'cgMLST'), 'cgMLST_10_diffs_clustering', 'cgMLST profiles clustering at the threshold of 10 allelic differences', 10, false, 2, 2, 'experimental', 1, (SELECT CURRENT_DATE)) ON CONFLICT DO NOTHING ;
