species:
  listeria:
    mlst:
      dirdb: /db/sequence_typing/listeria/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/listeria/cgmlst
      cmd_argument: cgmlst
    pcr_serogroup:
      dirdb: /db/sequence_typing/listeria/serogroup
      cmd_argument: pcr-serogroup
    metal_detergent:
      dirdb: /db/sequence_typing/listeria/metal_detergent_resistance
      cmd_argument: metal-detergent
    typing_virulence:
      dirdb: /db/sequence_typing/listeria/virulence
      cmd_argument: typing-virulence
    typing_amr:
      dirdb: /db/sequence_typing/listeria/antibiotic_resistance
      cmd_argument: typing-amr
    species_confirmation:
      dirdb: /db/sequence_typing/listeria/species_confirmation
      cmd_argument: species-confirmation
    ncbi_amr:
      dirdb: /db/gene_detection/NCBI_AMR
      cmd_argument: ncbi-amr
    resfinder:
      dirdb: /db/gene_detection/ResFinder
      cmd_argument: resfinder
    virulencefinder:
      dirdb: /db/gene_detection/VirulenceFinder-Listeria
      cmd_argument: virulencefinder
    vfdb_core:
      dirdb: /db/gene_detection/VFDB_core
      cmd_argument: vfdb-core
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-gram_positive
      cmd_argument: plasmidfinder
  mycobacterium:
    mlst:
      dirdb: /db/sequence_typing/mycobacterium/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/mycobacterium/cgmlst
      cmd_argument: cgmlst
# all not updated automatically and no git repo
# also distinction with vcf and without vcf...
#    51SNP:  # doesnt make sense to do 51snp since it is a static db of 51 snps
#      cmd_argument: 51snp
#    amr_who:
#      cmd_argument: amr_who
#    hsp65:
#      cmd_argument: hsp65
    ncbi_16s:
      dirdb: /db/gene_detection/NCBI_16S
      cmd_argument: ncbi-16s
#    snp_lineage:
#      cmd_argument: snp-lineage
#    snpit
#      cmd_argument: snpit
  neisseria:
    mlst:
      dirdb: /db/sequence_typing/neisseria/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/neisseria/cgmlst
      cmd_argument: cgmlst
    rplf:
      dirdb: /db/sequence_typing/neisseria/rplf
      cmd_argument: rplf
    bast:
      dirdb: /db/sequence_typing/neisseria/bast
      cmd_argument: bast
    pora:
      dirdb: /db/sequence_typing/neisseria/pora
      cmd_argument: pora
    porb:
      dirdb: /db/sequence_typing/neisseria/porb
      cmd_argument: porb
    feta:
      dirdb: /db/sequence_typing/neisseria/feta
      cmd_argument: feta
    resistance_genes:
      dirdb: /db/sequence_typing/neisseria/resistance_genes
      cmd_argument: resistance-genes
    vaccine_targets:
      dirdb: /db/sequence_typing/neisseria/vaccine_targets
      cmd_argument: vaccine-targets
    fhbp:
      dirdb: /db/sequence_typing/neisseria/fhbp
      cmd_argument: fhbp
    ncbi_amr:
      dirdb: /db/gene_detection/NCBI_AMR
      cmd_argument: ncbi-amr
    resfinder:
      dirdb: /db/gene_detection/ResFinder
      cmd_argument: resfinder
## having the same argparse argument twice does not seem to affect anything
    serogroup_a:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_a
      cmd_argument: serogroup
    serogroup_b:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_b
      cmd_argument: serogroup
    serogroup_c:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_c
      cmd_argument: serogroup
    serogroup_e:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_e
      cmd_argument: serogroup
    serogroup_h:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_h
      cmd_argument: serogroup
    serogroup_l:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_l
      cmd_argument: serogroup
    serogroup_w:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_w
      cmd_argument: serogroup
    serogroup_x:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_x
      cmd_argument: serogroup
    serogroup_y:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_y
      cmd_argument: serogroup
    serogroup_z:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_z
      cmd_argument: serogroup
  stec:
    mlst_warwick:
      dirdb: /db/sequence_typing/ecoli/mlst_warwick
      cmd_argument: mlst-warwick
    mlst_pasteur:
      dirdb: /db/sequence_typing/ecoli/mlst_pasteur
      cmd_argument: mlst-pasteur
    cgmlst:
      dirdb: /db/sequence_typing/ecoli/cgmlst
      cmd_argument: cgmlst
#    pointfinder:
#      dirdb: /usr/local/bin/lmod/PointFinder/20190227/pointfinder_db
#      cmd_argument: pointfinder
## having the same argparse argument twice does not seem to affect anything
    serotype_o:
      dirdb: /db/gene_detection/SerotypeFinder-O_type
      cmd_argument: serotype
    serotype_h:
      dirdb: /db/gene_detection/SerotypeFinder-H_type
      cmd_argument: serotype
    ncbi_amr:
      dirdb: /db/gene_detection/NCBI_AMR
      cmd_argument: ncbi-amr
    resfinder:
      dirdb: /db/gene_detection/ResFinder
      cmd_argument: resfinder
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-entero
      cmd_argument: plasmidfinder
## having the same argparse argument twice does not seem to affect anything
    virulencefinder:
      dirdb: /db/gene_detection/VirulenceFinder-Ecoli
      cmd_argument: virulencefinder
    virulencefinder_shiga:
      dirdb: /db/gene_detection/VirulenceFinder-Shiga
      cmd_argument: virulencefinder
  salmonella:
    mlst:
      dirdb: /db/sequence_typing/salmonella/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/salmonella/cgmlst
      cmd_argument: cgmlst
    spifinder:
      dirdb: /db/pipelines/salmonella/spifinder/genomicepidemiology-spifinder_db-db102668b704
      cmd_argument: spifinder
## having the same argparse argument twice does not seem to affect anything
    serotype_sistr:
      dirdb: /db/SISTR/1.1.1/data
      cmd_argument: serotype
    serotype_seqsero:
      dirdb: /db/pipelines/salmonella/seqsero2/1.2.1/seqsero2_db
      cmd_argument: serotype
    serotype_seqsero_salmid:
      dirdb: /db/pipelines/salmonella/salmid/0.1.23
      cmd_argument: serotype
#    genotyphi:  # genotyphi is a fastq specific option
#      dirdb: /db/pipelines/salmonella/mykrobe
    abritamr:
      dirdb: /db/abritamr/amrfinderplus_data
      cmd_argument: abritamr
    ncbi_amr:
      dirdb: /db/gene_detection/NCBI_AMR
      cmd_argument: ncbi-amr
    resfinder:
      dirdb: /db/gene_detection/ResFinder
      cmd_argument: resfinder
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-entero
      cmd_argument: plasmidfinder
    vfdb_core:
      dirdb: /db/gene_detection/VFDB_core
      cmd_argument: vfdb-core