species:
  enterococcus_faecalis:
    mlst:
      dirdb: /db/sequence_typing/enterococcus_faecalis/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/enterococcus_faecalis/cgmlst
      cmd_argument: cgmlst
#    Not updated automatically + no git repo
#    rmlst:
#      dirdb: /db/sequence_typing/various/rmlst
#      cmd_argument: rmlst
#    No database
#    lrefinder:
#      cmd_argument: lrefinder
#    Not updated automatically + no git repo
#    amrfinder:
#      dirdb: /db/amrfinder/by_version/latest
#      cmd_argument: amrfinder
    resfinder4:
      dirdb: /db/resfinder4/resfinder
      cmd_argument: resfinder4
    pointfinder4:
      dirdb: /db/resfinder4/pointfinder
      cmd_argument: pointfinder
    vfdb-core:
      dirdb: /db/gene_detection/VFDB_core
      cmd_argument: vfdb-core
    virulencefinder:
      dirdb: /db/gene_detection/VirulenceFinder-Enterococcus
      cmd_argument: virulencefinder
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-gram_positive
      cmd_argument: plasmidfinder
#    Not updated automatically + no git repo
#    mob-suite:
#      dirdb: /db/mob_suite/latest
#      cmd_argument: mob-suite
#    bacmet:
#      dirdb: /db/bacmet/latest
#      cmd_argument: bacmet
  enterococcus_faecium:
    mlst:
      dirdb: /db/sequence_typing/enterococcus_faecium/mlst
      cmd_argument: mlst
    mlst_bezdicek:
      dirdb: /db/sequence_typing/enterococcus_faecium/mlst_bezdicek
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/enterococcus_faecium/cgmlst
      cmd_argument: cgmlst
#    Not updated automatically + no git repo
#    rmlst:
#      dirdb: /db/sequence_typing/various/rmlst
#      cmd_argument: rmlst
#    No database
#    lrefinder:
#      cmd_argument: lrefinder
#    Not updated automatically + no git repo
#    amrfinder:
#      dirdb: /db/amrfinder/by_version/latest
#      cmd_argument: amrfinder
    resfinder4:
      dirdb: /db/resfinder4/resfinder
      cmd_argument: resfinder4
    pointfinder4:
      dirdb: /db/resfinder4/pointfinder
      cmd_argument: pointfinder
    vfdb-core:
      dirdb: /db/gene_detection/VFDB_core
      cmd_argument: vfdb-core
    virulencefinder:
      dirdb: /db/gene_detection/VirulenceFinder-Enterococcus
      cmd_argument: virulencefinder
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-gram_positive
      cmd_argument: plasmidfinder
#    Not updated automatically + no git repo
#    mob-suite:
#      dirdb: /db/mob_suite/latest
#      cmd_argument: mob-suite
#    bacmet:
#      dirdb: /db/bacmet/latest
#      cmd_argument: bacmet
  listeria:
    mlst:
      dirdb: /db/sequence_typing/listeria/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/listeria/cgmlst
      cmd_argument: cgmlst
#    Not updated automatically + no git repo
#    rmlst:
#      dirdb: /db/sequence_typing/various/rmlst
#      cmd_argument: rmlst
    pcr_serogroup:
      dirdb: /db/sequence_typing/listeria/serogroup
      cmd_argument: pcr-serogroup
    typing_virulence:
      dirdb: /db/sequence_typing/listeria/virulence
      cmd_argument: typing-virulence
    typing_amr:
      dirdb: /db/sequence_typing/listeria/antibiotic_resistance
      cmd_argument: typing-amr
    species_confirmation:
      dirdb: /db/sequence_typing/listeria/species_confirmation
      cmd_argument: species-confirmation
#    Not updated automatically + no git repo
#    amrfinder:
#      dirdb: /db/amrfinder/by_version/latest
#      cmd_argument: amrfinder
    resfinder4:
      dirdb: /db/resfinder4/resfinder
      cmd_argument: resfinder4
    pointfinder4:
      dirdb: /db/resfinder4/pointfinder
      cmd_argument: resfinder4
    virulencefinder:
      dirdb: /db/gene_detection/VirulenceFinder-Listeria
      cmd_argument: virulencefinder
    vfdb_core:
      dirdb: /db/gene_detection/VFDB_core
      cmd_argument: vfdb-core
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-gram_positive
      cmd_argument: plasmidfinder
#    Not updated automatically + no git repo
#    mob_suite:
#      dirdb: /db/mob_suite/latest
#      cmd_argument: mob-suite
  mycobacterium:
    mlst:
      dirdb: /db/sequence_typing/mycobacterium/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/mycobacterium/cgmlst
      cmd_argument: cgmlst
#    Not updated automatically + no git repo
#    rmlst:
#      dirdb: /db/sequence_typing/various/rmlst
#      cmd_argument: rmlst
#    All not updated automatically and no git repo
#    also distinction with vcf and without vcf...
#    51SNP:  # doesn't make sense to do 51snp since it is a static db of 51 snps
#      cmd_argument: 51snp
#    amr:
#      cmd_argument: amr
#    hsp65:
#      cmd_argument: hsp65
    ncbi_16s:
      dirdb: /db/gene_detection/NCBI_16S
      cmd_argument: ncbi-16s
#    snp_lineage:
#      cmd_argument: snp-lineage
#    snpit
#      cmd_argument: snpit
  neisseria:
    mlst:
      dirdb: /db/sequence_typing/neisseria/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/neisseria/cgmlst
      cmd_argument: cgmlst
#    Not updated automatically + no git repo
#    rmlst:
#      dirdb: /db/sequence_typing/various/rmlst
#      cmd_argument: rmlst
    rplf:
      dirdb: /db/sequence_typing/neisseria/rplf
      cmd_argument: rplf
    bast:
      dirdb: /db/sequence_typing/neisseria/bast
      cmd_argument: bast
    pora:
      dirdb: /db/sequence_typing/neisseria/pora
      cmd_argument: pora
    porb:
      dirdb: /db/sequence_typing/neisseria/porb
      cmd_argument: porb
    feta:
      dirdb: /db/sequence_typing/neisseria/feta
      cmd_argument: feta
    resistance_genes:
      dirdb: /db/sequence_typing/neisseria/resistance_genes
      cmd_argument: resistance-genes
    vaccine_targets:
      dirdb: /db/sequence_typing/neisseria/vaccine_targets
      cmd_argument: vaccine-targets
    fhbp:
      dirdb: /db/sequence_typing/neisseria/fhbp
      cmd_argument: fhbp
    resfinder4:
      dirdb: /db/resfinder4/resfinder
      cmd_argument: resfinder4
    pointfinder4:
      dirdb: /db/resfinder4/pointfinder
      cmd_argument: resfinder4
## having the same argparse argument twice does not seem to affect anything
    serogroup_a:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_a
      cmd_argument: serogroup
    serogroup_b:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_b
      cmd_argument: serogroup
    serogroup_c:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_c
      cmd_argument: serogroup
    serogroup_e:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_e
      cmd_argument: serogroup
    serogroup_h:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_h
      cmd_argument: serogroup
    serogroup_l:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_l
      cmd_argument: serogroup
    serogroup_w:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_w
      cmd_argument: serogroup
    serogroup_x:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_x
      cmd_argument: serogroup
    serogroup_y:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_y
      cmd_argument: serogroup
    serogroup_z:
      dirdb: /db/sequence_typing/neisseria/capsule_region_a_serogroup_z
      cmd_argument: serogroup
#    Not updated automatically + no git repo
#    gmats:
#      dirdb: /db/pipelines/neisseria/gMATS_DB.txt
#      cmd_argument: gmats
#    mendevar:
#      dirdb: /db/pipelines/neisseria/mendevar_DB.txt
#      cmd_argument: mendevar
  stec:
    mlst_warwick:
      dirdb: /db/sequence_typing/ecoli/mlst_warwick
      cmd_argument: mlst-warwick
    mlst_pasteur:
      dirdb: /db/sequence_typing/ecoli/mlst_pasteur
      cmd_argument: mlst-pasteur
    cgmlst:
      dirdb: /db/sequence_typing/ecoli/cgmlst
      cmd_argument: cgmlst
## having the same argparse argument twice does not seem to affect anything
    serotype_o:
      dirdb: /db/gene_detection/SerotypeFinder-O_type
      cmd_argument: serotype
    serotype_h:
      dirdb: /db/gene_detection/SerotypeFinder-H_type
      cmd_argument: serotype
#    Not updated automatically + no git repo
#    amrfinder:
#      dirdb: /db/amrfinder/by_version/latest
#      cmd_argument: amrfinder
    resfinder4:
      dirdb: /db/resfinder4/resfinder
      cmd_argument: resfinder4
    pointfinder4:
      dirdb: /db/resfinder4/pointfinder
      cmd_argument: resfinder4
    plasmidfinder:
      dirdb: /db/gene_detection/PlasmidFinder-entero
      cmd_argument: plasmidfinder
    ncbi_stress:
      dirdb: /db/gene_detection/NCBI_STRESS
      cmd_argument: ncbi-stress
## having the same argparse argument twice does not seem to affect anything
    virulencefinder:
      dirdb: /db/gene_detection/VirulenceFinder-Ecoli
      cmd_argument: virulencefinder
    virulencefinder_shiga:
      dirdb: /db/gene_detection/VirulenceFinder-Shiga
      cmd_argument: virulencefinder
  salmonella:
    mlst:
      dirdb: /db/sequence_typing/salmonella/mlst
      cmd_argument: mlst
    cgmlst:
      dirdb: /db/sequence_typing/salmonella/cgmlst
      cmd_argument: cgmlst
#    Not updated automatically + no git repo
#    rmlst:
#      dirdb: /db/sequence_typing/various/rmlst
#      cmd_argument: rmlst
    spifinder:
      dirdb: /db/pipelines/salmonella/spifinder/genomicepidemiology-spifinder_db-db102668b704
      cmd_argument: spifinder
## having the same argparse argument twice does not seem to affect anything
    serotype_sistr:
      dirdb: /db/SISTR/1.1.1/data
      cmd_argument: serotype
    serotype_seqsero:
      dirdb: /db/pipelines/salmonella/seqsero2/1.2.1/seqsero2_db
      cmd_argument: serotype
    abritamr:
      dirdb: /db/abritamr_2/amrfinderplus_data
      cmd_argument: abritamr
#    Not updated automatically + no git repo
#    amrfinder:
#      dirdb: /db/amrfinder/by_version/latest
#      cmd_argument: amrfinder
    resfinder4:
      dirdb: /db/resfinder4/resfinder
      cmd_argument: resfinder4
    pointfinder4:
      dirdb: /db/resfinder4/pointfinder
      cmd_argument: resfinder4
    vfdb_core:
      dirdb: /db/gene_detection/VFDB_core
      cmd_argument: vfdb-core
#    Not updated automatically + no git repo
#    mob_suite:
#      dirdb: /db/mob_suite/latest
#      cmd_argument: mob-suite
    mykrobe:
      dirdb: /db/mykrobe/latest
      cmd_argument: mykrobe
viral:
  sars_cov_2:
    dirsdb:
      - /db/nextclade3/sars-cov-2
  influenza_a:
    dirsdb:
      - /db/nextclade3/flu_h1n1pdm/ha
      - /db/nextclade3/flu_h1n1pdm/mp
      - /db/nextclade3/flu_h1n1pdm/na
      - /db/nextclade3/flu_h1n1pdm/np
      - /db/nextclade3/flu_h1n1pdm/ns
      - /db/nextclade3/flu_h1n1pdm/pa
      - /db/nextclade3/flu_h1n1pdm/pb1
      - /db/nextclade3/flu_h1n1pdm/pb2
      - /db/nextclade3/flu_h3n2/ha
      - /db/nextclade3/flu_h3n2/mp
      - /db/nextclade3/flu_h3n2/na
      - /db/nextclade3/flu_h3n2/np
      - /db/nextclade3/flu_h3n2/ns
      - /db/nextclade3/flu_h3n2/pa
      - /db/nextclade3/flu_h3n2/pb1
      - /db/nextclade3/flu_h3n2/pb2
  influenza_b:
    dirsdb:
      - /db/nextclade3/flu_vic/ha
      - /db/nextclade3/flu_vic/na
      - /db/nextclade3/flu_yam/ha