-- migrate:up
ALTER TABLE isolates
    ADD COLUMN epi_link text,
    ADD COLUMN perinatal_isolate_strain_mother text,
    ADD COLUMN perinatal_isolate_strain_fetus text,
    ADD COLUMN perinatal_isolate_strain_newborn text,
    ADD COLUMN perinatal_unknown_perinatal_info text,
    ADD COLUMN perinatal_not_applicable text,
    ADD COLUMN pregnancy_symptom text,
    ADD COLUMN pregnancy_outcome text,
    ADD COLUMN suspected_vehicle_canned_food_products text,
    ADD COLUMN suspected_vehicle_drinks text,
    ADD COLUMN suspected_vehicle_drinking_water text,
    ADD COLUMN suspected_vehicle_vegetable_and_products_thereof text,
    ADD COLUMN suspected_vehicle_starchy_food text,
    ADD COLUMN suspected_vehicle_nuts_and_seeds text,
    ADD COLUMN suspected_vehicle_candy_chocolate_candy_and_sugar_candy text,
    ADD COLUMN suspected_vehicle_mammalian_milk_based_food text,
    ADD COLUMN suspected_vehicle_cheese text,
    ADD COLUMN suspected_vehicle_eggs_edible_and_products_thereof text,
    ADD COLUMN suspected_vehicle_seafood_and_products_thereof text,
    ADD COLUMN suspected_vehicle_beef_and_products_thereof text,
    ADD COLUMN suspected_vehicle_pork_and_products_thereof text,
    ADD COLUMN suspected_vehicle_lamb_meat_and_products_thereof text,
    ADD COLUMN suspected_vehicle_chicken_meat_and_products_thereof text,
    ADD COLUMN suspected_vehicle_poultry_and_products_thereof text,
    ADD COLUMN suspected_vehicle_turkey_meat_and_products_thereof text,
    ADD COLUMN suspected_vehicle_cats text,
    ADD COLUMN suspected_vehicle_bats text,
    ADD COLUMN suspected_vehicle_other_pets text,
    ADD COLUMN suspected_vehicle_captive_wild_animals_in_zoo text,
    ADD COLUMN suspected_vehicle_other_wild_animals text,
    ADD COLUMN suspected_vehicle_unknown text,
    ADD COLUMN serogroup_pheno text,
    ADD COLUMN related_disease text,
    ADD COLUMN mode_of_transmission text,
    ADD COLUMN identification_culture text,
    ADD COLUMN identification_pcr text,
    ADD COLUMN identification_malditof text,
    ADD COLUMN serotype_pheno text,
    ADD COLUMN case_type text,
    ADD COLUMN symptom_adult_gastroenteritis text,
    ADD COLUMN symptom_adult_unknown text,
    ADD COLUMN symptom_adult_sepsis_due_to_listeria_monocytogenes text,
    ADD COLUMN symptom_adult_meningitis_and_meningoencephalitis text,
    ADD COLUMN symptom_adult_granulomatosis text,
    ADD COLUMN symptom_adult_other text,
    ADD COLUMN symptom_child_gastroenteritis text,
    ADD COLUMN symptom_child_unknown text,
    ADD COLUMN symptom_child_sepsis_due_to_listeria_monocytogenes text,
    ADD COLUMN symptom_child_meningitis_and_meningoencephalitis text,
    ADD COLUMN symptom_child_granulomatosis text,
    ADD COLUMN symptom_child_other text,
    ADD COLUMN mic_amo real,
    ADD COLUMN mic_amo_I text,
    ADD COLUMN mic_amp real,
    ADD COLUMN mic_amp_I text,
    ADD COLUMN mic_chl real,
    ADD COLUMN mic_chl_I text,
    ADD COLUMN mic_cip real,
    ADD COLUMN mic_cip_I text,
    ADD COLUMN mic_ery real,
    ADD COLUMN mic_ery_I text,
    ADD COLUMN mic_gmn real,
    ADD COLUMN mic_gmn_I text,
    ADD COLUMN mic_str real,
    ADD COLUMN mic_str_I text,
    ADD COLUMN mic_tet real,
    ADD COLUMN mic_tet_I text,
    ADD COLUMN mic_tmpsmx real,
    ADD COLUMN mic_tmpsmx_I text,
    ADD COLUMN mic_van real,
    ADD COLUMN mic_van_I text;

-- migrate:down
ALTER TABLE isolates
    DROP COLUMN epi_link,
    DROP COLUMN perinatal_isolate_strain_mother,
    DROP COLUMN perinatal_isolate_strain_fetus,
    DROP COLUMN perinatal_isolate_strain_newborn,
    DROP COLUMN perinatal_unknown_perinatal_info,
    DROP COLUMN perinatal_not_applicable,
    DROP COLUMN pregnancy_symptom,
    DROP COLUMN pregnancy_outcome,
    DROP COLUMN suspected_vehicle_canned_food_products,
    DROP COLUMN suspected_vehicle_drinks,
    DROP COLUMN suspected_vehicle_drinking_water,
    DROP COLUMN suspected_vehicle_vegetable_and_products_thereof,
    DROP COLUMN suspected_vehicle_starchy_food,
    DROP COLUMN suspected_vehicle_nuts_and_seeds,
    DROP COLUMN suspected_vehicle_candy_chocolate_candy_and_sugar_candy,
    DROP COLUMN suspected_vehicle_mammalian_milk_based_food,
    DROP COLUMN suspected_vehicle_cheese,
    DROP COLUMN suspected_vehicle_eggs_edible_and_products_thereof,
    DROP COLUMN suspected_vehicle_seafood_and_products_thereof,
    DROP COLUMN suspected_vehicle_beef_and_products_thereof,
    DROP COLUMN suspected_vehicle_pork_and_products_thereof,
    DROP COLUMN suspected_vehicle_lamb_meat_and_products_thereof,
    DROP COLUMN suspected_vehicle_chicken_meat_and_products_thereof,
    DROP COLUMN suspected_vehicle_poultry_and_products_thereof,
    DROP COLUMN suspected_vehicle_turkey_meat_and_products_thereof,
    DROP COLUMN suspected_vehicle_cats,
    DROP COLUMN suspected_vehicle_bats,
    DROP COLUMN suspected_vehicle_other_pets,
    DROP COLUMN suspected_vehicle_captive_wild_animals_in_zoo,
    DROP COLUMN suspected_vehicle_other_wild_animals,
    DROP COLUMN suspected_vehicle_unknown,
    DROP COLUMN serogroup_pheno,
    DROP COLUMN related_disease,
    DROP COLUMN mode_of_transmission,
    DROP COLUMN identification_culture,
    DROP COLUMN identification_pcr,
    DROP COLUMN identification_malditof,
    DROP COLUMN serotype_pheno,
    DROP COLUMN case_type,
    DROP COLUMN symptom_adult_gastroenteritis,
    DROP COLUMN symptom_adult_unknown,
    DROP COLUMN symptom_adult_sepsis_due_to_listeria_monocytogenes,
    DROP COLUMN symptom_adult_meningitis_and_meningoencephalitis,
    DROP COLUMN symptom_adult_granulomatosis,
    DROP COLUMN symptom_adult_other,
    DROP COLUMN symptom_child_gastroenteritis,
    DROP COLUMN symptom_child_unknown,
    DROP COLUMN symptom_child_sepsis_due_to_listeria_monocytogenes,
    DROP COLUMN symptom_child_meningitis_and_meningoencephalitis,
    DROP COLUMN symptom_child_granulomatosis,
    DROP COLUMN symptom_child_other,
    DROP COLUMN mic_amo,
    DROP COLUMN mic_amo_I,
    DROP COLUMN mic_amp,
    DROP COLUMN mic_amp_I,
    DROP COLUMN mic_chl,
    DROP COLUMN mic_chl_I,
    DROP COLUMN mic_cip,
    DROP COLUMN mic_cip_I,
    DROP COLUMN mic_ery,
    DROP COLUMN mic_ery_I,
    DROP COLUMN mic_gmn,
    DROP COLUMN mic_gmn_I,
    DROP COLUMN mic_str,
    DROP COLUMN mic_str_I,
    DROP COLUMN mic_tet,
    DROP COLUMN mic_tet_I,
    DROP COLUMN mic_tmpsmx,
    DROP COLUMN mic_tmpsmx_I,
    DROP COLUMN mic_van,
    DROP COLUMN mic_van_I;