-- migrate:up
ALTER TABLE isolates
    DROP COLUMN suspected_vehicle_canned_food_products,
    DROP COLUMN suspected_vehicle_drinks,
    DROP COLUMN suspected_vehicle_drinking_water,
    DROP COLUMN suspected_vehicle_vegetable_and_products_thereof,
    DROP COLUMN suspected_vehicle_starchy_food,
    DROP COLUMN suspected_vehicle_nuts_and_seeds,
    DROP COLUMN suspected_vehicle_candy_chocolate_candy_and_sugar_candy,
    DROP COLUMN suspected_vehicle_mammalian_milk_based_food,
    DROP COLUMN suspected_vehicle_cheese,
    DROP COLUMN suspected_vehicle_eggs_edible_and_products_thereof,
    DROP COLUMN suspected_vehicle_seafood_and_products_thereof,
    DROP COLUMN suspected_vehicle_beef_and_products_thereof,
    DROP COLUMN suspected_vehicle_pork_and_products_thereof,
    DROP COLUMN suspected_vehicle_lamb_meat_and_products_thereof,
    DROP COLUMN suspected_vehicle_chicken_meat_and_products_thereof,
    DROP COLUMN suspected_vehicle_poultry_and_products_thereof,
    DROP COLUMN suspected_vehicle_turkey_meat_and_products_thereof,
    DROP COLUMN suspected_vehicle_cats,
    DROP COLUMN suspected_vehicle_bats,
    DROP COLUMN suspected_vehicle_other_pets,
    DROP COLUMN suspected_vehicle_captive_wild_animals_in_zoo,
    DROP COLUMN suspected_vehicle_other_wild_animals,
    DROP COLUMN suspected_vehicle_unknown;

 -- migrate:down
ALTER TABLE isolates
    ADD COLUMN suspected_vehicle_canned_food_products text,
    ADD COLUMN suspected_vehicle_drinks text,
    ADD COLUMN suspected_vehicle_drinking_water text,
    ADD COLUMN suspected_vehicle_vegetable_and_products_thereof text,
    ADD COLUMN suspected_vehicle_starchy_food text,
    ADD COLUMN suspected_vehicle_nuts_and_seeds text,
    ADD COLUMN suspected_vehicle_candy_chocolate_candy_and_sugar_candy text,
    ADD COLUMN suspected_vehicle_mammalian_milk_based_food text,
    ADD COLUMN suspected_vehicle_cheese text,
    ADD COLUMN suspected_vehicle_eggs_edible_and_products_thereof text,
    ADD COLUMN suspected_vehicle_seafood_and_products_thereof text,
    ADD COLUMN suspected_vehicle_beef_and_products_thereof text,
    ADD COLUMN suspected_vehicle_pork_and_products_thereof text,
    ADD COLUMN suspected_vehicle_lamb_meat_and_products_thereof text,
    ADD COLUMN suspected_vehicle_chicken_meat_and_products_thereof text,
    ADD COLUMN suspected_vehicle_poultry_and_products_thereof text,
    ADD COLUMN suspected_vehicle_turkey_meat_and_products_thereof text,
    ADD COLUMN suspected_vehicle_cats text,
    ADD COLUMN suspected_vehicle_bats text,
    ADD COLUMN suspected_vehicle_other_pets text,
    ADD COLUMN suspected_vehicle_captive_wild_animals_in_zoo text,
    ADD COLUMN suspected_vehicle_other_wild_animals text,
    ADD COLUMN suspected_vehicle_unknown text;