#!/usr/bin/env python
import argparse
import datetime
import hashlib
import json
import logging
import os
import re
import shutil
import smtplib
import socket
import sys
import traceback
from email.message import EmailMessage
from pathlib import Path
from typing import Dict, Union

# import dnspython # somehow this package is a requirement without actually needing to be imported, probably imported in pymongo
import pymongo
import yaml
from pymongo.read_concern import ReadConcern
from pymongo.write_concern import WriteConcern

PYTHONPATH = Path(__file__).resolve().parent.parent
sys.path.append(str(PYTHONPATH))

from MongoDB.util.mongo_querying import Mongoquerying
from MongoDB.util.mongo_initialisation import MongoInitialisation
from MongoDB.util.mongo_custom_clustering import MongoCustomClustering
from MongoDB.config import MONGO_CONFIG
from MongoDB.config import CLUSTERING_CONFIG
from MongoDB.util.command.command import Command


def _parse_arguments(specieslist: list) -> argparse.Namespace:
    """
    Parses the command line arguments.
    !!Also add arguments/variables to main function!!
    :param specieslist: list of all the species choices
    :return: Parsed arguments
    """
    parser = argparse.ArgumentParser()
    mutually_exclusive_group = parser.add_mutually_exclusive_group(required=True)
    mutually_exclusive_group.add_argument('--subvaldict', type=json.loads)
    mutually_exclusive_group.add_argument('--jsonfilepath', type=Path)
    parser.add_argument("--species", required=True, type=str,
                        choices=specieslist)
    parser.add_argument("--results_type", required=True, type=str, choices=['new_isolate', 'reanalysis', 'badqc_validated', 'resequencing_validated'])
    parser.add_argument("--reportdirectorypath", required=False, type=str)  # not mandatory because of reanalysis
    parser.add_argument("--fastafilepath", required=False, type=str)  # not mandatory because of reanalysis
    parser.add_argument("--vcffilepath", required=False, type=str)  # not mandatory because of reanalysis
    parser.add_argument("--technical_id", required=True, type=str)
    # parser.add_argument('--bigs', action='store_true',
    #                     help='Prepare and send folder over to Bigs for automated insert (+assembly), html tagging and report moving')  # todo unfinished
    parser.add_argument('--alternate_connection_string', type=str, help=argparse.SUPPRESS)  # will replace connection string, only for small testing purposes
    parser.add_argument('--dont_send_email', action='store_true', help=argparse.SUPPRESS)  # will not send emails, mainly used for blocking the reanalysis spam
    return parser.parse_args()


def _write_document(opened_collection: pymongo.collection.Collection, json_input: dict) -> str:
    """
    write a document into a collection.
    :param opened_collection: the collection where the document needs to be saved
    :param json_input: the document to store into the collection
    :return: id of inserted document (either pre-given in json_input or auto-generated by Mongo)
    """
    collection_write = opened_collection.with_options(write_concern=WriteConcern(w="majority")).insert_one(json_input)
    logging.debug(f"Writing {collection_write.inserted_id} in collection {opened_collection}")
    return collection_write.inserted_id


def _new_isolate(technical_id: str, reportdirectorypath: str, vcffilepath: str, fastafilepath: str,
                 results: dict) -> Dict[str, Union[str, object]]:
    """
    Initialises new isolate dictionary including its results
    :param technical_id:
    :param vcffilepath:
    :param fastafilepath:
    :param results:
    :return:
    """
    results["results_version"] = 1  # this version always increments
    results["changed_version"] = 1  # this version only increments whenever something actually changed
    new_isolate_dict = {"_id": technical_id,
                        "report_directory": reportdirectorypath,
                        "vcf_path": vcffilepath,
                        "fasta_path": fastafilepath,
                        "previous_latest_results_document": None,  # _write_document(old_isolateresults_collection, results)
                        "creation_date": datetime.datetime.utcnow(),
                        "latest_analysis_date": _return_YMD_from_DMYhms(results["analysis_date"]),
                        "results": results}
    return new_isolate_dict


def prepend_string_dot_to_dict_keys(input_dictionary: dict, prepending: str = 'results') -> Dict[str, Union[str, object]]:
    """
    This function is designed to update only results that have been reanalyzed; by using dot notation in the dicts only the relevant assays/metadata are updated upon reanalysis.
    The function can of course serve other purposes
    Dot notation documentation: https://www.mongodb.com/docs/manual/core/document/#dot-notation
    :param input_dictionary:
    :param prepending: string to prepend to dictionary keys separated by dot
    :return: dict with prepended string joined with dot
    """
    keydict = {}
    import copy
    input_dictionary_copy = copy.deepcopy(input_dictionary)
    for key in input_dictionary:
        if key == 'qc' or key == 'assembly':
            for subkey in input_dictionary[key]:
                input_dictionary_copy['.'.join([key, subkey])] = input_dictionary_copy[key][subkey]
            input_dictionary_copy.pop(key)
    for key in input_dictionary_copy:
        keydict[key] = '.'.join([prepending, key])
    return dict((keydict[key], value) for (key, value) in input_dictionary_copy.items())


def _max_temp_allele_name_new_entry(hashed_AD_collection: pymongo.collection.Collection,
                                    locus: str, scheme: str) -> str:
    """
    Find the last temporary name for an hashed allele and returns a new id for the new allele to add.
    :param hashed_AD_collection: hashed allele collection from mongo db
    :param locus: locus name
    :param scheme: scheme name
    :return: the name for the new temporary allele.
    """
    query_max_temp_allele_name_doc = hashed_AD_collection.find_one({"scheme": scheme, "locus": locus}, sort=[('insertion_date',-1)])
    if query_max_temp_allele_name_doc is None:
        return f'{locus}_temp_1'
    else:
        max_temp_allele_name = int(query_max_temp_allele_name_doc['temp_allele_name'].split('_')[-1])
        return f'{locus}_temp_{max_temp_allele_name + 1}'


def find_hashes_in_results_and_add_to_collection(results: dict, mongoinit: MongoInitialisation, config_data: dict, species: str, mode: str) -> Dict[str, Union[str, object]]:
    """
    finds hashes in json output report for multilocus sequence typing schemes and adds these hashes and alleles to a separate collection: new_allele_hashes.
    Also replace the hashes by temporary allele identifiers and purges the sequences to save space
    :param results: results dictionary
    :param mongoinit: Mongointitialisation object to initialise collection connections
    :param config_data: Mongo config data
    :param species:
    :return: results
    """
    hashed_ad_collection = mongoinit.initialise_hashing_collection(config_data, species)
    for typing_scheme in ['mlst', 'cgmlst',  'mlst_warwick', 'mlst_pasteur']:
        if typing_scheme in results:
            for locus_index, allele_info in enumerate(results[typing_scheme]['loci']):
                # check if allele designation is md5 hash (32 char combination of letters andor numbers)
                if re.findall(r'(?i)(?<![a-z0-9])[a-z0-9]{32}(?![a-z0-9])', allele_info['Allele']):
                    logging.info('new allele detected')
                    existing_document = hashed_ad_collection.with_options(
                        read_concern=ReadConcern(level="majority")).find_one(
                        {"scheme": typing_scheme, "locus": allele_info['Locus'],
                         "hashed_allele": allele_info['Allele']})
                    if existing_document is None:
                        temp_allele = _max_temp_allele_name_new_entry(hashed_ad_collection, allele_info['Locus'], typing_scheme)
                        _write_document(hashed_ad_collection, {"scheme": typing_scheme,
                                                               "locus": allele_info['Locus'],
                                                               "hashed_allele": allele_info['Allele'],
                                                               "allele_sequence": allele_info['Allele_sequence'],
                                                               "encountered_count": 1,
                                                               "resolved_AD": 0,
                                                               "temp_allele_name": temp_allele,
                                                               "insertion_date": datetime.datetime.utcnow()
                                                               })
                    else:
                        temp_allele = existing_document["temp_allele_name"]
                        already_present = False
                        if mode == 'reanalysis':
                            hash_old = existing_document["hashed_allele"]
                            if hash_old == allele_info['Allele']:
                                already_present = True
                                logging.info('hash/temp allele already present')
                        if mode == 'new_isolate' or mode == 'reanalysis' and not already_present:
                            hashed_ad_collection.with_options(write_concern=WriteConcern(w="majority")).update_one(
                                {"_id": existing_document['_id']},
                                {"$inc": {"encountered_count": 1}})
                            logging.info(f"hashed allele '{allele_info['Allele']}' encounter incremented by one")
                    results[typing_scheme]['loci'][locus_index].pop('Allele_sequence')
                    results[typing_scheme]['loci'][locus_index][
                        'Allele'] = temp_allele  # replace in the results the name of the allele (no hash anymore)
    return results


def _return_YMD_from_DMYhms(datetimestring: str) -> str:
    """
    Converts between from long to short datetime string format
    :param datetimestring:
    :return: Short datetime string format
    """
    return datetime.datetime.strptime(datetimestring, '%d/%m/%Y - %X').strftime('%Y-%m-%d')


def parameter_compatibility_checks(args: argparse.Namespace) -> None:
    """
    Checks compatibility of argparse arguments
    :param args: argparse arguments namespace
    :return: None
    """
    # if args.results_type == 'reanalysis' and args.bigs is True:
    #     raise Exception('Bigs upload only available for new isolates')
    if args.results_type == 'badqc_validated' and not args.subvaldict:
        raise Exception('subvaldict necessary when using results_type badqc_validated')
    if args.results_type == 'resequencing_validated' and not args.subvaldict:
        raise Exception('subvaldict necessary when using results_type badqc_validated')
    if args.results_type == 'new_isolate' and not args.jsonfilepath:
        raise Exception('jsonfilepath necessary when using results_type new_isolate')
    if args.results_type == 'reanalysis' and not args.jsonfilepath:
        raise Exception('jsonfilepath necessary when using results_type reanalysis')


def _check_if_results_changed(current_results: Dict[str, Union[str, object]], new_results: Dict[str, Union[str, object]]) -> [bool, list, list]:
    any_result_changed = False
    unchanged_results = []
    changed_results = []
    for mainkey in new_results:  # mainkey is assay
        if isinstance(new_results[mainkey], dict):
            for subkey in new_results[mainkey]:
                if mainkey not in current_results:
                    logging.info(f"{mainkey} not in current results")
                    any_result_changed = True
                    changed_results.append(mainkey)
                elif subkey == 'loci' or subkey == 'results' or subkey.startswith('hits'):
                    if subkey not in current_results[mainkey] or new_results[mainkey][subkey] != \
                            current_results[mainkey][subkey]:
                        # keep in mind that loci is a list: it seems as if loci are always outputted in the same order though so that is allright
                        logging.info(f"{mainkey}{subkey} different or not in old")
                        any_result_changed = True
                        changed_results.append(mainkey)
            if mainkey not in changed_results:
                unchanged_results.append(mainkey)
    return any_result_changed, unchanged_results, changed_results

# def prepare_reports_for_bigs(jsonfilepath: Path, results_changed: dict) -> None:
# todo later; replace json file by json file from mongo with extra information

class MainMongo:
    """
    Class containing definitions to insert samples into MongoDB
    """
    def __init__(self, technical_id: str, species: str, results_type: str, jsonfilepath: Path = None, subvaldict: Dict[str, str] = None, reportdirectorypath: Path = None, fastafilepath: Path = None, vcffilepath: Path = None, alternate_connection_string: str = None, dont_send_email: bool = False) -> None:
        """
        See argparse function for variables and their requiredness
        :param technical_id:
        :param species:
        :param results_type:
        :param jsonfilepath:
        :param subvaldict:
        :param reportdirectorypath:
        :param fastafilepath:
        :param vcffilepath:
        :param alternate_connection_string:
        """
        self.technical_id = technical_id
        self.species = species
        self.results_type = results_type
        self.jsonfilepath = jsonfilepath
        self.subvaldict = subvaldict
        self.reportdirectorypath = reportdirectorypath
        self.fastafilepath = fastafilepath
        self.vcffilepath = vcffilepath
        self.alternate_connection_string = alternate_connection_string
        self.dont_send_email = dont_send_email
        
        self.run_MainMongo()

    def run_MainMongo(self) -> None:
        """
        Main function
        :return:
        """
        # Parse config
        with open(MONGO_CONFIG, encoding='utf-8') as handle:
            self.config_data = yaml.safe_load(handle)

        # if testing purposes; replace connection string by testing connection string
        if self.alternate_connection_string:
            self.config_data['CONNECTION_STRING_BASE'] = self.alternate_connection_string

        try:
            # Configure stdout logging
            logging.basicConfig(level=logging.DEBUG, stream=sys.stdout)

            # Open collections
            self.mongoinit = MongoInitialisation()
            self.isolates_collection, self.old_isolateresults_collection, self.isolates_badqc_collection, self.isolates_resequencing_collection = self.mongoinit.initialise_collections(
                self.config_data, self.species)
            self.st_collection, self.cluster_membership_collection, self.cluster_merging_collection = \
                self.mongoinit.initialise_clustering_collections(self.config_data, self.species)
            self.mongoquerying = Mongoquerying()

            # If statement for results_type
            if self.results_type == "new_isolate":
                new_records = json.load(open(self.jsonfilepath, 'r'))
                # todo check if fasta path and vcf path are real?
                isolates_findone = self.isolates_collection.find_one({"_id": self.technical_id})
                if isolates_findone:
                    self._new_resequencing_arrival(new_records, dict(isolates_findone), self.isolates_collection)
                else:
                    # Were excluding documents that were validated, additionally only documents that were validated with a negative result are still in the badqc collection
                    # Additionally, documents that were negatively validated now have their _id removed in sample_validation_to_mongo.py
                    isolates_badqc_findone = self.isolates_badqc_collection.find_one({"_id": self.technical_id, "validation": None})
                    if isolates_badqc_findone:
                        # unvalidated badqc isolates are taken care of in the _new_resequencing_arrival function
                        self._new_resequencing_arrival(new_records, dict(isolates_badqc_findone), self.isolates_badqc_collection)
                    else:
                        self._new_isolate_wrapper(new_records)
            elif self.results_type == 'badqc_validated':
                sample_doc = self.isolates_badqc_collection.find_one({"_id": self.technical_id})
                new_records = sample_doc['results']
                self.validation = self.subvaldict
                self.fastafilepath = sample_doc['fasta_path']
                self.vcffilepath = sample_doc['vcf_path']
                self._new_isolate_wrapper(new_records)
            elif self.results_type == "reanalysis" or self.results_type == 'resequencing_validated':
                try:
                    current_results_document = \
                        self.mongoquerying.query_docs_by_ids(self.isolates_collection, [self.technical_id])[0]
                except Exception as exceptionmessage:
                    self._send_email(
                        f"{Path(__file__).name} fail on host {socket.gethostname()}: This reanalysis technical id ({self.technical_id}) is not present in the isolates collections",
                        f"{exceptionmessage}\n{traceback.format_exc()}")
                    raise Exception(
                        f"{Path(__file__).name} fail on host {socket.gethostname()}: This reanalysis technical id ({self.technical_id}) is not present in the isolates collections")
                if self.results_type == "reanalysis":
                    new_results_handle = json.load(open(self.jsonfilepath, 'r'))
                elif self.results_type == 'resequencing_validated':
                    new_results_handle = self.isolates_resequencing_collection.find_one({"_id": self.technical_id})
                    self.validation = self.subvaldict

                self._new_reanalysis_wrapper(current_results_document, new_results_handle)

        except Exception as exceptionmessage:
            self._send_email(f"{Path(__file__).name} fail on host {socket.gethostname()}",
                        f"{exceptionmessage}\n{traceback.format_exc()}")
            raise Exception(f"{Path(__file__).name} fail on host {socket.gethostname()}: {exceptionmessage}\n{traceback.format_exc()}")

    def _new_isolate_wrapper(self, new_records: dict) -> None:
        """
        Handles and inserts new isolates, whether that be actual new isolates or validated bad samples
        :param new_records: results dictionary that is modified and inserted
        :return:
        """
        new_records["isolates_id"] = self.technical_id
        sample_quality = 'good'
        if self.results_type == 'new_isolate':
            try:
                for qc_type in new_records['qc']:
                    for key in new_records['qc'][qc_type]:
                        if key.endswith('status') and new_records['qc'][qc_type][key] == 'Failed':
                            sample_quality = 'bad'
            except KeyError:
                self._send_email(
                    f"{Path(__file__).name}: mongo upload fail in {self.isolates_collection.database.name} on host {socket.gethostname()}",
                    f"No qc values found in the given results\n{traceback.format_exc()}")
                raise KeyError('No qc values found in the given results')
        if sample_quality == 'good':
            new_records = find_hashes_in_results_and_add_to_collection(new_records, self.mongoinit, self.config_data,
                                                                   self.species, self.results_type)
            _write_document(self.isolates_collection,
                            _new_isolate(self.technical_id, str(self.reportdirectorypath), str(self.vcffilepath),
                                         str(self.fastafilepath), new_records))
            logging.info(f"Wrote new isolate {self.technical_id} and its result to {self.species} database")
            if 'cgmlst' in new_records:
                clustering_input = self.mongoquerying.query_typing_results_by_technicalids_and_scheme(
                    self.isolates_collection,
                    scheme="cgmlst",
                    technicalids=[self.technical_id])
                custom_clustering = MongoCustomClustering(clustering_input[0], clustering_input[1], self.species)
                logging.info(f"Running the clustering for the isolate {self.technical_id}")
                sp_thresholds = f"clustering_thresholds_{self.species}"
                sequence_type = custom_clustering.run_custom_clustering(self.st_collection,
                                                                        self.cluster_membership_collection,
                                                                        self.cluster_merging_collection,
                                                                        CLUSTERING_CONFIG[sp_thresholds])
                self.isolates_collection.with_options(write_concern=WriteConcern(w="majority")).find_one_and_update(
                    {"_id": new_records["isolates_id"]}, {"$set": {"results.cgST": sequence_type}})
            if self.results_type == 'badqc_validated':
                self.isolates_collection.with_options(write_concern=WriteConcern(w="majority")).find_one_and_update(
                    {"_id": new_records["isolates_id"]}, {'$set': {'validation': self.validation}})
                self.isolates_badqc_collection.delete_one({'_id': new_records["isolates_id"]})
        else:
            _write_document(self.isolates_badqc_collection,
                            _new_isolate(self.technical_id, str(self.reportdirectorypath), str(self.vcffilepath),
                                         str(self.fastafilepath), new_records))
            logging.warning(
                f"New isolate {self.technical_id} failed quality control for one or more checks. It's results were written to the 'isolates_badqc' collection in the {self.species} database")

    def _new_resequencing_arrival(self, new_records: Dict[str, Union[str, object]], document_original: Dict[str, Union[str, object]],
                                  collection_in: pymongo.collection.Collection) -> None:
        """
        After an id is found in either isolates or isolates_badqc; this workflow will determine if it really is a resequencing, and if so insert it into isolates_resequencing
        :param new_records: results dictionary that is modified and inserted
        :return:
        """
        # https://git.sciensano.be/bioit/BIGSdb/src/d2a261056221056e56df6aa584563454f6bfec3a/lib/BIGSdb/SubmitPage.pm#L2800
        # 2022-12-20 Check whether resequencing; if resequencing; fasta md5sum should be different from original one. debating whether to store md5 in mongo or not
        # resequencings should be rare so we can afford multiple finds
        md5_original = hashlib.md5(open(Path(document_original['fasta_path']), 'r').read().encode()).hexdigest()
        md5_new = hashlib.md5(open(Path(self.fastafilepath), 'r').read().encode()).hexdigest()
        if md5_original != md5_new:
            # this is an actual resequencing because the fastafilepath is different

            if collection_in == self.isolates_badqc_collection:
                self._send_email(
                    f"{Path(__file__).name} fail on host {socket.gethostname()}",
                    f"WARNING: a resequencing for sample {self.technical_id} was submitted to the isolates_resequencing while the sample is present in the isolates_badqc collection and has not yet been validated, validate the bad qc in bigs before trying to reupload this resequencing.")
                raise Exception(
                    f"WARNING: a resequencing for sample {self.technical_id} was submitted to the isolates_resequencing while the sample is present in the isolates_badqc collection and has not yet been validated, validate the bad qc in bigs before trying to reupload this resequencing.")
            previous_resequencings = list(
                self.isolates_resequencing_collection.find({'results.isolates_id': self.technical_id},
                                                      {'_id': 1, 'fasta_path': 1}))
            # new_resequencing = True
            if previous_resequencings != []:
                self._send_email(
                    f"{Path(__file__).name} fail on host {socket.gethostname()}",
                    f"WARNING: a resequencing for sample {self.technical_id} was submitted to the isolates_resequencing while one or more resequencings were already present: '{previous_resequencings}' in {self.isolates_resequencing_collection.database.name} on host {socket.gethostname()}, validate the original resequencing in bigs before uploading new resequencings.")
                raise Exception(f"WARNING: a resequencing for sample {self.technical_id} was submitted to the isolates_resequencing while one or more resequencings were already present: '{previous_resequencings}' in {self.isolates_resequencing_collection.database.name} on host {socket.gethostname()}, validate the original resequencing in bigs before uploading new resequencings.")
            # The commented code below was in case multiple resequencings were allowed
            #     # check whether fasta is different from existing previous resequencings.
            #     for projection in previous_resequencings:
            #         if hashlib.md5(open(Path(projection['fasta_path']), 'r').read().encode()).hexdigest() == md5_new:
            #             new_resequencing = False
            #     if new_resequencing is True:
            #         # Send a warning because we are not expecting multiple resequencings for the same same sample
            #         self._send_email(
            #             f"{Path(__file__).name} fail on host {socket.gethostname()}",
            #             f"WARNING: a resequencing for sample {self.technical_id} was written to the isolates_resequencing while one or more resequencings were already present: '{previous_resequencings}' in {self.isolates_resequencing_collection.database.name} on host {socket.gethostname()}")
            # if new_resequencing is True:
            #     # Writing document with auto generated id to avoid having multiple resequencings with same name (pop _id key from new isolate dict)
            #     _write_document(self.isolates_resequencing_collection,
            #                     _new_isolate(self.technical_id, str(self.reportdirectorypath), str(self.vcffilepath),
            #                                  str(self.fastafilepath), new_records).pop('_id'))
            #     sys.exit()
            # else:
            #     self._send_email(
            #         f"{Path(__file__).name} fail on host {socket.gethostname()}",
            #         f"This technical id is already present in the isolates collection\n{traceback.format_exc()}")
            #     raise Exception(
            #         f"The technical id '{self.technical_id}' is already present in the isolates or isolates badqc collection")
            else:
                new_records["isolates_id"] = self.technical_id
                _write_document(self.isolates_resequencing_collection,
                                _new_isolate(self.technical_id, str(self.reportdirectorypath), str(self.vcffilepath),
                                             str(self.fastafilepath), new_records))

    def _new_reanalysis_wrapper(self, current_results_document: Dict[str, Union[str, object]], new_results_document: Dict[str, Union[str, object]]) -> None:
        """        
        :param current_results_document: the current results document dict in the Mongo collection before applying the reanalysis
        :param new_results_document: the new results document dict, under results for reanalysis, all for resequencing
        :return: 
        """
        if self.results_type == "reanalysis":
            new_results = new_results_document
        elif self.results_type == 'resequencing_validated':
            new_results = new_results_document['results']
        new_results_handle_hashes_replaced = find_hashes_in_results_and_add_to_collection(new_results,
                                                                                          self.mongoinit,
                                                                                          self.config_data,
                                                                                          self.species,
                                                                                          self.results_type)
        current_results = current_results_document['results']
        if new_results["analysis_date"] == current_results["analysis_date"]:
            self._send_email(f"{Path(__file__).name} fail on host {socket.gethostname()}",
                        f"This ({self.technical_id}) is not a reanalysis but the same results\n{traceback.format_exc()}")
            raise Exception(
                f"{Path(__file__).name} fail on host {socket.gethostname()}: This ({self.technical_id}) is not a reanalysis but the same results")
        elif _return_YMD_from_DMYhms(new_results["analysis_date"]) < _return_YMD_from_DMYhms(
                current_results["analysis_date"]):
            self._send_email(f"{Path(__file__).name} fail on host {socket.gethostname()}",
                        f"These ({self.technical_id})results seem to be older than the current results\n{traceback.format_exc()}")
            raise Exception(
                f"{Path(__file__).name} fail on host {socket.gethostname()}: These ({self.technical_id})results seem to be older than the current results")
        any_result_changed_new_old, unchanged_results_new_old, changed_results_new_old = \
            _check_if_results_changed(current_results, new_results)
        if current_results_document['previous_latest_results_document'] is not None:
            # Update current results
            older_results_document_with_pointers = \
                self.mongoquerying.query_docs_by_ids(self.old_isolateresults_collection, [
                    current_results_document['previous_latest_results_document']])[0]
            older_results = self.mongoquerying.query_old_results_and_replace_pointers(self.old_isolateresults_collection,
                                                                                      older_results_document_with_pointers)
            any_result_changed_old_older, unchanged_results_old_older, changed_results_old_older = _check_if_results_changed(
                older_results, current_results)
            for unchanged_assay in list(set(unchanged_results_old_older)):
                unchanged_assay_new_dict_with_pointer = {}
                # check if document already has a pointer with same results to previous document or make pointer to document
                if older_results_document_with_pointers[unchanged_assay].get('pointer'):
                    unchanged_assay_new_dict_with_pointer['pointer'] = \
                        older_results_document_with_pointers[unchanged_assay]['pointer']
                else:
                    unchanged_assay_new_dict_with_pointer['pointer'] = older_results['_id']
                # for metadata info, check if same or different, independently of if results are different in order to be able to track when an assay was last analyzed by which tools
                for info in ['analysis_date', 'informs_tools', 'informs_dbs']:
                    if current_results[unchanged_assay].get(info) and older_results[unchanged_assay][info] != \
                            current_results[unchanged_assay][info]:
                        unchanged_assay_new_dict_with_pointer[info] = current_results[unchanged_assay][info]
                current_results[unchanged_assay] = unchanged_assay_new_dict_with_pointer
    
        # Update new results
        new_results = prepend_string_dot_to_dict_keys(new_results_handle_hashes_replaced, 'results')
        new_results["results.isolates_id"] = self.technical_id
        new_results["results.results_version"] = current_results["results_version"] + 1
        if any_result_changed_new_old is True:
            new_results["results.changed_version"] = current_results["changed_version"] + 1
            logging.info(
                f"Writing new changed results and linked to isolate {self.technical_id} in {self.species}")
        else:
            logging.info(
                f"New results are not different from current results for {self.technical_id} in {self.species}, updating analysis dates and db versions.")
        if self.results_type == 'resequencing_validated':
            new_results['validation'] = self.validation
            report_dir_merging_cmd = ' '.join([
                "rsync -a",
                f"{new_results_document['report_directory']}/",
                f"{current_results_document['report_directory']}/"
            ])
            command = Command(report_dir_merging_cmd)
            # run the command
            command.run(current_results_document['report_directory'])
            logging.info(f"merging the report directories of original and resequencing for isolate '{self.technical_id}'")
            if command.returncode != 0:
                self._send_email(f"{Path(__file__).name} fail on host {socket.gethostname()}",
                                 f"Could not 'git' merge dir {new_results_document['report_directory']} into dir {current_results_document['report_directory']}")
                raise Exception(f"{Path(__file__).name} fail on host {socket.gethostname()}: Could not 'git' merge dir {new_results_document['report_directory']} into dir {current_results_document['report_directory']}")
            else:
                # Removing the temporary working dir and the remaining files that were not kept
                shutil.rmtree(new_results_document['report_directory'])
                logging.info(f"Resequecing directory {new_results_document['report_directory']} deletion for isolate '{self.technical_id}' completed")
            # Remove the isolate from the resequencing collection to allow for new resequencings
            self.isolates_resequencing_collection.delete_one({'_id': self.technical_id})
        self.isolates_collection.with_options(write_concern=WriteConcern(w="majority")).update_one(
            {"_id": self.technical_id}, {
                "$set": {**new_results,
                         "results.results_changed_since_last_version": any_result_changed_new_old,
                         "latest_analysis_date": _return_YMD_from_DMYhms(new_results["results.analysis_date"]),
                         "previous_latest_results_document": _write_document(self.old_isolateresults_collection,
                                                                             current_results)}})
        logging.info(f"Wrote new results and linked to isolate {self.technical_id} in {self.species}")
    
        if 'cgmlst' in changed_results_new_old:
            clustering_input = self.mongoquerying.query_typing_results_by_technicalids_and_scheme(
                self.isolates_collection,
                scheme="cgmlst",
                technicalids=[self.technical_id])
            custom_clustering = MongoCustomClustering(clustering_input[0], clustering_input[1],
                                                      self.species)
            logging.info(f"Running the clustering for the isolate {self.technical_id}")
            sp_thresholds = f"clustering_thresholds_{self.species}"
            sequence_type = custom_clustering.run_custom_clustering(self.st_collection,
                                                                    self.cluster_membership_collection,
                                                                    self.cluster_merging_collection,
                                                                    CLUSTERING_CONFIG[sp_thresholds])
            self.isolates_collection.with_options(write_concern=WriteConcern(w="majority")).find_one_and_update(
                {"_id": self.technical_id},
                {"$set": {"results.cgST": sequence_type}})

    def _send_email(self, subject: str, content: str) -> None:
        """
        Sends an email.
        :param subject: Mail subject
        :param content: Content of the message
        :return: None
        """
        if not self.dont_send_email:
            message = EmailMessage()
            message['Subject'] = subject
            message['From'] = self.config_data['mail']['from']
            message['To'] = self.config_data['mail']['to']
            message.set_content(content)
            with smtplib.SMTP(self.config_data['mail']['host']) as s:
                s.send_message(message)
        logging.info(content)

if __name__ == '__main__':

    # Parse config
    with open(MONGO_CONFIG, encoding='utf-8') as handle:
        config_data = yaml.safe_load(handle)

    # Parse arguments
    args = _parse_arguments(config_data['species'])
    parameter_compatibility_checks(args)

    # run main
    MainMongo(args.technical_id,
              args.species,
              args.results_type, 
              jsonfilepath=(args.jsonfilepath if args.jsonfilepath else None), 
              subvaldict=(args.subvaldict if args.subvaldict else None),
              reportdirectorypath=(args.reportdirectorypath if args.reportdirectorypath else None), 
              fastafilepath=(args.fastafilepath if args.fastafilepath else None), 
              vcffilepath=(args.vcffilepath if args.vcffilepath else None), 
              alternate_connection_string=(args.alternate_connection_string if args.alternate_connection_string else None),
              dont_send_email=(True if args.dont_send_email else False))
