species:
    listeria:
        lmod: camel_hera/0.1
        main_script: mainlisteriapipeline.py
        options: ['--species-confirmation', '--mlst', '--resfinder', '--ncbi-amr', '--virulencefinder', '--vfdb-core', '--plasmidfinder', '--typing-amr', '--cgmlst', '--metal-detergent', '--pcr-serogroup', '--typing-virulence']
    mycobacterium:
        lmod: camel_hera/0.1
        main_script: mainmycobacteriumpipeline.py
        options: ['--hsp65', '--snpit', '--amr', '--ncbi-16s', '--mlst', '--cgmlst', '--snp-lineage', '--pointfinder']
        options_without_vcf: ['--hsp65', '--ncbi-16s', '--mlst', '--cgmlst', '--pointfinder']
    neisseria:
        lmod: camel_hera/0.1
        main_script: mainneisseriapipeline.py
        options: ['--resfinder', '--ncbi-amr', '--mlst', '--rplf', '--bast', '--pora', '--porb', '--feta', '--fhbp', '--resistance-genes', '--vaccine-targets', '--cgmlst', '--serogroup']
    stec:
        lmod: camel_hera/0.1
        main_script: mainstecpipeline.py
        options: ['--resfinder', '--ncbi-amr', '--virulencefinder', '--serotype', '--plasmidfinder', '--mlst-pasteur', '--mlst-warwick', '--cgmlst', '--pointfinder']
    salmonella:
        lmod: camel_hera/0.1
        main_script: mainsalmonellapipeline.py
        options: ['--serotype', '--spifinder', '--mlst', '--cgmlst', '--resfinder', '--ncbi-amr', '--vfdb-core', '--plasmidfinder', '--pointfinder', '--abritamr']
    influenza_a:
        lmod: camel_hera/0.1
        main_script: mainviralconsensuspipeline.py
        options: [ '--species influenza_a', '--ref-genome-db /db/pipelines/viral_consensus/ref_mash_dbs/influenza_a-gisaid' ]
    influenza_b:
        lmod: camel_hera/0.1
        main_script: mainviralconsensuspipeline.py
        options: [ '--species influenza_b', '--ref-genome-db /db/pipelines/viral_consensus/ref_mash_dbs/influenza_b-gisaid' ]
    sars_cov_2:
        lmod: camel_hera/0.1
        main_script: mainviralconsensuspipeline.py
        options: [ '--species sars_cov_2', '--fasta-ref /db/pipelines/viral_consensus/ref_genomes/sars_cov_2-Wuhan-Hu-1.fasta' ]

mongodb:
    lmod: bioit_mongodb/0.1
    main_script: mainmongo.py
    report_script: html_update_merger.py

failsafe:
  flag_dir: /scratch/temp/flags
  flag_append: reanalysis_start_flag

reference_assembly_size:
    listeria: 2986663
    mycobacterium: 4485135
    neisseria: 2188343
    stec: 5577201
    salmonella: 4926939
    influenza_a: 14340  # no reference genome
    influenza_b: 14475 # no reference genome
    sars_cov_2: 30427

threads_per_job: 1