allowed_missing_data_proportion: 0.10
clustering_thresholds_listeria: [4,7]  # threshold ECDC 4= 'core cluster', 7= 'extended cluster'
clustering_thresholds_mycobacterium: [5]
clustering_thresholds_neisseria: [5]
clustering_thresholds_salmonella: [5]
clustering_thresholds_stec: [5]
