#CONNECTION_STRING_BASE: mongodb+srv://mikelchtermans:YMFOH4BLF1U79dDk@hera-bioit-trial.vajezh0.mongodb.net
CONNECTION_STRING_BASE: mongodb://admin:8T1r7nQwXnMoP3A9ubsu@bioit-mongo-d01:27017,bioit-mongo-d02:27017,bioit-mongo-d03:27017/?replicaSet=bioit-HERA&authSource=admin

mail:
    from: bioit-dev1@wiv-isp.be
    to:  benoit.bergkpinto@sciensano.be, michael.kelchtermans@sciensano.be
    host: smtp.wiv-isp.be

species:
    - listeria
    - mycobacterium
    - neisseria
    - stec
    - salmonella

dtap: to_be_replaced_by_ansible

collections:
    - isolates
    - old_isolate_results
    - isolates_badqc
    - sequence_types
    - new_allele_hashes
    - cluster_membership
    - update_metadata
    - isolates_resequencing

module_name:
    - mongo_bigs_dbs/0.1

temp_dir: /scratch/temp
