mail:
    from: BIGSdb internal HERA
    to: Michael or Ann-Stephan
    host: bioit-mailhog.sciensano.be:1025

failsafe:
  flag_dir: /scratch/temp/flags
  flag_append: bigsupload_start_flag

postgresql_apache_pass: to_be_replaced_by_ansible

species:
  listeria:
    typing_schemes:
      listeria_mlst:
        dirdb: /db/sequence_typing/listeria/mlst
        tsvname: mlst
        scheme_fields: # the first element in the fields list should be an integer/primary_key
          - ST
          - CC
          - Lineage
        schemename_bigsdb: MLST
      listeria_cgmlst:
        dirdb: /db/sequence_typing/listeria/cgmlst
        tsvname: cgmlst
        schemename_bigsdb: cgMLST
      listeria_serogroup:
        dirdb: /db/sequence_typing/listeria/serogroup
        tsvname: pcr_serogroup
        scheme_fields:
          - profile_id
          - serogroup
        schemename_bigsdb: PCR serogroup
      listeria_metal_detergent_resistance:
        dirdb: /db/sequence_typing/listeria/metal_detergent_resistance
        tsvname: metal_detergent
        schemename_bigsdb: Metal and detergent resistance
      listeria_typing_virulence:
        dirdb: /db/sequence_typing/listeria/virulence
        tsvname: typing_virulence
        schemename_bigsdb: Virulence
      listeria_antibiotic_resistance:
        dirdb: /db/sequence_typing/listeria/antibiotic_resistance
        tsvname: typing_amr
        schemename_bigsdb: Antibiotic resistance
      listeria_species_confirmation:
        dirdb: /db/sequence_typing/listeria/species_confirmation
        tsvname: species_confirmation
        schemename_bigsdb: Species confirmation
    genedetection_schemes:
      listeria_ndaro:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        tsvname: hits_ncbi_amr
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes (NDARO)
      listeria_resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        tsvname: hits_resfinder
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
      listeria_virulencefinder:
        clusteredfasta: /db/gene_detection/VirulenceFinder-Listeria/virulencefinder-listeria-clustered_80.fasta
        metadatafile: /db/gene_detection/VirulenceFinder-Listeria/mapping_full.json
        tsvname: hits_virulencefinder
        schemename_bigsdb: VirulenceFinder_Listeria
        schemename_html: VirulenceFinder - <i>Listeria</i>
      listeria_vfdbcore:
        clusteredfasta: /db/gene_detection/VFDB_core/vfdb_core-clustered_80.fasta
        metadatafile: /db/gene_detection/VFDB_core/mapping_full.json
        tsvname: hits_vfdb_core
        schemename_bigsdb: VFDB_core
        schemename_html: Virulence Factor DB - Core
      listeria_plasmidfinder:
        clusteredfasta: /db/gene_detection/PlasmidFinder-gram_positive/plasmidfinder-gram_positive-clustered_80.fasta
        metadatafile: /db/gene_detection/PlasmidFinder-gram_positive/mapping_full.json
        tsvname: hits_plasmidfinder
        schemename_bigsdb: PlasmidFinder_grampositive
        schemename_html: PlasmidFinder - Gram positive
    seqdefdb: bigsdb_listeria_seqdef
    isolatesdb: bigsdb_listeria_isolates
  mycobacterium:
    typing_schemes:
      mycobacterium_mlst:
        dirdb: /db/sequence_typing/mycobacterium/mlst
        tsvname: mlst
        scheme_fields:
          - ST
        schemename_bigsdb: MLST
      mycobacterium_cgmlst:
        dirdb: /db/sequence_typing/mycobacterium/cgmlst
        tsvname: cgmlst
        schemename_bigsdb: cgMLST
      mycobacterium_spoligotyping:
        dirdb: ''
        tsvname: spoligotype_binary
      mycobacterium_51SNPassay:
        dirdb: ''
        tsvname: 51SNP
      mycobacterium_csbrd:
        dirdb: ''
        tsvname: ''
      mycobacterium_amrdetection:
        dirdb: ''
        tsvname: ''
      mycobacterium_hsp65:
        dirdb: ''
        tsvname: hits_hsp65
      mycobacterium_pointfinder:
        dirdb: ''
        tsvname: pointfinder_mutations
        schemename_html: PointFinder
      mycobacterium_ncbi16s:
        dirdb: ''
        tsvname: hits_ncbi_16s
    genedetection_schemes: null
    seqdefdb: bigsdb_mycobacterium_seqdef
    isolatesdb: bigsdb_mycobacterium_isolates
  neisseria:
    typing_schemes:
      neisseria_mlst:
        dirdb: /db/sequence_typing/neisseria/mlst
        tsvname: mlst
        scheme_fields:
          - ST
        schemename_bigsdb: MLST
      neisseria_cgmlst:
        dirdb: /db/sequence_typing/neisseria/cgmlst
        tsvname: cgmlst
        schemename_bigsdb: cgMLST
      neisseria_rplf:
        dirdb: /db/sequence_typing/neisseria/rplf
        tsvname: rplf
        scheme_fields:
          - rplF_id
          - genospecies
        schemename_bigsdb: rplF
      neisseria_bast:
        dirdb: /db/sequence_typing/neisseria/bast
        tsvname: bast
        scheme_fields:
          - BAST
          - MenDeVAR_Bexsero_reactivity
          - MenDeVAR_Trumenba_reactivity
        schemename_bigsdb: BAST
      neisseria_pora:
        dirdb: /db/sequence_typing/neisseria/pora
        tsvname: pora
        schemename_bigsdb: porA
      neisseria_porb:
        dirdb: /db/sequence_typing/neisseria/porb
        tsvname: porb
        schemename_bigsdb: porB
      neisseria_feta:
        dirdb: /db/sequence_typing/neisseria/feta
        tsvname: feta
        schemename_bigsdb: FetA
      neisseria_resistancegenes:
        dirdb: /db/sequence_typing/neisseria/resistance_genes
        tsvname: resistance_genes
        schemename_bigsdb: Antibiotic_resistance
      neisseria_vaccinetargets:
        dirdb: /db/sequence_typing/neisseria/vaccine_targets
        tsvname: vaccine_targets
        schemename_bigsdb: Vaccine_targets
      neisseria_fhbpnucl:
        dirdb: /db/sequence_typing/neisseria/fhbp
        tsvname: fhbp
        schemename_bigsdb: fHbp_nucl
      neisseria_fhbppept:
        dirdb: /db/sequence_typing/neisseria/fhbp
        tsvname: Fhbp
        schemename_bigsdb: fHbp_pept
    genedetection_schemes:
      neisseria_ndaro:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        tsvname: hits_ncbi_amr
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes (NDARO)
      neisseria_resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        tsvname: hits_resfinder
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
    seqdefdb: bigsdb_neisseria_seqdef
    isolatesdb: bigsdb_neisseria_isolates
  stec:
    typing_schemes:
      stec_mlst_warwick:
        dirdb: /db/sequence_typing/ecoli/mlst-warwick
        tsvname: mlst_warwick
        scheme_fields:
          - ST
        schemename_bigsdb: MLST_Warwick
      stec_mlst_pasteur:
        dirdb: /db/sequence_typing/ecoli/mlst-pasteur
        tsvname: mlst_pasteur
        scheme_fields:
          - ST
        schemename_bigsdb: MLST_Pasteur
      stec_cgmlst:
        dirdb: /db/sequence_typing/ecoli/cgmlst
        tsvname: cgmlst
        schemename_bigsdb: cgMLST
      stec_pointfinder:
        dirdb: ''
        tsvname: pointfinder_mutations
        schemename_html: PointFinder
      stec_serotype:
        dirdb: ''
        tsvname: serotype
    genedetection_schemes:
      stec_ndaro:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes (NDARO)
        tsvname: hits_ncbi_amr
      stec_resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
        tsvname: hits_resfinder
      stec_plasmidfinder:
        clusteredfasta: >-
          /db/gene_detection/PlasmidFinder-entero/plasmidfinder-entero-clustered_80.fasta
        metadatafile: /db/gene_detection/PlasmidFinder-entero/mapping_full.json
        schemename_bigsdb: PlasmidFinder_entero
        schemename_html: PlasmidFinder - Enterobacteriaceae
        tsvname: hits_plasmidfinder
      stec_virulencefinder_ecoli:
        clusteredfasta: >-
          /db/gene_detection/VirulenceFinder-Ecoli/virulencefinder-ecoli-clustered_80.fasta
        metadatafile: /db/gene_detection/VirulenceFinder-Ecoli/mapping_full.json
        schemename_bigsdb: VirulenceFinder_Ecoli
        schemename_html: VirulenceFinder - <i>E. coli</i>
        tsvname: hits_virulencefinder
      stec_virulencefinder_shiga:
        clusteredfasta: >-
          /db/gene_detection/VirulenceFinder-Shiga/virulencefinder-shiga-clustered_80.fasta
        metadatafile: /db/gene_detection/VirulenceFinder-Shiga/mapping_full.json
        schemename_bigsdb: VirulenceFinder_Shiga
        schemename_html: VirulenceFinder - Shiga-toxin genes
        tsvname: hits_virulencefinder_shiga
    seqdefdb: bigsdb_stec_seqdef
    isolatesdb: bigsdb_stec_isolates
  salmonella:
    typing_schemes:
      salmonella_mlst:
        dirdb: /db/sequence_typing/salmonella/mlst
        tsvname: mlst
        scheme_fields:
          - ST
        schemename_bigsdb: MLST
      salmonella_cgmlst:
        dirdb: /db/sequence_typing/salmonella/cgmlst
        tsvname: cgmlst
        schemename_bigsdb: cgMLST
      salmonella_pointfinder:
        dirdb: ''
        tsvname: pointfinder_mutations
        schemename_html: PointFinder
      salmonella_genotyphi:
        dirdb: ''
        tsvname: genotyphi
      salmonella_serotyping:
        dirdb: ''
        tsvname: serotyping
      salmonella_spifinder:
        dirdb: ''
        tsvname: spifinder
    genedetection_schemes:
      salmonella_ndaro:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        tsvname: hits_ncbi_amr
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes (NDARO)
      salmonella_resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        tsvname: hits_resfinder
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
      salmonella_vfdbcore:
        clusteredfasta: /db/gene_detection/VFDB_core/vfdb_core-clustered_80.fasta
        metadatafile: /db/gene_detection/VFDB_core/mapping_full.json
        tsvname: hits_vfdb_core
        schemename_bigsdb: VFDB_core
        schemename_html: Virulence Factor DB - Core
      salmonella_plasmidfinder:
        clusteredfasta: /db/gene_detection/PlasmidFinder-entero/plasmidfinder-entero-clustered_80.fasta
        metadatafile: /db/gene_detection/PlasmidFinder-entero/mapping_full.json
        tsvname: hits_plasmidfinder
        schemename_bigsdb: PlasmidFinder_entero
        schemename_html: plasmid
    seqdefdb: bigsdb_salmonella_seqdef
    isolatesdb: bigsdb_salmonella_isolates

species_json:
  listeria:
    typing_schemes:
      mlst:
        type: regular
      cgmlst:
        type: regular
      pcr_serogroup:
        type: regular
      metal_detergent:
        type: regular
      typing_virulence:
        type: regular
      typing_amr:
        type: regular
      species_confirmation:
        type: regular
    genedetection_schemes:
      ncbi_amr:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes
      resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
      virulencefinder:
        clusteredfasta: /db/gene_detection/VirulenceFinder-Listeria/virulencefinder-listeria-clustered_80.fasta
        metadatafile: /db/gene_detection/VirulenceFinder-Listeria/mapping_full.json
        schemename_bigsdb: VirulenceFinder_Listeria
        schemename_html: VirulenceFinder - <i>Listeria</i>
      vfdb_core:
        clusteredfasta: /db/gene_detection/VFDB_core/vfdb_core-clustered_80.fasta
        metadatafile: /db/gene_detection/VFDB_core/mapping_full.json
        schemename_bigsdb: VFDB_core
        schemename_html: Virulence Factor DB - Core
      plasmidfinder:
        clusteredfasta: /db/gene_detection/PlasmidFinder-gram_positive/plasmidfinder-gram_positive-clustered_80.fasta
        metadatafile: /db/gene_detection/PlasmidFinder-gram_positive/mapping_full.json
        schemename_bigsdb: PlasmidFinder_grampositive
        schemename_html: PlasmidFinder - Gram positive
  mycobacterium:
    typing_schemes:
      mlst:
        type: regular
      cgmlst:
        type: regular
      spoligotyping:
        type: irregular
      51SNP:
        type: irregular
      csb_rd:
        type: irregular
      amr_who:
        type: irregular
      hsp65:
        type: irregular
      pointfinder:
        type: irregular
        schemename_html: PointFinder
        schemename_bigsdb: Pointfinder
      ncbi_16s:
        type: irregular
    genedetection_schemes: null
  neisseria:
    typing_schemes:
      mlst:
        type: regular
      cgmlst:
        type: regular
      rplf:
        type: regular
      bast:
        type: regular
      pora:
        type: regular
      porb:
        type: regular
      feta:
        type: regular
      resistance_genes:
        type: regular
      vaccine_targets:
        type: regular
      fhbp:
        type: regular
    genedetection_schemes:
      ncbi_amr:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes
      resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
  stec:
    typing_schemes:
      mlst_warwick:
        type: regular
      mlst_pasteur:
        type: regular
      cgmlst:
        type: regular
      pointfinder:
        type: irregular
        schemename_html: PointFinder
        schemename_bigsdb: Pointfinder
      serotype:
        type: irregular
    genedetection_schemes:
      ncbi_amr:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes
      resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
      plasmidfinder:
        clusteredfasta: >-
          /db/gene_detection/PlasmidFinder-entero/plasmidfinder-entero-clustered_80.fasta
        metadatafile: /db/gene_detection/PlasmidFinder-entero/mapping_full.json
        schemename_bigsdb: PlasmidFinder_entero
        schemename_html: PlasmidFinder - Enterobacteriaceae
      virulencefinder:
        clusteredfasta: >-
          /db/gene_detection/VirulenceFinder-Ecoli/virulencefinder-ecoli-clustered_80.fasta
        metadatafile: /db/gene_detection/VirulenceFinder-Ecoli/mapping_full.json
        schemename_bigsdb: VirulenceFinder_Ecoli
        schemename_html: VirulenceFinder - <i>E. coli</i>
      virulencefinder_shiga:
        clusteredfasta: >-
          /db/gene_detection/VirulenceFinder-Shiga/virulencefinder-shiga-clustered_80.fasta
        metadatafile: /db/gene_detection/VirulenceFinder-Shiga/mapping_full.json
        schemename_bigsdb: VirulenceFinder_Shiga
        schemename_html: VirulenceFinder - Shiga-toxin genes
  salmonella:
    typing_schemes:
      mlst:
        type: regular
      cgmlst:
        type: regular
      pointfinder:
        type: irregular
        schemename_html: PointFinder
        schemename_bigsdb: Pointfinder
      genotyphi:
        type: irregular
      sistr:
        type: irregular
      seqsero2_kmer:
        type: irregular
      seqsero2_allele:
        type: irregular
      seqsero2_kmerread:
        type: irregular
      spifinder_fastq:
        type: irregular
      spifinder_fasta:
        type: irregular
      abritamr:
        type: irregular
    genedetection_schemes:
      ncbi_amr:
        clusteredfasta: /db/gene_detection/NCBI_AMR/ncbi_amr-clustered_80.fasta
        metadatafile: /db/gene_detection/NCBI_AMR/mapping_full.json
        schemename_bigsdb: NCBI_AMR
        schemename_html: NCBI AMR genes
      resfinder:
        clusteredfasta: /db/gene_detection/ResFinder/resfinder-clustered_80.fasta
        metadatafile: /db/gene_detection/ResFinder/mapping_full.json
        schemename_bigsdb: ResFinder
        schemename_html: ResFinder
      vfdb_core:
        clusteredfasta: /db/gene_detection/VFDB_core/vfdb_core-clustered_80.fasta
        metadatafile: /db/gene_detection/VFDB_core/mapping_full.json
        schemename_bigsdb: VFDB_core
        schemename_html: Virulence Factor DB - Core
      plasmidfinder:
        clusteredfasta: /db/gene_detection/PlasmidFinder-entero/plasmidfinder-entero-clustered_80.fasta
        metadatafile: /db/gene_detection/PlasmidFinder-entero/mapping_full.json
        schemename_bigsdb: PlasmidFinder_entero
        schemename_html: PlasmidFinder - Enterobacteriaceae

lab_metadata:
  neisseria:
    isolation_date: 'Isolation Date '
    year_of_isolation: 'Year of Isolation'
    month_of_isolation: 'Month of Isolation'
    day_of_isolation: 'Day of Isolation'
    human_sample: 'Human Sample'
    specimen: 'Specimen'
    patient_id: 'Patient ID'
    patient_birth_date: 'Patient BirthDate'
    patient_age: 'Patient Age'
    patient_age_group: 'Patient Age Group'
    patient_sex: 'Patient Sex'
    patient_zip: 'Patient Zip'
    province: 'Province'
    region: 'Region'
    latitude: 'Latitude'
    longitude: 'Longitude'
    hospitalisation: 'Hospitalisation'
    recently_stayed_abroad: 'Recently Stayed Abroad'
    country_1: 'Country 1'
    country_2: 'Country 2'
    serogroup_pheno: 'Serogroup'
    mic_azm: 'MIC Azm'
    mic_azm_1: 'MIC Azm I'
    mic_cox: 'MIC Cox'
    mic_cox_1: 'MIC Cox I'
    mic_chl: 'MIC Chl'
    mic_chl_1: 'MIC Chl I'
    mic_cip: 'MIC Cip'
    mic_cip_1: 'MIC Cip I'
    mic_pen: 'MIC Pen'
    mic_pen_1: 'MIC Pen I'
    mic_rif: 'MIC Rif'
    mic_rif_1: 'MIC Rif I'
    clinical_info: 'Clinical info'
    evolution: 'Evolution'
    case_type: 'Case Type '


