pathogens:
  salmonella:
    dcd_name: BIOIT_SLM
    dcd_code: HDBP0345
    dcd_version: 1.0.1-draft4
  listeria:
    dcd_name: BIOIT_LIST
    dcd_code: HDBP0335
    dcd_version: 1.0.1-draft3
  influenza:
    dcd_name: BIOIT_INFL
    dcd_code: HDBP0333
    dcd_version: 1.0.1-draft3

common:
  CD_HCO_NIHDI:
    dict_path:
      - technical_metadata
      - CD_HCO_NIHDI  # this value is not converted in the HERA_Azure code and should not be
  TX_PIPELINE_NAM:
    dict_path:
      - results
      - pipeline_name
  TX_PIPELINE_VER:
    dict_path:
      - results
      - pipeline_version
  TX_PIPELINE_HASH:
    dict_path:
      - results
      - pipeline_hash
#  DT_PIPELINE_ANAL:  # needs to be in “YYYY-MM-DDT00:00:00”  format; added to main code
#    dict_path:
#      - results
#      - analysis_date
  TX_BUSINESS_KEY:
    dict_path:
      - TX_BUSINESS_KEY
  TX_LAB_SAMPLE_VAL:
    dict_path:
      - _id

salmonella:
  TX_SEROTPE_WGS:
    dict_path:
      - results
      - sistr
      - sistr_serotype_consensus
  TX_MLST_ST:
    dict_path:
      - results
      - mlst
      - mlst-ST
  CD_ABRITAMR_AMP_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Ampicillin_Interpretation
    code_list: SRI
  CD_ABRITAMR_CEF_ESBL_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Cefotaxime (ESBL)_Interpretation
    code_list: SRI
  CD_ABRITAMR_CEF_AMPC_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Cefotaxime (AmpC)_Interpretation
    code_list: SRI
  CD_ABRITAMR_TETRACY_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Tetracycline_Interpretation
    code_list: SRI
  CD_ABRITAMR_GENTMC_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Gentamicin_Interpretation
    code_list: SRI
  CD_ABRITAMR_KANMC_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Kanamycin_Interpretation
    code_list: SRI
  CD_ABRITAMR_STREPMC_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Streptomycin_Interpretation
    code_list: SRI
  CD_ABRITAMR_SULFZL_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Sulfathiazole_Interpretation
    code_list: SRI
  CD_ABRITAMR_TRIMETH_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Trimethoprim_Interpretation
    code_list: SRI
  CD_ABRITAMR_TRIMS_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Trim-Sulpha_Interpretation
    code_list: SRI
  CD_ABRITAMR_CHLORP_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Chloramphenicol_Interpretation
    code_list: SRI
  CD_ABRITAMR_CIPR_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Ciprofloxacin_Interpretation
    code_list: SRI
  CD_ABRITAMR_MER_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Meropenem_Interpretation
    code_list: SRI
  CD_ABRITAMR_AZI_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Azithromycin_Interpretation
    code_list: SRI
  CD_ABRITAMR_AMNGLY_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Aminoglycosides (RMT)_Interpretation
    code_list: SRI
  CD_ABRITAMR_COL_SUSC:
    dict_path:
      - results
      - abritamr
      - abritamr_Colistin_Interpretation
    code_list: SRI
listeria:
  TX_MLST_ST:
    dict_path:
      - results
      - mlst
      - mlst-ST
  TX_MLST_CC:
    dict_path:
      - results
      - mlst
      - mlst-CC
  TX_MLST_LINEAGE:
    dict_path:
      - results
      - mlst
      - mlst-Lineage
  TX_PCR_SEROGR:
    dict_path:
      - results
      - pcr_serogroup
      - pcr_serogroup-serogroup

influenza:
  TX_GENTPE_TOOL_VER:
    dict_path:
      - results
      - nextclade
      - nextclade_tool_version
  TX_GENTPE_TPE:
    dict_path:
      - technical_metadata
      - data
      - Microorganism
    code_list: influenza_species
  TX_GENTPE_SUBTPE:
    dict_path:
      - results
      - nextclade
      - nextclade_detected_subtype
#  TX_GENTPE_SUBTPE_HEMAG:  # is dependent on influenza A, incorporated in main code
#    dict_path:
#      - results
#      - nextclade
#      - nextclade_detected_subtype
#  TX_GENTPE_SUBTPE_NEURAM:  # is dependent on influenza A, incorporated in main code
#    dict_path:
#      - results
#      - nextclade
#      - nextclade_detected_subtype
code_lists:
  SRI:
    Susceptible: 131196009
    Resistant: 30714006
    Intermediate: 11896004
    Unknown: 261665006
    '-': 261665006
  influenza_species:
    Influenza A virus (organism): A
    Influenza B virus (organism): B