TX_TTL_REGN_AUTHOR
TX_AUTHOR_GR
TX_AUTHOR
TX_COAUTHOR
TX_TTL_STDY
TX_PROG
TX_PROJ
TX_EVENT
TX_DCD
TX_BUSINESS_KEY
TX_TTL_PAT
CD_IDC_PAT_SYS
IDC_PAT: patient_id
DT_PAT_DOB: patient_birth_date
CD_PAT_SEX: patient_sex
CD_PAT_MULT_BIRTH
MS_PAT_MULT_BIRTH_ORD
CD_PAT_DEATH_INDICAT
DT_PAT_DOD
TX_TTL_PAT_NAM_INFO
TX_PAT_FIRST_NAM
TX_PAT_INIT
TX_PAT_GIVN_NAM
CD_PAT_NAM_USGE
TX_PAT_LAST_NAM
TX_PAT_PREFX
TX_PAT_PNR_LAST_NAM
TX_PAT_PNR_PREFX
TX_PAT_TTL
TX_TTL_PAT_ADR_INFO
TX_PAT_STREET
TX_PAT_HNR
TX_PAT_HNR_LTR
TX_PAT_HNR_ADD
CD_PAT_HNR_INDICATN
CD_PAT_PC: patient_zip
CD_PAT_PLC_RESDC
CD_PAT_MUNICP
CD_CNTRY: country
TX_PAT_ADD_INFO
CD_PAT_ADR_TPE
CD_PAT_ADR_USE
TX_TTL_PAT_CONT_INFO
CD_PAT_CONT_TPE
TX_PAT_CONT_VAL
CD_PAT_CONT_USE
TX_PAT_CONT_CMNT
CD_ORIGL_ID_UNK
TX_ORIGL_ID
TX_TTL_LAB_TEST_RSLT
TX_TTL_REQE_HP
CD_REQE_HPIN_SYS
CD_REQE_HPIN_VAL
CD_REQE_SPLTY
CD_REQE_SEX
CD_REQE_HP_ROLE
TX_TTL_REQE_HP_NAM_INFO
TX_REQE_HP_FIRST_NAM
TX_REQE_HP_INIT
TX_REQE_HP_GIVN_NAM
CD_REQE_HP_NAM_USGE
TX_REQE_HP_LAST_NAME
TX_REQE_HP_PREFX
TX_REQE_HP_PNR_LAST_NAM
TX_REQE_HP_PNR_PREFX
TX_REQE_HP_TTL
TX_TTL_REQE_HP_ADR_INFO
TX_REQE_HP_STREET
TX_REQE_HP_HNR
TX_REQE_HP_HNR_LTR
TX_REQE_HP_HNR_ADD
CD_REQE_HP_HNR_INDICATN
CD_REQE_HP_PC
CD_REQE_HP_PLC_RESDC
CD_REQE_HP_MUNICP
CD_REQE_HP_CNTRY
TX_REQE_HP_ADR_ADD_INFO
CD_REQE_HP_ADR_TPE
CD_REQE_HP_ADR_USE
TX_TTL_REQE_HP_CONT_INFO
CD_REQE_HP_CONT_TPE
TX_REQE_HP_CONT_VAL
CD_REQE_HP_CONT_USE
TX_REQE_HP_CONT_CMNT
TX_TTL_REQE_HCO
CD_REQE_HCO_SYS
CD_REQE_HCO_VAL
TX_REQE_HCO_NAM
CD_REQE_HCO_SPLTY
CD_REQE_HCO_TPE
TX_REQE_HCO_LOC_NAM
CD_REQE_HCO_LOC_NR
CD_REQE_HCO_DEPT_NR
TX_TTL_REQE_HCO_CONT_INFO
CD_REQE_HCO_CONT_TPE
TX_REQE_HCO_CONT_VAL
CD_REQE_HCO_CONT_USE
TX_REQE_HCO_CONT_CMNT
TX_TTL_REQE_HCO_ADR_INFO
TX_REQE_HCO_STREET
TX_REQE_HCO_HNR
TX_REQE_HCO_HNR_LTR
TX_REQE_HCO_HNR_ADD
CD_REQE_HCO_HNR_INDICATN
CD_REQE_HCO_PC
CD_REQE_HCO_PLC_RESDC
CD_REQE_HCO_MUNICP
CD_REQE_HCO_CNTRY
TX_REQE_HCO_ADR_ADD_INFO
CD_REQE_HCO_ADR_TPE
CD_REQE_HCO_ADR_USE
TX_TTL_PERFMR_HP
CD_HPIN_PERFMR_SYS
CD_HPIN_PERFMR_VAL
CD_PERFMR_HP_SPLTY
CD_PERFMR_HP_SEX
CD_PERFMR_HP_ROLE
TX_TTL_PERFMR_HP_NAM_INFO
TX_PERFMR_HP_FIRST_NAM
TX_PERFMR_HP_INIT
TX_PERFMR_HP_GIVN_NAM
CD_PERFMR_HP_NAM_USGE
TX_PERFMR_HP_LAST_NAM
TX_PERFMR_HP_PREFX
TX_PERFMR_HP_PNR_LAST_NAME
TX_PERFMR_HP_PNR_PREFX
TX_PERFMR_HP_TTL
TX_TTL_PERFMR_HP_ADR_INFO
TX_PERFMR_HP_STREET
TX_PERFMR_HP_HNR
TX_PERFMR_HP_HNR_LTR
TX_PERFMR_HP_HNR_ADD
CD_PERFMR_HP_HNR_INDICATN
CD_PERFMR_HP_PC
CD_PERFMR_HP_PLC_RESDC
CD_PERFMR_HP_MUNICP
CD_PERFMR_HP_CNTRY
TX_PERFMR_HP_ADR_ADD_INFO
CD_PERFMR_HP_ADR_TPE
CD_PERFMR_HP_ADR_USE
TX_TTL_PERFMR_HP_CONT_INFO
CD_PERFMR_HP_CONT_INFO_TPE
TX_PERFMR_HP_CONT_VAL
CD_PERFMR_HP_CONT_USE
TX_PERFMR_HP_CONT_CMNT
TX_TTL_PERFMR_HCO
CD_PERFMR_HCO_SYS
CD_PERFMR_HCO_VAL
TX_PERFMR_HCO_NAM
CD_PERFMR_HCO_SPLTY
CD_PERFMR_HCO_TPE
TX_PERFMR_LOC_NAM
CD_PERFMR_LOC_NR
CD_PERFMR_DEPT_NR
TX_TTL_PERFMR_HCO_CONT_INFO
CD_PERFMR_HCO_CONT_TPE
TX_PERFMR_HCO_CONT_VAL
CD_PERFMR_HCO_CONT_USE
TX_PERFMR_HCO_CONT_CMNT
TX_TTL_PERFMR_HCO_ADR_INFO
TX_PERFMR_HCO_STREET
TX_PERFMR_HCO_HNR
TX_PERFMR_HCO_HNR_LTR
TX_PERFMR_HCO_HNR_ADD
CD_PERFMR_HCO_HNR_INDICATN
CD_PERFMR_HCO_PC
CD_PERFMR_HCO_PLC_RESDC
CD_PERFMR_HCO_MUNICP
CD_PERFMR_HCO_CNTRY
TX_PERFMR_HCO_ADR_ADD_INFO
CD_PERFMR_HCO_ADR_TPE
CD_PERFMR_HCO_ADR_USE
TX_TTL_SPECIM
CD_LAB_SAMPLE_SYS
TX_LAB_SAMPLE_VAL: specimen
TX_LAB_SAMPLE_EXT
CD_LAB_CONT_TPE
CD_LAB_SAMPLE_ORIGIN
CD_LAB_LTRLTY
CD_LAB_LOC
CD_LAB_PATHOGEN: serovar_final
MS_LAB_COLLCN_VOL
DT_LAB_START
DT_LAB_END
MS_LAB_DURA
DT_LAB_COLLCN
DT_LAB_RECEIVD
CD_LAB_COLLCN_METH
CD_LAB_MORPH
CD_LAB_SPECIM_SRC
TX_LAB_CMNT_SPECIM: comment
TX_TTL_LAB_TEST
CD_LAB_TEST_CODE
CD_LAB_TEST_METH
DT_LAB_TEST
TX_LAB_TEST_RSLT_ID
CD_LAB_TEST_RSLT_QL
TX_LAB_TEST_RSLT_TXT
MS_LAB_TEST_RSLT_QN_VAL
CD_LAB_TEST_RSLT_QN_UNIT
CD_LAB_TEST_RSLT_STA
TX_LAB_RR_UL
MS_LAB_RR_UL_VAL
CD_LAB_RR_UL_UNIT
TX_LAB_RR_LL
MS_LAB_RR_LL_VAL
CD_LAB_RR_LL_UNIT
CD_LAB_INTRPR_METH
CD_LAB_RSLT_FLAG
TX_LAB_RSLT_INTRPR
CD_LAB_PNL_BATT
CD_LAB_RSLT_STA
TX_LAB_CMNT_TEST_RSLT
CD_LAB_RESLT_TPE
CD_STATUS_REC
CD_DATA_SRC
TX_LANG
TX_REG_NAM
CD_HOSPZ: hospitalisation
CD_EVOL: outcome
CD_PROB_NAM
CD_ANTBIO: antibiotic_therapy
CD_ANTBIO_SPECIF: antibiotic
CD_EPILINK: link
CD_IMPRTD
CD_INFCT_CNRTY: country_1
CD_STATUS_REC
CD_DATA_SRC
TX_LANG
TX_REG_NAM
