hostname_get_nominative_from_ODS: hera-dc.healthdata.be
port_get_nominative_from_ODS: 2222  # Default SFTP port
username_get_nominative_from_ODS: to_be_replaced_by_ansible
password_get_nominative_from_ODS: to_be_replaced_by_ansible
hostname_send_mapping_table_to_ODS: hera-dc.healthdata.be
port_send_mapping_table_to_ODS: 2222  # Default SFTP port
username_send_mapping_table_to_ODS: to_be_replaced_by_ansible
password_send_mapping_table_to_ODS: to_be_replaced_by_ansible