INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id)
            VALUES(1, 'MLST', 'MLST scheme downloaded and updated weekly from Enterobase.', 't', 1, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id)
            VALUES(2, 'cgMLST', 'cgMLST scheme downloaded and updated weekly from Enterobase.', 't', 2, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 2);
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field)
            VALUES(1, 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't');
--reports fields
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator)
                VALUES('html', 'text', 'galaxy report', 'galaxy html report', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator)
                VALUES('tsv', 'text', 'galaxy report', 'galaxy tsv report', 't', 't', (SELECT CURRENT_DATE), 1);
-- AMR
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('NCBI_AMR', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('ResFinder', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(3, 'NCBI_AMR', 'NDARO AMR database', 't', 3, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 3);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(4, 'ResFinder', 'ResFinder database', 't', 4, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 4);
-- Other gene detection
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('VFDB_core', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('PlasmidFinder_entero', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(5, 'VFDB_core', 'VirulenceFactor core database', 't', 5, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 5);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(6, 'PlasmidFinder_entero', 'PlasmidFinder enterobacteriaceae', 't', 6, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 6);
-- counstraints for copying tables
CREATE TABLE eav_text_hidden AS (SELECT * FROM eav_text) WITH NO DATA;
ALTER TABLE eav_text_hidden ADD PRIMARY KEY(isolate_id, field);
ALTER TABLE eav_text_hidden ADD CONSTRAINT eavt_field FOREIGN KEY (field) REFERENCES eav_fields(field) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE eav_text_hidden ADD CONSTRAINT eavt_isolate FOREIGN KEY (isolate_id) REFERENCES isolates(id) ON UPDATE CASCADE ON DELETE CASCADE;
GRANT SELECT, INSERT, UPDATE, DELETE ON eav_text_hidden TO apache;
-- hash not implemented yet
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('hash_fastq_md5_forward', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('hash_fastq_md5_reverse', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
--spifinder_fastq
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(7, 'spifinder_fastq', 'SPIFinder carried out on fastq with kma', 't', 7, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 7);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-3','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-3', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-3&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-4','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-4', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-4&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-5','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-5', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-5&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_HPI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_HPI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_HPI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SESS-LEE','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SESS-LEE', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SESS-LEE&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SGI1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SGI1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SGI1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SGI2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SGI2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SGI2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-10','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-10', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-10&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-11','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-11', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-11&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-12','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-12', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-12&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-13','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-13', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-13&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-14','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-14', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-14&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-6','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-6', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-6&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-7','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-7', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-7&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-8','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-8', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-8&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_SPI-9','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_SPI-9', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_SPI-9&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_C63PI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_C63PI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_C63PI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_CS54_ISLAND','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_CS54_ISLAND', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_CS54_ISLAND&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTQ_NOT_NAMED','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTQ_NOT_NAMED', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTQ_NOT_NAMED&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-1', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-2', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-3', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-4', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-5', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_HPI', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SESS-LEE', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SGI1', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SGI2', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-10', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-11', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-12', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-13', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-14', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-6', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-7', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-8', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_SPI-9', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_C63PI', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_CS54_ISLAND', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fastq'), 'SPIFINDER_FASTQ_NOT_NAMED', 1, (SELECT CURRENT_DATE));

--spifinder_fasta
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(8, 'spifinder_fasta', 'SPIFinder carried out on fasta with blast', 't', 8, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 8);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-3','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-3', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-3&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-4','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-4', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-4&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-5','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-5', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-5&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_HPI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_HPI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_HPI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SESS-LEE','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SESS-LEE', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SESS-LEE&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SGI1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SGI1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SGI1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SGI2','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SGI2', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SGI2&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-10','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-10', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-10&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-11','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-11', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-11&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-12','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-12', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-12&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-13','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-13', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-13&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-14','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-14', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-14&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-6','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-6', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-6&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-7','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-7', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-7&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-8','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-8', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-8&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_SPI-9','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_SPI-9', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_SPI-9&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_C63PI','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_C63PI', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_C63PI&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_CS54_ISLAND','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_CS54_ISLAND', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_CS54_ISLAND&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SPIFINDER_FASTA_NOT_NAMED','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SPIFINDER_FASTA_NOT_NAMED', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SPIFINDER_FASTA_NOT_NAMED&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-1', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-2', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-3', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-4', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-5', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_HPI', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SESS-LEE', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SGI1', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SGI2', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-10', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-11', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-12', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-13', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-14', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-6', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-7', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-8', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_SPI-9', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_C63PI', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_CS54_ISLAND', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='spifinder_fasta'), 'SPIFINDER_FASTA_NOT_NAMED', 1, (SELECT CURRENT_DATE));
--pointfinder
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('pointfinder_hits', 'text', 'pointfinder', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(9, 'Pointfinder', 'pointfinder mutation giving resistance to antibiotic', 't', 9, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 9);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_SPECTINOMYCIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_SPECTINOMYCIN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_SPECTINOMYCIN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_CIPROFLOXACIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_CIPROFLOXACIN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_CIPROFLOXACIN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_COLISTIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_COLISTIN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_COLISTIN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_NALIDIXIC_ACID','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_NALIDIXIC ACID', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_NALIDIXIC_ACID&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_UNKNOWN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_UNKNOWN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_UNKNOWN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_SPECTINOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CIPROFLOXACIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_COLISTIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_NALIDIXIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_UNKNOWN', 1, (SELECT CURRENT_DATE));
--genotyphi
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_ESBLs_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_IncFIAHI1_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_IncHI1A_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_IncHI1BR27_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_IncY_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_aminoglycosides_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_azithromycin_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_beta-lactamases_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_macrolides_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_pST_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_phenicols_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_quinolones_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_sulfonamides_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_tetracyclines_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_trimethoprims_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_z66_susceptibility', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(10, 'Genotyphi', 'Genotyphi antibiotic susceptibility variants and genes', 't', 10, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 10);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_ESBLS','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_ESBLS', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_ESBLS&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_INCFIAHI1','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_INCFIAHI1', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_INCFIAHI1&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_INCHI1A','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_INCHI1A', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_INCHI1A&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_INCHI1BR27','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_INCHI1BR27', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_INCHI1BR27&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_INCY','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_INCY', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_INCY&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_AMINOGLYCOSIDES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_AMINOGLYCOSIDES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_AMINOGLYCOSIDES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_AZITHROMYCIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_AZITHROMYCIN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_AZITHROMYCIN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_BETA-LACTAMASES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_BETA-LACTAMASES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_BETA-LACTAMASES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_MACROLIDES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_MACROLIDES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_MACROLIDES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_PST','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_PST', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_PST&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_PHENICOLS','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_PHENICOLS', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_PHENICOLS&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_QUINOLONES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_QUINOLONES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_QUINOLONES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_SULFONAMIDES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_SULFONAMIDES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_SULFONAMIDES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_TETRACYCLINES','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_TETRACYCLINES', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_TETRACYCLINES&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_TRIMETHOPRIMS','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_TRIMETHOPRIMS', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_TRIMETHOPRIMS&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('GENOTYPHI_Z66','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'GENOTYPHI_Z66', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=GENOTYPHI_Z66&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_ESBLS', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_INCFIAHI1', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_INCHI1A', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_INCHI1BR27', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_INCY', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_AMINOGLYCOSIDES', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_AZITHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_BETA-LACTAMASES', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_MACROLIDES', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_PST', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_PHENICOLS', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_QUINOLONES', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_SULFONAMIDES', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_TETRACYCLINES', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_TRIMETHOPRIMS', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Genotyphi'), 'GENOTYPHI_Z66', 1, (SELECT CURRENT_DATE));
--serotyping
--sistr
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(11, 'sistr', 'SISTR ', 't', 11, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 11);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SISTR_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SISTR_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SISTR_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SISTR_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SISTR_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SISTR_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SISTR_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SISTR_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SISTR_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='sistr'), 'SISTR_O_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='sistr'), 'SISTR_H1_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='sistr'), 'SISTR_H2_ANTIGEN', 1, (SELECT CURRENT_DATE));
--seqsero2 allele
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(12, 'seqsero2_allele', 'SeqSero2 allele ', 't', 12, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 12);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_ALLELE_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_ALLELE_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_ALLELE_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_ALLELE_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_ALLELE_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_ALLELE_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_ALLELE_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_ALLELE_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_ALLELE_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_allele'), 'SEQSERO2_ALLELE_O_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_allele'), 'SEQSERO2_ALLELE_H1_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_allele'), 'SEQSERO2_ALLELE_H2_ANTIGEN', 1, (SELECT CURRENT_DATE));
--seqsero2 kmer
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(13, 'seqsero2_kmer', 'SeqSero2 kmer ', 't',13, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 13);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMER_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMER_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMER_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMER_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMER_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMER_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMER_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMER_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMER_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmer'), 'SEQSERO2_KMER_O_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmer'), 'SEQSERO2_KMER_H1_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmer'), 'SEQSERO2_KMER_H2_ANTIGEN', 1, (SELECT CURRENT_DATE));
--seqsero2 kmerread
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(14, 'seqsero2_kmerread', 'SeqSero2 kmerread ', 't', 14, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 14);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMERREAD_O_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMERREAD_O_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMERREAD_O_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMERREAD_H1_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMERREAD_H1_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMERREAD_H1_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('SEQSERO2_KMERREAD_H2_ANTIGEN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef','SEQSERO2_KMERREAD_H2_ANTIGEN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=SEQSERO2_KMERREAD_H2_ANTIGEN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmerread'), 'SEQSERO2_KMERREAD_O_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmerread'), 'SEQSERO2_KMERREAD_H1_ANTIGEN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='seqsero2_kmerread'), 'SEQSERO2_KMERREAD_H2_ANTIGEN', 1, (SELECT CURRENT_DATE));
--cgMLST
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_0', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_1', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_2', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_3', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_4', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_5', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_6-10', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_11-15', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_15-20', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
--uploader
ALTER TABLE isolates ADD uploader text;
-- AMR new fields
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(15, 'NCBI_AMR_AB_CLASS', 'NDARO AMR database AB classes, https://www.ncbi.nlm.nih.gov/pathogens/refgene/#type:AMR', 't', 15, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 15);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(16, 'NCBI_AMR_AB', 'NDARO AMR database AB subclasses, https://www.ncbi.nlm.nih.gov/pathogens/refgene/#type:AMR', 't', 16, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 16);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(17, 'ResFinder_AB', 'ResFinder database', 't', 17, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 17);
