INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(1, 'MLST_Warwick', 'MLST scheme downloaded and updated weekly from Enterobase.', 't', 1, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(2, 'MLST_Pasteur', 'MLST scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 2, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(3, 'cgMLST', 'cgMLST scheme downloaded and updated weekly from the Pasteur-institute Bigsdb-interface.', 't', 3, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(4, 'Pointfinder', '', 't', 4, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp) VALUES(1, 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp) VALUES(2, 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(5, 'NCBI_AMR', 'NDARO AMR database', 't', 5, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(6, 'ResFinder', 'ResFinder database', 't', 6, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(7, 'VirulenceFinder_Ecoli', 'VirulenceFinder database', 't', 7, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(8, 'VirulenceFinder_Shiga', 'VirulenceFinder database', 't', 8, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(9, 'PlasmidFinder_entero', 'PlasmidFinder enterobacteriaceae', 't', 9, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_AMOXICILLIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_AMOXICILLIN+CLAVULANIC_ACID','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_AMPICILLIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_AMPICILLIN+CLAVULANIC_ACID','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_AZITHROMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_CEFIXIME','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_CEFOTAXIME','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_CEFOXITIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_CEFTAZIDIME','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_CIPROFLOXACIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_COLISTIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_ERYTHROMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_G418','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_GENTAMICIN_C','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_KANAMYCIN_A','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_KASUGAMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_LINEZOLID','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_NALIDIXIC_ACID','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_NEOMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_PAROMOMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_PIPERACILLIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_RIFAMPICIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_SPECTINOMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_STREPTOMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_SULFAMETHOXAZOLE','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_TELITHROMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_TETRACYCLINE,','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_TOBRAMYCIN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('POINTFINDER_UNKNOWN','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_AMOXICILLIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_AMOXICILLIN+CLAVULANIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_AMPICILLIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_AMPICILLIN+CLAVULANIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_AZITHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CEFIXIME', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CEFOTAXIME', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CEFOXITIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CEFTAZIDIME', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CIPROFLOXACIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_COLISTIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_ERYTHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_G418', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_GENTAMICIN_C', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_KANAMYCIN_A', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_KASUGAMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_LINEZOLID', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_NALIDIXIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_NEOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_PAROMOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_PIPERACILLIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_RIFAMPICIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_SPECTINOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_STREPTOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_SULFAMETHOXAZOLE', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_TELITHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_TETRACYCLINE,', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_TOBRAMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_UNKNOWN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbases(id, name, description, dbase_name, dbase_config_name, dbase_view, url, curator, datestamp) VALUES(1, 'bigsdb_stec_isolates', 'Other isolates containing this allele:', 'bigsdb_stec_isolates', 'bigsdb_stec_isolates', 'isolates', '/cgi-bin/bigsdb/bigsdb.pl', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_AMOXICILLIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_AMOXICILLIN+CLAVULANIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_AMPICILLIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_AMPICILLIN+CLAVULANIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_AZITHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_CEFIXIME', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_CEFOTAXIME', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_CEFOXITIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_CEFTAZIDIME', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_CIPROFLOXACIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_COLISTIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_ERYTHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_G418', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_GENTAMICIN_C', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_KANAMYCIN_A', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_KASUGAMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_LINEZOLID', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_NALIDIXIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_NEOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_PAROMOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_PIPERACILLIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_RIFAMPICIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_SPECTINOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_STREPTOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_SULFAMETHOXAZOLE', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_TELITHROMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_TETRACYCLINE,', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_TOBRAMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'POINTFINDER_UNKNOWN', 1, (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(10, 'NCBI_AMR_AB_CLASS', 'NDARO AMR database AB classes, https://www.ncbi.nlm.nih.gov/pathogens/refgene/#type:AMR', 't', 10, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(11, 'NCBI_AMR_AB', 'NDARO AMR database AB subclasses, https://www.ncbi.nlm.nih.gov/pathogens/refgene/#type:AMR', 't', 11, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(12, 'ResFinder_AB', 'ResFinder database', 't', 12, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, no_submissions, disable, curator, date_entered, datestamp) VALUES(13, 'Serotype', 'Serotyping scheme ', 't', 13, 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('O_antigen','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, no_submissions, curator, date_entered, datestamp) VALUES('H_antigen','DNA','text','t', 't','t', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Serotype'), 'O_antigen', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Serotype'), 'H_antigen', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'O_antigen', 1, (SELECT CURRENT_DATE));
INSERT INTO client_dbase_loci(client_dbase_id, locus, curator, datestamp) VALUES(1, 'H_antigen', 1, (SELECT CURRENT_DATE));