
-- INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id)
--             VALUES(1, 'MLST', 'MLST scheme downloaded and updated weekly from Enterobase.', 't', 1, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 1);
-- INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id)
--             VALUES(2, 'cgMLST', 'cgMLST scheme downloaded and updated weekly from Enterobase.', 't', 2, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 2);
-- INSERT INTO scheme_fields(scheme_id, field, type, description, field_order, dropdown, primary_key, curator, datestamp, isolate_display, main_display, query_field)
--             VALUES(1, 'ST', 'integer', 'Sequence Type', 1, 'f', 't', 1, (SELECT CURRENT_DATE), 't', 't', 't');
-- reports fields
-- INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator)
--                 VALUES('html', 'text', 'galaxy report', 'galaxy html report', 't', 't', (SELECT CURRENT_DATE), 1);
-- INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator)
--                 VALUES('tsv', 'text', 'galaxy report', 'galaxy tsv report', 't', 't', (SELECT CURRENT_DATE), 1);
-- AMR
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('NCBI_AMR', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('ResFinder', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(3, 'NCBI_AMR', 'NDARO AMR database', 't', 3, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 3);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(4, 'ResFinder', 'ResFinder database', 't', 4, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 4);
-- Other gene detection
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('VFDB_core', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('PlasmidFinder_entero', 'text', 'Gene detection', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(5, 'VFDB_core', 'VirulenceFactor core database', 't', 5, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 5);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(6, 'PlasmidFinder_entero', 'PlasmidFinder enterobacteriaceae', 't', 6, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 6);
-- counstraints for copying tables
CREATE TABLE eav_text_hidden AS (SELECT * FROM eav_text) WITH NO DATA;
ALTER TABLE eav_text_hidden ADD PRIMARY KEY(isolate_id, field);
ALTER TABLE eav_text_hidden ADD CONSTRAINT eavt_field FOREIGN KEY (field) REFERENCES eav_fields(field) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE eav_text_hidden ADD CONSTRAINT eavt_isolate FOREIGN KEY (isolate_id) REFERENCES isolates(id) ON UPDATE CASCADE ON DELETE CASCADE;
GRANT SELECT, INSERT, UPDATE, DELETE ON eav_text_hidden TO apache;
-- hash not implemented yet
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('hash_fastq_md5_forward', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('hash_fastq_md5_reverse', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
--pointfinder
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('pointfinder_hits', 'text', 'pointfinder', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_SPECTINOMYCIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_SPECTINOMYCIN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_SPECTINOMYCIN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_CIPROFLOXACIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_CIPROFLOXACIN ', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_CIPROFLOXACIN &allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_COLISTIN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_COLISTIN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_COLISTIN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_NALIDIXIC_ACID','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_NALIDIXIC ACID', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_NALIDIXIC ACID&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO loci(id, data_type, allele_id_format, length_varies, coding_sequence, dbase_name, dbase_id, url, isolate_display, main_display, query_field, analysis, submission_template, curator, date_entered, datestamp) VALUES('POINTFINDER_UNKNOWN','DNA','text', 't', 't', 'bigsdb_salmonella_seqdef', 'POINTFINDER_UNKNOWN', '/cgi-bin/bigsdb/bigsdb.pl?db=bigsdb_salmonella_seqdef&page=alleleInfo&locus=POINTFINDER_UNKNOWN&allele_id=[?]', 'allele only', 'f', 't', 't', 'f', 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_SPECTINOMYCIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_CIPROFLOXACIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_COLISTIN', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_NALIDIXIC_ACID', 1, (SELECT CURRENT_DATE));
INSERT INTO scheme_members(scheme_id, locus, curator, datestamp) VALUES((SELECT id FROM schemes WHERE name='Pointfinder'), 'POINTFINDER_UNKNOWN', 1, (SELECT CURRENT_DATE));
--spifinder
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('spifinder_fasta', 'text', 'SPIFinder', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(7, 'spifinder_fasta', 'SPIFinder with assembly', 't', 7, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 7);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('spifinder_fastq', 'text', 'SPIFinder', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(8, 'spifinder_fastq', 'SPIFinder with raw reads', 't', 8, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 8);
--genotyphi
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_ESBLs', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_IncFIAHI1', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_IncHI1A', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_IncHI1BR27', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_IncY', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_aminoglycosides', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_azithromycin', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_beta-lactamases', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_macrolides', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_pST', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_phenicols', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_quinolones', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_sulfonamides', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_tetracyclines', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_trimethoprims', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('genotyphi_susceptibility_z66', 'text', 'Genotyphi', '', 't', 't', (SELECT CURRENT_DATE), 1);
--serotyping
--sistr
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_O_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_H1_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_H2_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('sistr_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(9, 'sistr', 'SISTR ', 't', 9, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 9);
--seqsero2 allele
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_O_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_H1_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_H2_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_allele_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(11, 'seqsero2_allele', 'SeqSero2 allele ', 't', 11, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 11);
--seqsero2 kmer
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_O_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_H1_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_H2_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmer_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(13, 'seqsero2_kmer', 'SeqSero2 kmer ', 't',13, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 13);
--seqsero2 kmerread
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_O_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_H1_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_H2_antigen', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_formula', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, category, description, no_curate, no_submissions, datestamp, curator) VALUES('seqsero2_kmerread_serotype', 'text', 'Serotyping', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO schemes(id, name, description, allow_missing_loci, display_order, curator, date_entered, datestamp, isolate_display, main_display, query_field, query_status, analysis, recommended, quality_metric, dbase_name, dbase_id) VALUES(15, 'seqsero2_kmerread', 'SeqSero2 kmerread ', 't', 15, 1, (SELECT CURRENT_DATE), (SELECT CURRENT_DATE), 't', 't', 't', 'f', 't', 't', 'f', 'bigsdb_salmonella_seqdef', 15);
--cgMLST
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_0', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_1', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_2', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_3', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_4', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_5', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_6-10', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_11-15', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);
INSERT INTO eav_fields(field, value_format, description, no_curate, no_submissions, datestamp, curator) VALUES('cgMLST_differences_15-20', 'text', '', 't', 't', (SELECT CURRENT_DATE), 1);