"""
This script is referenced by SubmitPage.pm in the lib/BIGSdb folder, if its location is modified, it needs to be modified there as well
"""

import argparse
import datetime
import logging
import re
import socket
import sys
import traceback
from pathlib import Path
from typing import Any, Dict, List, Tuple, Union

import pymongo
import yaml
from pymongo.read_concern import ReadConcern
from pymongo.write_concern import WriteConcern

PYTHONPATH = Path(__file__).resolve().parent.parent
sys.path.append(str(PYTHONPATH))

from bioit_custom_scripts.components.psql_tables_queries import TblSubmissions
from bioit_custom_scripts.components.python_utility_functions import get_bigsdb_config_data, send_email
from MongoDB.config import MONGO_CONFIG
from MongoDB.mainmongo import MainMongo
from MongoDB.mongo_to_bigs import mongo_to_bigs
from MongoDB.util.mongo_initialisation import MongoInitialisation


def parse_arguments() -> argparse.Namespace:
    """
    Parses the command line arguments.
    :return: Parsed arguments
    """
    argument_parser = argparse.ArgumentParser()
    argument_parser.add_argument('--db', required=True, type=str)
    return argument_parser.parse_args()

if __name__ == '__main__':
    # Configure stdout logging
    logging.basicConfig(level=logging.DEBUG, stream=sys.stdout)

    # Parse arguments
    args = parse_arguments()
    species = re.sub('bigsdb_|_isolates', '', args.db)
    # Parse config
    with open(MONGO_CONFIG, encoding='utf-8') as handle:
        mongo_config = yaml.safe_load(handle)

    bigsdb_config_data = get_bigsdb_config_data()

    try:

        # Open collections
        mongoinit = MongoInitialisation()
        isolates_collection, old_isolateresults_collection, isolates_badqc_collection, isolates_resequencing_collection = \
            mongoinit.initialise_collections(mongo_config, species)

        # Connect to db and create cursor
        with TblSubmissions(species) as isolates_submissions_psql_tbl:
            query: List[Tuple[Any]] = isolates_submissions_psql_tbl.select_closed_submissions()
            if query:  # todo 09/01/2023 MK I think this is a dangerous approach. If at some point no connection can be made between bigs and mongo, a delay will be acquired. I would modify this to be a for loop, combined with a flagfile to say that this script is running which also contains the start time, if the start time is longer than 10 min ago remove it and restart
                #retrieve id of the isolate and curator id from BIGSdb
                submission_id: str = query[0][0]
                isolate_id: str = query[0][1]
                outcome: str = query[0][2]
                curator_mailadress: str = query[0][3]
                validation_type: str = query[0][4]
                if validation_type == 'bad_quality':
                    results_type = 'badqc_validated'
                elif validation_type == 'resequencing':
                    results_type = 'resequencing_validated'
                else:
                    results_type = '?'  # in order to not have issue 'variable referenced before assignment' and in order to leave possibility open
                #GO into mongo DB
                validation = {
                    'outcome': outcome,
                    'curator': curator_mailadress,
                    'type': results_type.split('_')[0],
                    'date': datetime.datetime.utcnow().strftime('%d/%m/%Y - %X')
                }
                # Note on the behaviour of the script: This scripts runs when a sample has been validated on BIGSdb by a
                # curator. Main steps:
                # 1) The validation outcome is added into the results of the samples (curator name and outcome).
                # 2) If the outcome is 'good', the script mainmongo.py is called in with specific options (see below).
                # In this mode, the mainmongo will retrieve the sample to insert in the isolate collection. It will also
                # add the date of validation (which can't be passed though the json as the date object is not serializable).
                #In addition, path to fasta and vcfile are also added.
                # If the outcome is bad, the date is added to the dict of the validation outcome and this dict is saved into the
                # results of the badqc_isolates
                if outcome == 'good':
                    MainMongo(isolate_id, species, results_type, subvaldict=validation)
                else:
                    validation['date'] = datetime.datetime.utcnow()
                    def _remove_id_from_document_to_be_unique_again_if_bad(collection_in: pymongo.collection.Collection) -> None:
                        """
                        This function modifies the document to not have the unique bioit identifier anymore, but the MongoDB autogenerated one.
                        Appearently the only or easiest way to do this is to reinsert the document.
                        The goal of this manipulation is to be able to insert new resequencings or bad samples.
                        Additionally it adds the validation dict
                        :param collection_in: collection document is in
                        :return: None
                        """
                        negatively_validated_document = dict(collection_in.with_options(read_concern=ReadConcern(level="majority")).find_one({'_id': isolate_id}))
                        negatively_validated_document['validation'] = validation
                        negatively_validated_document.pop('_id')
                        collection_in.with_options(write_concern=WriteConcern(w="majority")).insert_one(negatively_validated_document)  # Modified doc
                        collection_in.with_options(write_concern=WriteConcern(w="majority")).delete_one({'_id': isolate_id})  # Unmodified doc
                    if validation_type == 'bad_quality':
                        _remove_id_from_document_to_be_unique_again_if_bad(isolates_badqc_collection)
                    elif validation_type == 'resequencing':
                        _remove_id_from_document_to_be_unique_again_if_bad(isolates_resequencing_collection)
                #update status once everything is finished
                isolates_submissions_psql_tbl.update_submission((submission_id,))
        mongo_to_bigs(species, single_sample=isolate_id)
    except Exception as exceptionmessage:
        send_email(f"{exceptionmessage}\n{traceback.format_exc()}",
                   f"{Path(__file__).name}: sample validation to mongo fail on host {socket.gethostname()}")
        raise Exception(f"{Path(__file__).name}: sample validation to mongo fail on host {socket.gethostname()}")
