CONNECTION_STRING_ALTERNATE: mongodb+srv://mikelchtermans:YMFOH4BLF1U79dDk@hera-bioit-trial.vajezh0.mongodb.net
CONNECTION_STRING_AZURE: to_be_replaced_by_ansible
CONNECTION_STRING_LOCAL: to_be_replaced_by_ansible

mail:
    from: MongoDB internal HERA
    to: Michael or Ann-Stephan
    host: bioit-mailhog.sciensano.be:1025

species:
    - listeria
    - mycobacterium
    - neisseria
    - stec
    - salmonella
    - influenza
    - sars_cov_2

viral_species:
    - influenza
    - sars_cov_2

dtap: to_be_replaced_by_ansible

collections:
    - isolates
    - old_isolate_results
    - isolates_badqc
    - sequence_types
    - new_allele_hashes
    - cluster_membership
    - cluster_merging
    - update_metadata
    - isolates_resequencing
    - headers
    - mapping_table
    - nominative_labtest_clinical_metadata
    - unprocessed_nominative_labtest_metadata
    - unprocessed_nominative_clinical_metadata
    - isolates_rejected_coreqc

schemes_sequence_typing:
    - mlst
    - cgmlst
    - mlst_warwick
    - mlst_pasteur

temp_dir: /scratch/temp

azure_reportsapi_ip: to_be_replaced_by_ansible

naive_clustering_distance_matrix_file: /var/lib/.bioit_database/distance_matrices/cgmlst_distance_matrix_species_dtap.npy