CONNECTION_STRING_ALTERNATE: mongodb+srv://mikelchtermans:YMFOH4BLF1U79dDk@hera-bioit-trial.vajezh0.mongodb.net
CONNECTION_STRING_BASE: to_be_replaced_by_ansible

mail:
    from: MongoDB internal HERA
    to: Michael or Ann-Stephan
    host: bioit-mailhog.sciensano.be:1025

species:
    - listeria
    - mycobacterium
    - neisseria
    - stec
    - salmonella

dtap: to_be_replaced_by_ansible

collections:
    - isolates
    - old_isolate_results
    - isolates_badqc
    - sequence_types
    - new_allele_hashes
    - cluster_membership
    - cluster_merging
    - update_metadata
    - isolates_resequencing
    - headers

temp_dir: /scratch/temp

htmlreporterpipeline:
    lmod: camel_hera/0.1
    main_script: mainhtmlreporterpipeline.py