enterococcus_faecalis:
  AMRFinder (AMRFinder 3.11.26): amrfinder
  AMRFinder (AMRFinder 4.0.19): amrfinder
  ResFinder (ResFinder 4.4.2): resfinder4
  Virulence Factor DB - Core: vfdb-core
  VirulenceFinder - Enterococcus: virulencefinder
  PlasmidFinder - Gram positive: plasmidfinder
  LRE-Finder (LRE-Finder 20200812): lre-finder
  MOB-recon (MOB-recon 3.1.8): mob-suite
  rMLST taxonomic identification: rmlst
enterococcus_faecium:
  AMRFinder (AMRFinder 3.11.26): amrfinder
  AMRFinder (AMRFinder 4.0.19): amrfinder
  ResFinder (ResFinder 4.4.2): resfinder4
  Virulence Factor DB - Core: vfdb-core
  VirulenceFinder - Enterococcus: virulencefinder
  PlasmidFinder - Gram positive: plasmidfinder
  LRE-Finder (LRE-Finder 20200812): lre-finder
  MOB-recon (MOB-recon 3.1.8): mob-suite
  rMLST taxonomic identification: rmlst
listeria:
  AMRFinder (AMRFinder 3.11.26): amrfinder
  AMRFinder (AMRFinder 4.0.19): amrfinder
  ResFinder (ResFinder 4.4.2): resfinder4
  Virulence Factor DB - Core: vfdb-core
  VirulenceFinder - Listeria: virulencefinder
  PlasmidFinder - Gram positive: plasmidfinder
  MOB-recon (MOB-recon 3.1.8): mob-suite
  rMLST taxonomic identification: rmlst
mycobacterium:
  SNP lineage: snp-lineage
  rMLST taxonomic identification: rmlst
  51 SNP-based: 51snp
  Snpit: snpit
  NCBI-16S: ncbi-16s
  hsp65-based differentiation: hsp65
  Spoligotyping (SpoTyping 2.1): spoligotyping
  AMR detection: amr-detection
neisseria:
  AMRFinder (AMRFinder 3.11.26): amrfinder
  AMRFinder (AMRFinder 4.0.19): amrfinder
  ResFinder (ResFinder 4.4.2): resfinder4
  rMLST taxonomic identification: rmlst
salmonella:
  abriTAMR (AbriTAMR run 1.0.19): abritamr
  AMRFinder (AMRFinder 3.11.26): amrfinder
  AMRFinder (AMRFinder 4.0.19): amrfinder
  ResFinder (ResFinder 4.4.2): resfinder4
  SISTR (SISTR 1.1.1): sistr
  SeqSero2 (SeqSero2 1.2.1): seqsero2
  SPIFinder (SPIFinder 0.1): spifinder
  Virulence Factor DB - Core: vfdb-core
  MOB-recon (MOB-recon 3.1.8): mob-suite
  rMLST taxonomic identification: rmlst
  Mykrobe (mykrobe 0.13.0): mykrobe