listeria:
  listeria_resfinder: ResFinder
  listeria_virulencefinder: VirulenceFinder - <i>Listeria</i>
  listeria_vfdbcore: Virulence Factor DB - Core
  listeria_plasmidfinder': PlasmidFinder - Gram positive
neisseria:
  neisseria_resfinder: ResFinder
stec:
  stec_resfinder: ResFinder
  stec_virulencefinder_ecoli: VirulenceFinder - <i>E. coli</i>
  stec_virulencefinder_shiga: VirulenceFinder - Shiga-toxin genes
  stec_plasmidfinder: PlasmidFinder - Enterobacteriaceae
salmonella':
  salmonella_spifinder: SPIFinder
  salmonella_resfinder: ResFinder
  salmonella_vfdbcore: Virulence Factor DB - Core
  salmonella_abritamr: AbritAMR